#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
FIXTURE_DIR="$ROOT/tools/hako_check/tests/fastmem_capability_inventory"
OUT="$(mktemp "${TMPDIR:-/tmp}/hako_fastmem_capability_inventory.XXXXXX")"
CHECK_OUT="$(mktemp "${TMPDIR:-/tmp}/hako_fastmem_capability_check.XXXXXX")"
trap 'rm -f "$OUT" "$CHECK_OUT"' EXIT

bash "$ROOT/tools/hako_check.sh" fastmem-capability-inventory \
  --report "$FIXTURE_DIR/report.kv" \
  >"$OUT"

grep -q '^output_contract=hako-check-fastmem-capability-inventory-v0$' "$OUT"
grep -q '^tool_surface=hako_check_fastmem_capability_inventory$' "$OUT"
grep -q '^observation_only=1$' "$OUT"
grep -q '^benchmark_run_executed=0$' "$OUT"
grep -q '^keeper_selection=0$' "$OUT"
grep -q '^provider_activation=0$' "$OUT"
grep -q '^hook_installed=0$' "$OUT"
grep -q '^global_allocator_product_claim=0$' "$OUT"
grep -q '^winner_claim=0$' "$OUT"
grep -q '^measured_hot_path_owner=generated_c_replacement_front$' "$OUT"
grep -q '^fastmem_region_count=0$' "$OUT"
grep -q '^fastmem_contract_count=0$' "$OUT"
grep -q '^fastmem_contract_runtime_lookup_count=0$' "$OUT"
grep -q '^fastmem_memop_region_begin_count=0$' "$OUT"
grep -q '^fastmem_memop_region_end_count=0$' "$OUT"
grep -q '^fastmem_memop_unclassified_count=0$' "$OUT"
grep -q '^fastmem_forbidden_call_count=0$' "$OUT"
grep -q '^fastmem_type_abi_hot_lookup_count=0$' "$OUT"
grep -q '^fastmem_provider_abi_crossing_count=0$' "$OUT"
grep -q '^fastmem_escape_count=0$' "$OUT"
grep -q '^fastmem_general_rawptr_type=0$' "$OUT"
grep -q '^fastmem_general_deref_outside_region=0$' "$OUT"
grep -q '^fastmem_general_pointer_arithmetic_outside_region=0$' "$OUT"
grep -q '^free_path_page_lookup_route=page_map_bridge$' "$OUT"
grep -q '^page_map_bridge_kind=flat_side_table$' "$OUT"
grep -q '^page_map_bridge_type_abi_hot_lookup_count=0$' "$OUT"
grep -q '^page_map_bridge_provider_abi_hot_dispatch_count=0$' "$OUT"
grep -q '^page_key_capability=1$' "$OUT"
grep -q '^page_key_numeric_route=uintptr_exact_logical_shift_mask$' "$OUT"
grep -q '^page_key_shift_count_trap=1$' "$OUT"
grep -q '^page_key_segment_shift=25$' "$OUT"
grep -q '^page_key_page_shift=16$' "$OUT"
grep -q '^page_key_mask=0xffff$' "$OUT"
grep -q '^typed_page_meta_handle=1$' "$OUT"
grep -q '^typed_page_meta_layout_verified=1$' "$OUT"
grep -q '^typed_page_meta_layout_id=PageMetaLayoutV0$' "$OUT"
grep -q '^typed_page_meta_layout_hash=fixture-pagemeta-v0$' "$OUT"
grep -q '^typed_page_meta_field_count=7$' "$OUT"
grep -q '^typed_page_meta_required_field_missing_count=0$' "$OUT"
grep -q '^typed_page_meta_field_owner_worker_id=1$' "$OUT"
grep -q '^typed_page_meta_field_block_size=1$' "$OUT"
grep -q '^typed_page_meta_field_free_head=1$' "$OUT"
grep -q '^typed_page_meta_field_local_free_head=1$' "$OUT"
grep -q '^typed_page_meta_field_remote_head=1$' "$OUT"
grep -q '^typed_page_meta_field_capacity=1$' "$OUT"
grep -q '^typed_page_meta_field_used=1$' "$OUT"
grep -q '^fastmem_layout_verified=1$' "$OUT"
grep -q '^fastmem_layout_id=PageMetaLayoutV0$' "$OUT"
grep -q '^fastmem_layout_hash=fixture-pagemeta-v0$' "$OUT"
grep -q '^fastmem_unverified_offset_load_count=0$' "$OUT"
grep -q '^alloc_owner_id_capability=1$' "$OUT"
grep -q '^alloc_owner_id_kind=allocator_arena_owner$' "$OUT"
grep -q '^alloc_owner_id_source=benchmark_c_pthread_tls$' "$OUT"
grep -q '^alloc_owner_id_width_bits=64$' "$OUT"
grep -q '^alloc_owner_id_generation_enabled=1$' "$OUT"
grep -q '^alloc_owner_id_zero_is_unowned=1$' "$OUT"
grep -q '^alloc_owner_id_escape_count=0$' "$OUT"
grep -q '^worker_id_capability=1$' "$OUT"
grep -q '^worker_id_kind=allocator_arena_owner$' "$OUT"
grep -q '^worker_id_source=benchmark_c_pthread_tls$' "$OUT"
grep -q '^worker_id_equals_os_thread_id_claim=0$' "$OUT"
grep -q '^worker_id_equals_runtime_worker_id_claim=0$' "$OUT"
grep -q '^worker_id_equals_hako_task_id_claim=0$' "$OUT"
grep -q '^worker_id_escape_count=0$' "$OUT"
grep -q '^allocator_tls_arena_enabled=1$' "$OUT"
grep -q '^allocator_tls_arena_mode=benchmark_c_tls$' "$OUT"
grep -q '^allocator_tls_arena_init_count=2$' "$OUT"
grep -q '^allocator_tls_arena_live_count=2$' "$OUT"
grep -q '^allocator_tls_arena_peak_count=2$' "$OUT"
grep -q '^allocator_tls_arena_reuse_count=0$' "$OUT"
grep -q '^allocator_tls_arena_init_fail_count=0$' "$OUT"
grep -q '^allocator_tls_arena_fallback_count=0$' "$OUT"
grep -q '^allocator_thread_exit_flush_supported=0$' "$OUT"
grep -q '^page_owner_check_enabled=1$' "$OUT"
grep -q '^page_owner_check_route=page_meta_owner_worker_id$' "$OUT"
grep -q '^page_owner_check_count=8163984$' "$OUT"
grep -q '^page_owner_same_count=8163984$' "$OUT"
grep -q '^page_owner_remote_count=0$' "$OUT"
grep -q '^page_owner_unowned_count=0$' "$OUT"
grep -q '^page_owner_stale_generation_count=0$' "$OUT"
grep -q '^page_owner_invalid_count=0$' "$OUT"
grep -q '^page_owner_count_mismatch=0$' "$OUT"
grep -q '^same_owner_free_local_candidate_count=8163984$' "$OUT"
grep -q '^same_owner_free_local_push_count=0$' "$OUT"
grep -q '^remote_owner_free_remote_candidate_count=0$' "$OUT"
grep -q '^remote_owner_free_remote_push_count=0$' "$OUT"
grep -q '^atomic_remote_head_enabled=0$' "$OUT"
grep -q '^replacement_front_is_full_hako_algorithm=0$' "$OUT"
grep -q '^hako_mimalloc_algorithm_claim=0$' "$OUT"
grep -q '^product_activation_ready=0$' "$OUT"
grep -q '^summary=ok$' "$OUT"

bash "$ROOT/tools/hako_check.sh" fastmem-capability-inventory \
  --report "$FIXTURE_DIR/safe_capability_wrapper_report.kv" \
  >"$OUT"

grep -q '^safe_capability_wrapper_plan=1$' "$OUT"
grep -q '^safe_capability_wrapper_route=fastmem_memop_alias$' "$OUT"
grep -q '^safe_capability_wrapper_lowering_route=fastmem_memop_alias$' "$OUT"
grep -q '^safe_capability_wrapper_memop_equivalence=1$' "$OUT"
grep -q '^safe_capability_wrapper_count=6$' "$OUT"
grep -q '^safe_capability_wrapper_missing_count=0$' "$OUT"
grep -q '^safe_capability_wrapper_rawptr_surface=0$' "$OUT"
grep -q '^safe_capability_wrapper_deref_surface=0$' "$OUT"
grep -q '^safe_capability_wrapper_escape_count=0$' "$OUT"
grep -q '^address_token_capability=1$' "$OUT"
grep -q '^address_token_escape_check=pass$' "$OUT"
grep -q '^address_token_deref_allowed=0$' "$OUT"
grep -q '^address_token_pointer_arithmetic_allowed=0$' "$OUT"
grep -q '^address_token_wrapper=1$' "$OUT"
grep -q '^page_key_wrapper=1$' "$OUT"
grep -q '^page_map_bridge_wrapper=1$' "$OUT"
grep -q '^page_meta_handle_wrapper=1$' "$OUT"
grep -q '^alloc_owner_id_wrapper=1$' "$OUT"
grep -q '^atomic_remote_head_wrapper=1$' "$OUT"
grep -q '^atomic_remote_head_enabled=1$' "$OUT"
grep -q '^type_abi_hot_path_lookup_count=0$' "$OUT"
grep -q '^provider_dispatch_hot_path=0$' "$OUT"
grep -q '^product_activation_ready=0$' "$OUT"
grep -q '^summary=ok$' "$OUT"

bash "$ROOT/tools/hako_check.sh" fastmem-check \
  --report "$FIXTURE_DIR/safe_capability_wrapper_report.kv" \
  --format kv \
  >"$CHECK_OUT"

grep -q '^failure_count=0$' "$CHECK_OUT"
grep -q '^summary=ok$' "$CHECK_OUT"

bash "$ROOT/tools/hako_check.sh" fastmem-capability-inventory \
  --report "$FIXTURE_DIR/shape_coverage_keeper_report.kv" \
  >"$OUT"

grep -q '^mimalloc_keeper_candidate=1$' "$OUT"
grep -q '^mimalloc_keeper_eligible=1$' "$OUT"
grep -q '^mimalloc_keeper_block_reason=eligible$' "$OUT"
grep -q '^mimalloc_speed_score=100$' "$OUT"
grep -q '^mimalloc_shape_score=100$' "$OUT"
grep -q '^mimalloc_safety_score=100$' "$OUT"
grep -q '^mimalloc_coverage_score=100$' "$OUT"
grep -q '^mimalloc_shape_component_count=10$' "$OUT"
grep -q '^mimalloc_shape_component_page_map_bridge=1$' "$OUT"
grep -q '^mimalloc_shape_component_typed_page_meta=1$' "$OUT"
grep -q '^mimalloc_shape_component_tls_arena=1$' "$OUT"
grep -q '^mimalloc_shape_component_alloc_owner=1$' "$OUT"
grep -q '^mimalloc_shape_component_owner_check=1$' "$OUT"
grep -q '^mimalloc_shape_component_same_owner_local_free=1$' "$OUT"
grep -q '^mimalloc_shape_component_atomic_remote_head=1$' "$OUT"
grep -q '^mimalloc_shape_component_safe_wrappers=1$' "$OUT"
grep -q '^mimalloc_shape_component_no_global_lock_hot_path=1$' "$OUT"
grep -q '^mimalloc_shape_component_no_range_scan_hot_path=1$' "$OUT"
grep -q '^product_activation_ready=0$' "$OUT"
grep -q '^summary=ok$' "$OUT"

bash "$ROOT/tools/hako_check.sh" fastmem-check \
  --report "$FIXTURE_DIR/shape_coverage_keeper_report.kv" \
  --format kv \
  >"$CHECK_OUT"

grep -q '^failure_count=0$' "$CHECK_OUT"
grep -q '^summary=ok$' "$CHECK_OUT"

echo "[TEST/OK] fastmem_capability_inventory"
