#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$(mktemp "${TMPDIR:-/tmp}/hako_llvm_pipeline_inventory.XXXXXX")"
trap 'rm -f "$OUT"' EXIT

bash "$ROOT/tools/hako_check.sh" llvm-pipeline-inventory >"$OUT"

grep -q '^output_contract=hako-check-llvm-pipeline-inventory-v0$' "$OUT"
grep -q '^tool_surface=hako_check_llvm_pipeline_inventory$' "$OUT"
grep -q '^observation_only=1$' "$OUT"
grep -q '^rewrite_executed=0$' "$OUT"
grep -q '^source_rewrite_executed=0$' "$OUT"
grep -q '^benchmark_run_executed=0$' "$OUT"
grep -q '^behavior_change=0$' "$OUT"
grep -q '^mir_future_rewrite_forced=1$' "$OUT"
grep -q '^mir_future_rewrite_env_key=NYASH_REWRITE_FUTURE$' "$OUT"
grep -q '^mir_future_rewrite_env_restore_guard=1$' "$OUT"
grep -q '^mir_future_rewrite_consumed_by_normalize=1$' "$OUT"
grep -q '^mir_future_rewrite_route=FutureNew/FutureSet/Await->env.future$' "$OUT"
grep -q '^method_id_injector_stage_present=1$' "$OUT"
grep -q '^method_id_injector_called=1$' "$OUT"
grep -q '^method_id_injector_noop_stub=1$' "$OUT"
grep -q '^method_id_injector_mutation_count=0$' "$OUT"
grep -q '^joinir_experiment_hook_called=1$' "$OUT"
grep -q '^joinir_experiment_feature_gate=llvm-harness$' "$OUT"
grep -q '^joinir_experiment_feature_gated=1$' "$OUT"
grep -q '^joinir_experiment_env_gate=NYASH_JOINIR_EXPERIMENT+NYASH_JOINIR_LLVM_EXPERIMENT+NYASH_LLVM_USE_HARNESS$' "$OUT"
grep -q '^joinir_experiment_env_gated=1$' "$OUT"
grep -q '^joinir_experiment_fallback_policy=original_mir$' "$OUT"
grep -q '^joinir_experiment_original_mir_fallback=1$' "$OUT"
grep -q '^pyvm_executor_stage_present=1$' "$OUT"
grep -q '^pyvm_reachable=1$' "$OUT"
grep -q '^pyvm_gate=SMOKES_USE_PYVM$' "$OUT"
grep -q '^pyvm_daily_route=0$' "$OUT"
grep -q '^pyvm_withdrawn_policy=diagnostic_only$' "$OUT"
grep -q '^llvm_obj_out_stage_present=1$' "$OUT"
grep -q '^llvm_harness_stage_present=1$' "$OUT"
grep -q '^llvm_harness_feature_gate=llvm-harness$' "$OUT"
grep -q '^llvm_harness_default_enabled=1$' "$OUT"
grep -q '^llvmlite_daily_owner=0$' "$OUT"
grep -q '^mock_fallback_stage_present=1$' "$OUT"
grep -q '^mock_fallback_reachable=1$' "$OUT"
grep -q '^mock_fallback_blocked_when_harness_explicit=1$' "$OUT"
grep -q '^execution_backend_order=pyvm,obj_out,ny_llvmc_exe,mock$' "$OUT"
grep -q '^execution_backend_runtime_sample=0$' "$OUT"
grep -q '^llvm_fallback_used=0$' "$OUT"
grep -q '^llvm_fallback_reason=static_inventory_only$' "$OUT"
grep -q '^type_abi_hot_lookup_count=0$' "$OUT"
grep -q '^provider_abi_hot_dispatch_count=0$' "$OUT"
grep -q '^product_activation=0$' "$OUT"
grep -q '^hook_installed=0$' "$OUT"
grep -q '^global_allocator_product_claim=0$' "$OUT"
grep -q '^winner_claim=0$' "$OUT"
grep -q '^failure_count=0$' "$OUT"
grep -q '^summary=ok$' "$OUT"

echo "[TEST/OK] llvm_pipeline_inventory"
