use super::super::backend;
use super::super::contract;
use std::fmt::Write as _;

pub(crate) fn emit_summary_to_stderr() {
    let snapshot = backend::snapshot();
    let str_concat2_classified =
        snapshot[47] + snapshot[48] + snapshot[49] + snapshot[50] + snapshot[51];
    let str_concat2_unclassified = snapshot[45].saturating_sub(str_concat2_classified);
    let str_len_classified = snapshot[54] + snapshot[55] + snapshot[56];
    let str_len_unclassified = snapshot[52].saturating_sub(str_len_classified);
    eprintln!(
        "[perf/counter][{}] total={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={}",
        contract::STORE_ARRAY_STR,
        snapshot[0],
        contract::STORE_ARRAY_STR_CACHE_HIT,
        snapshot[1],
        contract::STORE_ARRAY_STR_CACHE_MISS_HANDLE,
        snapshot[2],
        contract::STORE_ARRAY_STR_CACHE_MISS_EPOCH,
        snapshot[3],
        contract::STORE_ARRAY_STR_RETARGET_HIT,
        snapshot[4],
        contract::STORE_ARRAY_STR_SOURCE_STORE,
        snapshot[5],
        contract::STORE_ARRAY_STR_NON_STRING_SOURCE,
        snapshot[6],
        contract::STORE_ARRAY_STR_EXISTING_SLOT,
        snapshot[7],
        contract::STORE_ARRAY_STR_APPEND_SLOT,
        snapshot[8],
        contract::STORE_ARRAY_STR_SOURCE_STRING_BOX,
        snapshot[9],
        contract::STORE_ARRAY_STR_SOURCE_STRING_VIEW,
        snapshot[10],
        contract::STORE_ARRAY_STR_SOURCE_MISSING,
        snapshot[11],
    );
    eprintln!(
        "[perf/counter][{}] total={} {}={} {}={} {}={} {}={} {}={} {}={}",
        contract::CONST_SUFFIX,
        snapshot[12],
        contract::CONST_SUFFIX_CACHED_HANDLE_HIT,
        snapshot[13],
        contract::CONST_SUFFIX_TEXT_CACHE_RELOAD,
        snapshot[14],
        contract::CONST_SUFFIX_FREEZE_FALLBACK,
        snapshot[15],
        contract::CONST_SUFFIX_EMPTY_RETURN,
        snapshot[16],
        contract::CONST_SUFFIX_CACHED_FAST_STR_HIT,
        snapshot[17],
        contract::CONST_SUFFIX_CACHED_SPAN_HIT,
        snapshot[18],
    );
    eprintln!(
        "[perf/counter][{}] {}={} {}={} {}={} {}={} {}={} {}={}",
        contract::BIRTH_PLACEMENT,
        contract::BIRTH_PLACEMENT_RETURN_HANDLE,
        snapshot[19],
        contract::BIRTH_PLACEMENT_BORROW_VIEW,
        snapshot[20],
        contract::BIRTH_PLACEMENT_FREEZE_OWNED,
        snapshot[21],
        contract::BIRTH_PLACEMENT_FRESH_HANDLE,
        snapshot[22],
        contract::BIRTH_PLACEMENT_MATERIALIZE_OWNED,
        snapshot[23],
        contract::BIRTH_PLACEMENT_STORE_FROM_SOURCE,
        snapshot[24],
    );
    let mut birth_backend_line = format!("[perf/counter][{}]", contract::BIRTH_BACKEND);
    for (name, value) in [
        (contract::BIRTH_BACKEND_FREEZE_TEXT_PLAN_TOTAL, snapshot[25]),
        (contract::BIRTH_BACKEND_FREEZE_TEXT_PLAN_VIEW1, snapshot[26]),
        (contract::BIRTH_BACKEND_FREEZE_TEXT_PLAN_PIECES2, snapshot[27]),
        (contract::BIRTH_BACKEND_FREEZE_TEXT_PLAN_PIECES3, snapshot[28]),
        (contract::BIRTH_BACKEND_FREEZE_TEXT_PLAN_PIECES4, snapshot[29]),
        (contract::BIRTH_BACKEND_FREEZE_TEXT_PLAN_OWNED_TMP, snapshot[30]),
        (contract::BIRTH_BACKEND_STRING_BOX_NEW_TOTAL, snapshot[31]),
        (contract::BIRTH_BACKEND_STRING_BOX_NEW_BYTES, snapshot[32]),
        (contract::BIRTH_BACKEND_STRING_BOX_CTOR_TOTAL, snapshot[33]),
        (contract::BIRTH_BACKEND_STRING_BOX_CTOR_BYTES, snapshot[34]),
        (contract::BIRTH_BACKEND_ARC_WRAP_TOTAL, snapshot[35]),
        (
            contract::BIRTH_BACKEND_OBJECTIZE_STABLE_BOX_NOW_TOTAL,
            snapshot[36],
        ),
        (
            contract::BIRTH_BACKEND_OBJECTIZE_STABLE_BOX_NOW_BYTES,
            snapshot[37],
        ),
        (contract::BIRTH_BACKEND_HANDLE_ISSUE_TOTAL, snapshot[38]),
        (contract::BIRTH_BACKEND_ISSUE_FRESH_HANDLE_TOTAL, snapshot[39]),
        (contract::BIRTH_BACKEND_MATERIALIZE_OWNED_TOTAL, snapshot[40]),
        (contract::BIRTH_BACKEND_MATERIALIZE_OWNED_BYTES, snapshot[41]),
        (contract::BIRTH_BACKEND_GC_ALLOC_CALLED, snapshot[42]),
        (contract::BIRTH_BACKEND_GC_ALLOC_BYTES, snapshot[43]),
        (contract::BIRTH_BACKEND_GC_ALLOC_SKIPPED, snapshot[44]),
    ] {
        let _ = write!(&mut birth_backend_line, " {}={}", name, value);
    }
    eprintln!("{}", birth_backend_line);
    eprintln!(
        "[perf/counter][{}] {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={}",
        contract::STR_CONCAT2_ROUTE,
        contract::STR_CONCAT2_ROUTE_TOTAL,
        snapshot[45],
        contract::STR_CONCAT2_ROUTE_DISPATCH_HIT,
        snapshot[46],
        contract::STR_CONCAT2_ROUTE_FAST_STR_OWNED,
        snapshot[47],
        contract::STR_CONCAT2_ROUTE_FAST_STR_RETURN_HANDLE,
        snapshot[48],
        contract::STR_CONCAT2_ROUTE_SPAN_FREEZE,
        snapshot[49],
        contract::STR_CONCAT2_ROUTE_SPAN_RETURN_HANDLE,
        snapshot[50],
        contract::STR_CONCAT2_ROUTE_MATERIALIZE_FALLBACK,
        snapshot[51],
        contract::STR_CONCAT2_ROUTE_UNCLASSIFIED,
        str_concat2_unclassified,
    );
    eprintln!(
        "[perf/counter][{}] {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={}",
        contract::STR_LEN_ROUTE,
        contract::STR_LEN_ROUTE_TOTAL,
        snapshot[52],
        contract::STR_LEN_ROUTE_DISPATCH_HIT,
        snapshot[53],
        contract::STR_LEN_ROUTE_FAST_STR_HIT,
        snapshot[54],
        contract::STR_LEN_ROUTE_FALLBACK_HIT,
        snapshot[55],
        contract::STR_LEN_ROUTE_MISS,
        snapshot[56],
        contract::STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FAST_STR_HIT,
        snapshot[57],
        contract::STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FALLBACK_HIT,
        snapshot[58],
        contract::STR_LEN_ROUTE_UNCLASSIFIED,
        str_len_unclassified,
    );
    let stable_box_demand = nyash_rust::runtime::host_handles::perf_observe_snapshot();
    eprintln!(
        "[perf/counter][{}] {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={} {}={}",
        contract::STABLE_BOX_DEMAND,
        contract::STABLE_BOX_DEMAND_OBJECT_GET_LATEST_FRESH,
        stable_box_demand[0],
        contract::STABLE_BOX_DEMAND_OBJECT_WITH_HANDLE_LATEST_FRESH,
        stable_box_demand[1],
        contract::STABLE_BOX_DEMAND_OBJECT_PAIR_LATEST_FRESH,
        stable_box_demand[2],
        contract::STABLE_BOX_DEMAND_OBJECT_TRIPLE_LATEST_FRESH,
        stable_box_demand[3],
        contract::STABLE_BOX_DEMAND_TEXT_READ_HANDLE_LATEST_FRESH,
        stable_box_demand[4],
        contract::STABLE_BOX_DEMAND_TEXT_READ_PAIR_LATEST_FRESH,
        stable_box_demand[5],
        contract::STABLE_BOX_DEMAND_TEXT_READ_TRIPLE_LATEST_FRESH,
        stable_box_demand[6],
        contract::STABLE_BOX_DEMAND_OBJECT_WITH_HANDLE_ARRAY_STORE_STR_SOURCE_LATEST_FRESH,
        stable_box_demand[7],
        contract::STABLE_BOX_DEMAND_OBJECT_WITH_HANDLE_SUBSTRING_PLAN_LATEST_FRESH,
        stable_box_demand[8],
        contract::STABLE_BOX_DEMAND_OBJECT_WITH_HANDLE_DECODE_ARRAY_FAST_LATEST_FRESH,
        stable_box_demand[9],
        contract::STABLE_BOX_DEMAND_OBJECT_WITH_HANDLE_DECODE_ANY_ARG_LATEST_FRESH,
        stable_box_demand[10],
        contract::STABLE_BOX_DEMAND_OBJECT_WITH_HANDLE_DECODE_ANY_INDEX_LATEST_FRESH,
        stable_box_demand[11],
    );
}
