#!/usr/bin/env python3
"""Generate the Hako parser's typed Language v1 registry projection."""

from __future__ import annotations

import argparse
import pathlib
import sys

if __package__:
    from .grammar_contract_registry import load_registry_rows
else:
    from grammar_contract_registry import load_registry_rows


ROOT = pathlib.Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = (
    ROOT / "lang/src/compiler/parser/generated/grammar_contract_projection.hako"
)


def _escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def render() -> str:
    rows = load_registry_rows()
    by_row: dict[str, dict[str, object]] = {}
    for row in rows:
        by_row.setdefault(row.row_id, {})[row.profile.lower()] = row

    lines = [
        "// @generated by tools/language_v1/generate_hako_grammar_contract.py",
        "// Do not edit by hand. Registry/profile authority stays in grammar/language-v1-registry.toml.",
        "",
        "static box GrammarContractProjection {",
    ]
    for method, field, missing in [
        ("status", "status", "missing"),
        ("normalized_shape", "normalized_shape", ""),
        ("stable_reject_tag", "stable_reject_tag", "parser/registry_row_missing"),
    ]:
        lines.append(f"  {method}(row_id, profile) {{")
        for row_id, profiles in by_row.items():
            canonical = profiles["canonical"]
            compat = profiles["compat2025"]
            canonical_value = _escape(str(getattr(canonical, field)))
            compat_value = _escape(str(getattr(compat, field)))
            lines.append(f'    if row_id == "{_escape(row_id)}" {{')
            lines.append(
                f'      if profile == "canonical" {{ return "{canonical_value}" }}'
            )
            lines.append(
                f'      if profile == "compat2025" {{ return "{compat_value}" }}'
            )
            lines.append('      return "parser/profile_mismatch"')
            lines.append("    }")
        lines.append(f'    return "{_escape(missing)}"')
        lines.append("  }")
        lines.append("")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=pathlib.Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if actual != expected:
            print("parser/hako_grammar_contract_projection_stale", file=sys.stderr)
            return 1
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
