#[path = "../parser_birth_once_cycle.rs"]
pub mod parser_birth_once_cycle;
#[path = "../parser_bitops_test.rs"]
pub mod parser_bitops_test;
#[cfg(feature = "legacy-tests")]
#[path = "../parser_block_postfix_catch.rs"]
pub mod parser_block_postfix_catch;
#[path = "../parser_block_postfix_errors.rs"]
pub mod parser_block_postfix_errors;
#[path = "../parser_enum_match.rs"]
pub mod parser_enum_match;
#[path = "../parser_enum_surface.rs"]
pub mod parser_enum_surface;
#[cfg(feature = "legacy-tests")]
#[path = "../parser_expr_postfix_catch.rs"]
pub mod parser_expr_postfix_catch;
#[path = "../parser_header_param_extensions.rs"]
pub mod parser_header_param_extensions;
#[cfg(feature = "legacy-tests")]
#[path = "../parser_lambda.rs"]
pub mod parser_lambda;
#[path = "../parser_lambda_call.rs"]
pub mod parser_lambda_call;
#[path = "../parser_loop_scan_range_shape.rs"]
pub mod parser_loop_scan_range_shape;
#[path = "../parser_method_postfix.rs"]
pub mod parser_method_postfix;
#[path = "../parser_null_void_surface.rs"]
pub mod parser_null_void_surface;
#[path = "../parser_opt_annotations.rs"]
pub mod parser_opt_annotations;
#[path = "../parser_outbox_contract.rs"]
pub mod parser_outbox_contract;
#[path = "../parser_parent_colon.rs"]
pub mod parser_parent_colon;
#[cfg(feature = "legacy-tests")]
#[path = "../parser_peek_block.rs"]
pub mod parser_peek_block;
#[path = "../parser_scope_exit_fini.rs"]
pub mod parser_scope_exit_fini;
#[cfg(feature = "legacy-tests")]
#[path = "../parser_semicolon.rs"]
pub mod parser_semicolon;
#[path = "../parser_static_box_members.rs"]
pub mod parser_static_box_members;
#[path = "../parser_unified_members_get.rs"]
pub mod parser_unified_members_get;
#[path = "../parser_unified_members_property_emit.rs"]
pub mod parser_unified_members_property_emit;
#[path = "../parser_weak_field_contract.rs"]
pub mod parser_weak_field_contract;
#[path = "../tokenizer_unicode_toggle.rs"]
pub mod tokenizer_unicode_toggle;
