pub fn object_storage_plan_report_fields() -> &'static [(&'static str, &'static str)] {
    &[
        ("output_contract", "hako-object-storage-plan-ssot-v0"),
        ("mirbuilder_object_management_enabled", "0"),
        ("mirbuilder_records_object_meaning", "1"),
        ("box_callable_registry_is_callable_truth", "1"),
        ("routeplan_is_call_execution_truth", "1"),
        ("object_storage_plan_is_representation_truth", "1"),
        ("object_storage_plan_vocabulary_defined", "1"),
        ("objectplan_canonical_vocabulary_defined", "1"),
        ("objectplan_is_representation_truth", "1"),
        ("objectplan_is_publication_site_truth", "1"),
        ("local_first_object_plan_alias_retired", "1"),
        ("object_site_location_vocabulary_defined", "1"),
        ("object_site_location_field_migration_enabled", "1"),
        ("object_publication_site_location_field_migrated", "1"),
        ("local_fastpath_fact_location_field_migrated", "1"),
        ("local_publication_inventory_location_field_migrated", "1"),
        ("publication_site_generic_inventory_defined", "1"),
        ("publication_reason_vocabulary_count", "8"),
        ("unknown_publication_forces_generic_fallback", "1"),
        ("routeplan_objectplan_handoff_contract_defined", "1"),
        ("routeplan_owns_execution_not_representation", "1"),
        ("objectplan_owns_representation_not_execution", "1"),
        ("backend_requires_routeplan_for_direct_call", "1"),
        ("backend_requires_objectplan_for_representation_bypass", "1"),
        ("backend_plan_consumer_guard_enabled", "1"),
        (
            "backend_plan_consumer_requires_routeplan_and_objectplan",
            "1",
        ),
        ("backend_existing_flattened_nested_consumer_allowed", "1"),
        ("backend_new_lowering_enabled", "0"),
        ("backend_helper_symbol_inference_enabled", "0"),
        ("backend_method_name_special_case_enabled", "0"),
        ("backend_variable_name_special_case_enabled", "0"),
        ("object_plan_local_first_vocabulary_defined", "1"),
        ("object_plan_publication_sites_defined", "1"),
        ("standalone_publication_plan_enabled", "0"),
        ("unknown_publication_forces_generic_fallback", "1"),
        ("publication_state_vocabulary_defined", "1"),
        ("publication_state_unpublished_fastpath_allowed", "1"),
        ("publication_state_published_fastpath_allowed", "0"),
        ("publication_state_maybe_published_fastpath_allowed", "0"),
        ("local_fastpath_fallback_reason_vocabulary_defined", "1"),
        ("local_fastpath_fact_vocabulary_defined", "1"),
        ("local_fastpath_fact_backend_consumable", "1"),
        ("fallback_evidence_backend_consumable", "0"),
        ("fallback_fact_enabled", "0"),
        ("backend_reads_local_fastpath_fact_only", "1"),
        ("full_escape_engine_required_for_v0", "0"),
        ("interprocedural_fixedpoint_required_for_v0", "0"),
        ("local_alias_class_mvp_vocabulary_defined", "1"),
        ("local_alias_class_mvp_source_count", "5"),
        ("local_alias_class_heap_graph_enabled", "0"),
        ("local_alias_class_field_sensitive_points_to_enabled", "0"),
        ("local_publication_inventory_v2_vocabulary_defined", "1"),
        ("local_publication_inventory_v2_report_only", "1"),
        ("local_publication_inventory_v2_backend_consumable", "0"),
        ("local_publication_inventory_v2_unknown_alias_fallback", "1"),
        (
            "local_publication_inventory_v2_maybe_published_fallback",
            "1",
        ),
        ("local_known_receiver_direct_call_shadow_defined", "1"),
        (
            "local_known_receiver_direct_call_shadow_backend_consumable",
            "0",
        ),
        ("local_known_receiver_direct_call_shadow_fact_optional", "1"),
        (
            "local_known_receiver_direct_call_shadow_requires_routeplan",
            "1",
        ),
        (
            "local_known_receiver_direct_call_shadow_requires_objectstorageplan",
            "1",
        ),
        ("flattened_nested_field_layout_vocabulary_defined", "1"),
        ("object_storage_plan_execution_enabled", "0"),
        ("object_plan_execution_enabled", "0"),
        ("exact_object_shadow_ready", "1"),
        ("product_default_changed", "0"),
    ]
}
