#[path = "../mir_array_element_write_lowering.rs"]
pub mod mir_array_element_write_lowering;
#[cfg(feature = "vm-reference")]
#[path = "../mir_array_element_write_vm.rs"]
pub mod mir_array_element_write_vm;
#[path = "../mir_box_new_field_initializer.rs"]
pub mod mir_box_new_field_initializer;
#[path = "../mir_brand_constructor.rs"]
pub mod mir_brand_constructor;
#[path = "../mir_breakfinder_ssa.rs"]
pub mod mir_breakfinder_ssa;
#[path = "../mir_compound_assignment_evaluated_place.rs"]
pub mod mir_compound_assignment_evaluated_place;
#[path = "../mir_core13_normalize.rs"]
pub mod mir_core13_normalize;
#[path = "../mir_corebox_router_unified.rs"]
pub mod mir_corebox_router_unified;
#[path = "../mir_effect_capability_plan.rs"]
pub mod mir_effect_capability_plan;
#[path = "../mir_guard_let_enummatch.rs"]
pub mod mir_guard_let_enummatch;
#[path = "../mir_inline_plan.rs"]
pub mod mir_inline_plan;
#[path = "../mir_locals_ssa.rs"]
pub mod mir_locals_ssa;
#[path = "../mir_move_contract.rs"]
pub mod mir_move_contract;
#[path = "../mir_outbox_contract.rs"]
pub mod mir_outbox_contract;
#[path = "../mir_parameter_binding_identity.rs"]
pub mod mir_parameter_binding_identity;
#[path = "../mir_peek_lower.rs"]
pub mod mir_peek_lower;
#[cfg(feature = "vm-reference")]
#[path = "../mir_pure_e2e_arith.rs"]
pub mod mir_pure_e2e_arith;
#[cfg(feature = "vm-reference")]
#[path = "../mir_pure_e2e_branch.rs"]
pub mod mir_pure_e2e_branch;
#[cfg(feature = "vm-reference")]
#[path = "../mir_pure_e2e_vm.rs"]
pub mod mir_pure_e2e_vm;
#[path = "../mir_pure_envbox.rs"]
pub mod mir_pure_envbox;
#[path = "../mir_pure_llvm_build.rs"]
pub mod mir_pure_llvm_build;
#[path = "../mir_pure_llvm_parity.rs"]
pub mod mir_pure_llvm_parity;
#[cfg(feature = "vm-reference")]
#[path = "../mir_scope_exit_fini_vm.rs"]
pub mod mir_scope_exit_fini_vm;
#[cfg(feature = "vm-reference")]
#[path = "../mir_stage1_cli_emit_program_min.rs"]
pub mod mir_stage1_cli_emit_program_min;
#[cfg(feature = "vm-reference")]
#[path = "../mir_static_const_table_load.rs"]
pub mod mir_static_const_table_load;
#[path = "../mir_unified_members_property_read.rs"]
pub mod mir_unified_members_property_read;
#[path = "../mir_user_box_method_determinism.rs"]
pub mod mir_user_box_method_determinism;
#[path = "../mir_value_kind.rs"]
pub mod mir_value_kind;
#[cfg(feature = "vm-reference")]
#[path = "../record_construction_ergonomics.rs"]
pub mod record_construction_ergonomics;
