#[path = "../mir_breakfinder_ssa.rs"]
pub mod mir_breakfinder_ssa;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_controlflow_extras.rs"]
pub mod mir_controlflow_extras;
#[path = "../mir_core13_normalize.rs"]
pub mod mir_core13_normalize;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_ctrlflow_break_continue.rs"]
pub mod mir_ctrlflow_break_continue;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_funcscanner_parse_params_trim_min.rs"]
pub mod mir_funcscanner_parse_params_trim_min;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_funcscanner_skip_ws.rs"]
pub mod mir_funcscanner_skip_ws;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_funcscanner_skip_ws_min.rs"]
pub mod mir_funcscanner_skip_ws_min;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_funcscanner_ssa.rs"]
pub mod mir_funcscanner_ssa;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_funcscanner_trim_min.rs"]
pub mod mir_funcscanner_trim_min;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_lambda_functionbox.rs"]
pub mod mir_lambda_functionbox;
#[path = "../mir_locals_ssa.rs"]
pub mod mir_locals_ssa;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_loopform_complex.rs"]
pub mod mir_loopform_complex;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_loopform_conditional_reassign.rs"]
pub mod mir_loopform_conditional_reassign;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_loopform_exit_phi.rs"]
pub mod mir_loopform_exit_phi;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_no_phi_merge_tests.rs"]
pub mod mir_no_phi_merge_tests;
#[path = "../mir_outbox_contract.rs"]
pub mod mir_outbox_contract;
#[path = "../mir_move_contract.rs"]
pub mod mir_move_contract;
#[path = "../mir_peek_lower.rs"]
pub mod mir_peek_lower;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_phi_basic_verify.rs"]
pub mod mir_phi_basic_verify;
#[path = "../mir_pure_e2e_arith.rs"]
pub mod mir_pure_e2e_arith;
#[path = "../mir_pure_e2e_branch.rs"]
pub mod mir_pure_e2e_branch;
#[path = "../mir_pure_e2e_vm.rs"]
pub mod mir_pure_e2e_vm;
#[path = "../mir_pure_envbox.rs"]
pub mod mir_pure_envbox;
#[path = "../mir_pure_llvm_build.rs"]
pub mod mir_pure_llvm_build;
#[path = "../mir_pure_llvm_parity.rs"]
pub mod mir_pure_llvm_parity;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_pure_locals_normalized.rs"]
pub mod mir_pure_locals_normalized;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_pure_only_core13.rs"]
pub mod mir_pure_only_core13;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_qmark_lower.rs"]
pub mod mir_qmark_lower;
#[path = "../mir_scope_exit_fini_vm.rs"]
pub mod mir_scope_exit_fini_vm;
#[path = "../mir_stage1_cli_emit_program_min.rs"]
pub mod mir_stage1_cli_emit_program_min;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_stage1_cli_stage1_main_verify.rs"]
pub mod mir_stage1_cli_stage1_main_verify;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_stage1_staticcompiler_receiver.rs"]
pub mod mir_stage1_staticcompiler_receiver;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_stage1_using_resolver_verify.rs"]
pub mod mir_stage1_using_resolver_verify;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_stageb_like_args_length.rs"]
pub mod mir_stageb_like_args_length;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_stageb_loop_break_continue.rs"]
pub mod mir_stageb_loop_break_continue;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_stageb_string_utils_skip_ws.rs"]
pub mod mir_stageb_string_utils_skip_ws;
#[cfg(feature = "legacy-tests")]
#[path = "../mir_static_box_naming.rs"]
pub mod mir_static_box_naming;
#[path = "../mir_value_kind.rs"]
pub mod mir_value_kind;
