use super::ASTNode;

impl ASTNode {
    /// AST nodeの種類を文字列で取得 (デバッグ用)
    pub fn node_type(&self) -> &'static str {
        match self {
            ASTNode::Program { .. } => "Program",
            ASTNode::Assignment { .. } => "Assignment",
            ASTNode::Print { .. } => "Print",
            ASTNode::If { .. } => "If",
            ASTNode::Loop { .. } => "Loop",
            ASTNode::LoopRange { .. } => "LoopRange",
            ASTNode::Return { .. } => "Return",
            ASTNode::Break { .. } => "Break",
            ASTNode::Continue { .. } => "Continue",
            ASTNode::UsingStatement { .. } => "UsingStatement",
            ASTNode::ImportStatement { .. } => "ImportStatement",
            ASTNode::BoxDeclaration {
                is_record: true, ..
            } => "RecordDeclaration",
            ASTNode::BoxDeclaration { .. } => "BoxDeclaration",
            ASTNode::EnumDeclaration { .. } => "EnumDeclaration",
            ASTNode::BrandDeclaration { .. } => "BrandDeclaration",
            ASTNode::TypeAliasDeclaration { .. } => "TypeAliasDeclaration",
            ASTNode::FunctionDeclaration { .. } => "FunctionDeclaration",
            ASTNode::GlobalVar { .. } => "GlobalVar",
            ASTNode::StaticConstTable { .. } => "StaticConstTable",
            ASTNode::Literal { .. } => "Literal",
            ASTNode::Variable { .. } => "Variable",
            ASTNode::UnaryOp { .. } => "UnaryOp",
            ASTNode::BinaryOp { .. } => "BinaryOp",
            ASTNode::CheckExpr { .. } => "CheckExpr",
            ASTNode::MethodCall { .. } => "MethodCall",
            ASTNode::FieldAccess { .. } => "FieldAccess",
            ASTNode::Index { .. } => "Index",
            ASTNode::New { .. } => "New",
            ASTNode::This { .. } => "This",
            ASTNode::Me { .. } => "Me",
            ASTNode::FromCall { .. } => "FromCall",
            ASTNode::ThisField { .. } => "ThisField",
            ASTNode::MeField { .. } => "MeField",
            ASTNode::Local { .. } => "Local",
            ASTNode::Outbox { .. } => "Outbox",
            ASTNode::FunctionCall { .. } => "FunctionCall",
            ASTNode::Call { .. } => "Call",
            ASTNode::Nowait { .. } => "Nowait",
            ASTNode::TaskScope { .. } => "TaskScope",
            ASTNode::Arrow { .. } => "Arrow",
            ASTNode::TryCatch { .. } => "TryCatch",
            ASTNode::Throw { .. } => "Throw",
            ASTNode::AwaitExpression { .. } => "AwaitExpression",
            ASTNode::QMarkPropagate { .. } => "QMarkPropagate",
            ASTNode::MatchExpr { .. } => "MatchExpr",
            ASTNode::EnumMatchExpr { .. } => "EnumMatchExpr",
            ASTNode::Lambda { .. } => "Lambda",
            ASTNode::ArrayLiteral { .. } => "ArrayLiteral",
            ASTNode::MapLiteral { .. } => "MapLiteral",
            ASTNode::RecordLiteral { .. } => "RecordLiteral",
            ASTNode::RecordUpdate { .. } => "RecordUpdate",
            ASTNode::BlockExpr { .. } => "BlockExpr",
            ASTNode::ScopeBox { .. } => "ScopeBox",
            ASTNode::GroupedAssignmentExpr { .. } => "GroupedAssignmentExpr",
        }
    }
}
