#!/usr/bin/env python3
"""Generate all MapStore RoutePolicyRow derived artifacts."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/write_set_mapstore_route_policy.hako"
EXPECTED = {
    "MapStoreI64": ("map_store_i64_set_surface", "I64", "Any"),
    "MapStoreAny": ("map_store_any_set_surface", "Any", "Any"),
}
GENERATED = {
    "rust": ROOT / "src/mir/generic_method_route_plan/generated/write_set_mapstore_route_policy.rs",
    "i64_policy": ROOT / "src/mir/generic_method_route_plan/generated/write_set_mapstore_i64_hako_policy.rs",
    "any_policy": ROOT / "src/mir/generic_method_route_plan/generated/write_set_mapstore_any_hako_policy.rs",
    "i64_caller": ROOT / "src/mir/generic_method_route_plan/generated/write_set_mapstore_i64_caller_orientation_contract.rs",
    "any_caller": ROOT / "src/mir/generic_method_route_plan/generated/write_set_mapstore_any_caller_orientation_contract.rs",
}


def read_rows(source: Path) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        marker = '"map_store_'
        start = line.find(marker)
        if start < 0:
            continue
        raw = line[start + 1 : line.rfind('"')]
        fields = raw.split("|")
        if len(fields) != 13:
            raise SystemExit(f"MapStore RoutePolicyRow has {len(fields)} fields, expected 13")
        rows.append(fields)
    if len(rows) != len(EXPECTED):
        raise SystemExit(f"MapStore RoutePolicyRow count drift: {len(rows)}")
    return rows


def validate(fields: list[str]) -> None:
    (
        row_id,
        route_kind,
        key_domain,
        stored_value_domain,
        result_shape,
        effect_class,
        mutation_class,
        publication_policy,
        surface,
        core_op,
        lowering_tier,
        value_demand,
        authority_kind,
    ) = fields
    expected = EXPECTED.get(route_kind)
    if expected is None or expected[1:] != (key_domain, stored_value_domain):
        raise SystemExit(f"{route_kind} key/value domain drift: {fields!r}")
    if row_id != expected[0]:
        raise SystemExit(f"{route_kind} policy row identity drift: {row_id}")
    expected_fields = {
        "result_shape": "None",
        "effect_class": "mutate",
        "mutation_class": "MutatesReceiverOrContainer",
        "publication_policy": "NonePublication",
        "core_op": "MapSet",
        "lowering_tier": "ColdFallback",
        "value_demand": "WriteAny",
        "authority_kind": "HakoPolicyRow",
    }
    actual = locals()
    for name, value in expected_fields.items():
        if actual[name] != value:
            raise SystemExit(f"{route_kind} {name} drift: {actual[name]!r}")
    if not surface.startswith("SetSurfacePolicy"):
        raise SystemExit(f"{route_kind} surface drift: {surface!r}")


def lit(value: str) -> str:
    return json.dumps(value)


def render(rows: list[list[str]]) -> str:
    for row in rows:
        validate(row)
    rendered_rows = []
    for row in rows:
        (
            row_id,
            route_kind,
            key_domain,
            stored_value_domain,
            result_shape,
            effect_class,
            mutation_class,
            publication_policy,
            surface,
            core_op,
            lowering_tier,
            value_demand,
            authority_kind,
        ) = row
        rendered_rows.append(
            "        MapStoreRoutePolicyRow {\n"
            f"            policy_row_id: {lit(row_id)},\n"
            f"            route_kind: GenericMethodRouteKind::{route_kind},\n"
            f"            key_domain: {lit(key_domain)},\n"
            f"            stored_value_domain: {lit(stored_value_domain)},\n"
            f"            result_shape: {lit(result_shape)},\n"
            f"            effect_class: {lit(effect_class)},\n"
            f"            mutation_class: {lit(mutation_class)},\n"
            f"            publication_policy: {lit(publication_policy)},\n"
            f"            surface: {lit(surface)},\n"
            f"            core_op: CoreMethodOp::{core_op},\n"
            f"            lowering_tier: CoreMethodLoweringTier::{lowering_tier},\n"
            f"            value_demand: GenericMethodValueDemand::{value_demand},\n"
            f"            authority_kind: {lit(authority_kind)},\n"
            "        },"
        )
    return """// @generated by tools/rust_lifecycle/generate_write_set_mapstore_route_policy.py
// source: lang/src/compiler/lib/write_set_mapstore_route_policy.hako

use crate::mir::core_method_op::{CoreMethodLoweringTier, CoreMethodOp};
use crate::mir::generic_method_route_facts::GenericMethodValueDemand;
use crate::mir::generic_method_route_plan::GenericMethodRouteKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct MapStoreRoutePolicyRow {
    pub(crate) policy_row_id: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) key_domain: &'static str,
    pub(crate) stored_value_domain: &'static str,
    pub(crate) result_shape: &'static str,
    pub(crate) effect_class: &'static str,
    pub(crate) mutation_class: &'static str,
    pub(crate) publication_policy: &'static str,
    pub(crate) surface: &'static str,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) authority_kind: &'static str,
}

pub(crate) const MAPSTORE_ROUTE_POLICY_ROWS: &[MapStoreRoutePolicyRow] = &[
""" + "\n".join(rendered_rows) + "\n];\n"


def row_by_route(rows: list[list[str]], route_kind: str) -> list[str]:
    for row in rows:
        if row[1] == route_kind:
            return row
    raise SystemExit(f"MapStore policy row not found: {route_kind}")


def render_classifier(row: list[str], route_kind: str, value_boundary: str,
                      any_boundary_policy: str = "") -> str:
    (
        row_id, _route_kind, _key_domain, _stored_value_domain, result_shape,
        effect_class, mutation_class, publication_policy, surface, core_op,
        lowering_tier, value_demand, _authority_kind,
    ) = row
    struct_name = f"Hako{route_kind}Policy"
    const_name = f"WRITE_SET_MAPSTORE_{'I64' if route_kind == 'MapStoreI64' else 'ANY'}_HAKO_POLICY"
    module_name = "i64" if route_kind == "MapStoreI64" else "any"
    extra_fields = "" if not any_boundary_policy else "    pub(crate) any_boundary_policy: &'static str,\n"
    extra_value = "" if not any_boundary_policy else f"        any_boundary_policy: {lit(any_boundary_policy)},\n"
    return f'''// @generated by tools/rust_lifecycle/generate_write_set_mapstore_route_policy.py
// source: lang/src/compiler/lib/write_set_mapstore_route_policy.hako
// projection: {module_name} classifier compatibility view

use crate::mir::core_method_op::{{CoreMethodLoweringTier, CoreMethodOp}};
use crate::mir::generic_method_route_facts::GenericMethodValueDemand;
use crate::mir::generic_method_route_plan::GenericMethodRouteKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct {struct_name} {{
    pub(crate) policy_row_id: &'static str,
    pub(crate) surface: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) result_class: &'static str,
    pub(crate) return_shape: &'static str,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) value_boundary: &'static str,
    pub(crate) publication_policy: &'static str,
    pub(crate) effect_class: &'static str,
    pub(crate) mutation_class: &'static str,
{extra_fields}    pub(crate) role: &'static str,
}}

pub(crate) const {const_name}: {struct_name} = {struct_name} {{
    policy_row_id: {lit(row_id)},
    surface: {lit(surface)},
    route_kind: GenericMethodRouteKind::{_route_kind},
    core_op: CoreMethodOp::{core_op},
    lowering_tier: CoreMethodLoweringTier::{lowering_tier},
    result_class: "NoneResult",
    return_shape: {lit(result_shape)},
    value_demand: GenericMethodValueDemand::{value_demand},
    value_boundary: {lit(value_boundary)},
    publication_policy: {lit(publication_policy)},
    effect_class: {lit(effect_class)},
    mutation_class: {lit(mutation_class)},
{extra_value}    role: "classifier_policy_mirror_only",
}};
'''


def render_caller(row: list[str], route_kind: str) -> str:
    row_id = row[0]
    upper = "I64" if route_kind == "MapStoreI64" else "Any"
    struct_name = f"HakoMapStore{upper}CallerOrientationContract"
    const_name = f"WRITE_SET_MAPSTORE_{upper.upper()}_CALLER_ORIENTATION_CONTRACT"
    return f'''// @generated by tools/rust_lifecycle/generate_write_set_mapstore_route_policy.py
// source: lang/src/compiler/lib/write_set_mapstore_route_policy.hako
// projection profile: MetadataOnlySingleSurfaceV1

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct {struct_name} {{
    pub(crate) policy_row_id: &'static str,
    pub(crate) orientation_kind: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) runtime_consumer: &'static str,
    pub(crate) backend_lowering_consumer: &'static str,
    pub(crate) mutation_consumer: &'static str,
    pub(crate) publication_consumer: &'static str,
    pub(crate) mismatch_policy: &'static str,
}}

#[allow(dead_code)]
pub(crate) const {const_name}: {struct_name} = {struct_name} {{
    policy_row_id: {lit(row_id)},
    orientation_kind: "CallerOrientationContractMetadataOnly",
    scope: "SingleSurface",
    runtime_consumer: "Forbidden",
    backend_lowering_consumer: "Forbidden",
    mutation_consumer: "Forbidden",
    publication_consumer: "Forbidden",
    mismatch_policy: "FailFast",
}};
'''


def render_all(rows: list[list[str]]) -> dict[Path, str]:
    outputs = {
        GENERATED["rust"]: render(rows),
        GENERATED["i64_policy"]: render_classifier(row_by_route(rows, "MapStoreI64"), "MapStoreI64", "ScalarI64"),
        GENERATED["any_policy"]: render_classifier(row_by_route(rows, "MapStoreAny"), "MapStoreAny", "Any", "DeclaredMetadataOnly"),
        GENERATED["i64_caller"]: render_caller(row_by_route(rows, "MapStoreI64"), "MapStoreI64"),
        GENERATED["any_caller"]: render_caller(row_by_route(rows, "MapStoreAny"), "MapStoreAny"),
    }
    formatted: dict[Path, str] = {}
    for path, content in outputs.items():
        result = subprocess.run(
            ["rustfmt", "--edition", "2021", "--emit", "stdout"],
            input=content,
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            raise SystemExit(f"rustfmt failed for {path.relative_to(ROOT)}: {result.stderr}")
        formatted[path] = result.stdout
    return formatted


def artifact_key(name: str) -> str:
    key = {
        "rust": "rust",
        "i64_policy": "i64_policy",
        "any_policy": "any_policy",
        "i64_caller": "i64_caller",
        "any_caller": "any_caller",
    }.get(name)
    if key is None:
        raise SystemExit(f"unknown MapStore artifact: {name}")
    return key


def check_outputs(outputs: dict[Path, str]) -> None:
    stale = [str(path.relative_to(ROOT)) for path, expected in outputs.items()
             if not path.exists() or path.read_text(encoding="utf-8") != expected]
    if stale:
        raise SystemExit("stale generated MapStore artifacts:\n" + "\n".join(stale))


def write_outputs(outputs: dict[Path, str]) -> None:
    for path, content in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(tmp_name, path)
        except Exception:
            Path(tmp_name).unlink(missing_ok=True)
            raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="Verify all generated artifacts.")
    mode.add_argument("--write", action="store_true", help="Write all generated artifacts atomically.")
    parser.add_argument("--artifact", choices=["rust", "i64_policy", "any_policy", "i64_caller", "any_caller"])
    args = parser.parse_args()
    outputs = render_all(read_rows(args.source))
    if args.check:
        check_outputs(outputs)
    elif args.write:
        write_outputs(outputs)
    elif args.artifact:
        print(outputs[GENERATED[artifact_key(args.artifact)]], end="")
    else:
        print(outputs[GENERATED["rust"]], end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
