#!/usr/bin/env python3
"""Generate the checked-in MapStoreI64 caller-orientation contract artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/write_set_mapstore_i64_caller_orientation_contract.hako"


def read_contract_row(source: Path) -> list[str]:
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find('"map_store_i64_')
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("MapStoreI64 caller contract row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 8:
            raise SystemExit(f"MapStoreI64 caller contract has {len(fields)} fields, expected 8")
        if fields[0] != "map_store_i64_set_surface":
            raise SystemExit(f"unexpected MapStoreI64 caller contract ID: {fields[0]!r}")
        return fields
    raise SystemExit("MapStoreI64 caller contract row not found")


def render(fields: list[str]) -> str:
    expected_tail = [
        "CallerOrientationContractMetadataOnly", "SingleSurface", "Forbidden",
        "Forbidden", "Forbidden", "Forbidden", "FailFast",
    ]
    if fields[1:] != expected_tail:
        raise SystemExit(f"unexpected MapStoreI64 caller contract row: {fields!r}")

    def lit(value: str) -> str:
        return json.dumps(value)

    return f'''// @generated by tools/rust_lifecycle/generate_write_set_mapstore_i64_caller_orientation_contract.py
// source: lang/src/compiler/lib/write_set_mapstore_i64_caller_orientation_contract.hako

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoMapStoreI64CallerOrientationContract {{
    pub(crate) policy_row_id: &'static str,
    pub(crate) orientation_kind: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) runtime_consumer: &'static str,
    pub(crate) backend_lowering_consumer: &'static str,
    pub(crate) mutation_consumer: &'static str,
    pub(crate) publication_consumer: &'static str,
    pub(crate) mismatch_policy: &'static str,
}}

#[allow(dead_code)]
pub(crate) const WRITE_SET_MAPSTORE_I64_CALLER_ORIENTATION_CONTRACT: HakoMapStoreI64CallerOrientationContract =
    HakoMapStoreI64CallerOrientationContract {{
        policy_row_id: {lit(fields[0])},
        orientation_kind: {lit(fields[1])},
        scope: {lit(fields[2])},
        runtime_consumer: {lit(fields[3])},
        backend_lowering_consumer: {lit(fields[4])},
        mutation_consumer: {lit(fields[5])},
        publication_consumer: {lit(fields[6])},
        mismatch_policy: {lit(fields[7])},
    }};
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_contract_row(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
