#!/usr/bin/env python3
"""Generate the checked-in MapLoadScalarI64 Hako shadow policy artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/map_load_scalar_i64_policy_classifier.hako"


def read_policy_row(source: Path) -> list[str]:
    prefix = '"map_load_scalar_i64_routes|'
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find(prefix)
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("MapLoad policy row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 13:
            raise SystemExit(f"MapLoad policy row has {len(fields)} fields, expected 13")
        return fields
    raise SystemExit("MapLoad policy row not found")


def render(fields: list[str]) -> str:
    (
        row_id,
        surface,
        route_kind,
        core_op,
        lowering_tier,
        result_class,
        return_shape,
        value_demand,
        publication_policy,
        effect_class,
        proof_family,
        allowed_proofs,
        role,
    ) = fields

    expected = {
        "row_id": "map_load_scalar_i64_routes",
        "surface": "MapLoadScalarI64Routes",
        "route_kind": "MapLoadScalarI64",
        "core_op": "MapGet",
        "lowering_tier": "WarmDirectAbi",
        "value_demand": "ScalarI64",
        "proof_family": "ScalarI64MapGetStoreFact",
    }
    actual = {
        "row_id": row_id,
        "surface": surface,
        "route_kind": route_kind,
        "core_op": core_op,
        "lowering_tier": lowering_tier,
        "value_demand": value_demand,
        "proof_family": proof_family,
    }
    if actual != expected:
        raise SystemExit(f"unexpected MapLoad policy identity: {actual!r}")
    proof_variants = allowed_proofs.split(",")
    if len(proof_variants) != 3:
        raise SystemExit("MapLoad policy must carry exactly three scalar-map proofs")

    def lit(value: str) -> str:
        return json.dumps(value)

    rendered_proofs = ",\n    ".join(f"GenericMethodRouteProof::{proof}" for proof in proof_variants)
    return f"""// @generated by tools/rust_lifecycle/generate_mapload_scalar_i64_hako_policy.py
// source: lang/src/compiler/lib/map_load_scalar_i64_policy_classifier.hako

use crate::mir::core_method_op::{{CoreMethodLoweringTier, CoreMethodOp}};
use crate::mir::generic_method_route_facts::{{
    GenericMethodPublicationPolicy, GenericMethodReturnShape, GenericMethodValueDemand,
}};
use crate::mir::generic_method_route_plan::{{
    GenericMethodRouteKind, GenericMethodRouteProof,
}};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoMapLoadScalarI64Policy {{
    pub(crate) surface: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) result_class: &'static str,
    pub(crate) return_shape: GenericMethodReturnShape,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) publication_policy: GenericMethodPublicationPolicy,
    pub(crate) effect_class: &'static str,
    pub(crate) proof_family: &'static str,
    pub(crate) allowed_proofs: &'static [GenericMethodRouteProof],
    pub(crate) role: &'static str,
}}

pub(crate) const MAPLOAD_SCALAR_I64_ALLOWED_PROOFS: &[GenericMethodRouteProof] = &[
    {rendered_proofs},
];

pub(crate) const MAPLOAD_SCALAR_I64_HAKO_POLICY: HakoMapLoadScalarI64Policy =
    HakoMapLoadScalarI64Policy {{
        surface: {lit(surface)},
        route_kind: GenericMethodRouteKind::{route_kind},
        core_op: CoreMethodOp::{core_op},
        lowering_tier: CoreMethodLoweringTier::{lowering_tier},
        result_class: {lit(result_class)},
        return_shape: GenericMethodReturnShape::{return_shape},
        value_demand: GenericMethodValueDemand::{value_demand},
        publication_policy: GenericMethodPublicationPolicy::{publication_policy},
        effect_class: {lit(effect_class)},
        proof_family: {lit(proof_family)},
        allowed_proofs: MAPLOAD_SCALAR_I64_ALLOWED_PROOFS,
        role: {lit(role)},
    }};
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_policy_row(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
