#!/usr/bin/env python3
"""Generate the checked-in Write Push Hako shadow policy artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/write_push_surface_policy_classifier.hako"


def read_policy_row(source: Path) -> list[str]:
    prefix = '"array_append_any_push_surface|'
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find(prefix)
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("Push policy row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 12:
            raise SystemExit(f"Push policy row has {len(fields)} fields, expected 12")
        return fields
    raise SystemExit("Push policy row not found")


def render(fields: list[str]) -> str:
    (
        row_id,
        surface,
        route_kind,
        core_op,
        lowering_tier,
        result_class,
        return_shape,
        value_demand,
        publication_policy,
        effect_class,
        mutation_class,
        role,
    ) = fields

    expected = {
        "row_id": "array_append_any_push_surface",
        "surface": "PushSurfacePolicy",
        "route_kind": "ArrayAppendAny",
        "core_op": "ArrayPush",
        "lowering_tier": "ColdFallback",
        "value_demand": "WriteAny",
    }
    actual = {
        "row_id": row_id,
        "surface": surface,
        "route_kind": route_kind,
        "core_op": core_op,
        "lowering_tier": lowering_tier,
        "value_demand": value_demand,
    }
    if actual != expected:
        raise SystemExit(f"unexpected Push policy identity: {actual!r}")

    def lit(value: str) -> str:
        return json.dumps(value)

    return f"""// @generated by tools/rust_lifecycle/generate_write_push_hako_policy.py
// source: lang/src/compiler/lib/write_push_surface_policy_classifier.hako

use crate::mir::core_method_op::{{CoreMethodLoweringTier, CoreMethodOp}};
use crate::mir::generic_method_route_facts::GenericMethodValueDemand;
use crate::mir::generic_method_route_plan::GenericMethodRouteKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoWritePushPolicy {{
    pub(crate) surface: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) result_class: &'static str,
    pub(crate) return_shape: &'static str,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) publication_policy: &'static str,
    pub(crate) effect_class: &'static str,
    pub(crate) mutation_class: &'static str,
    pub(crate) role: &'static str,
}}

pub(crate) const WRITE_PUSH_HAKO_POLICY: HakoWritePushPolicy = HakoWritePushPolicy {{
    surface: {lit(surface)},
    route_kind: GenericMethodRouteKind::{route_kind},
    core_op: CoreMethodOp::{core_op},
    lowering_tier: CoreMethodLoweringTier::{lowering_tier},
    result_class: {lit(result_class)},
    return_shape: {lit(return_shape)},
    value_demand: GenericMethodValueDemand::{value_demand},
    publication_policy: {lit(publication_policy)},
    effect_class: {lit(effect_class)},
    mutation_class: {lit(mutation_class)},
    role: {lit(role)},
}};
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_policy_row(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
