#!/usr/bin/env python3
"""Generate the checked-in MapStoreAny Hako shadow policy artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/write_set_mapstore_any_policy_classifier.hako"


def read_policy_row(source: Path) -> list[str]:
    prefix = '"map_store_any_set_surface|'
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find(prefix)
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("MapStoreAny policy row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 14:
            raise SystemExit(f"MapStoreAny policy row has {len(fields)} fields, expected 14")
        return fields
    raise SystemExit("MapStoreAny policy row not found")


def render(fields: list[str]) -> str:
    (
        row_id,
        surface,
        route_kind,
        core_op,
        lowering_tier,
        result_class,
        return_shape,
        value_demand,
        value_boundary,
        publication_policy,
        effect_class,
        mutation_class,
        any_boundary_policy,
        role,
    ) = fields

    expected = {
        "row_id": "map_store_any_set_surface",
        "surface": "SetSurfacePolicy/MapStoreAny",
        "route_kind": "MapStoreAny",
        "core_op": "MapSet",
        "lowering_tier": "ColdFallback",
        "value_demand": "WriteAny",
        "value_boundary": "Any",
    }
    actual = {
        "row_id": row_id,
        "surface": surface,
        "route_kind": route_kind,
        "core_op": core_op,
        "lowering_tier": lowering_tier,
        "value_demand": value_demand,
        "value_boundary": value_boundary,
    }
    if actual != expected:
        raise SystemExit(f"unexpected MapStoreAny policy identity: {actual!r}")

    def lit(value: str) -> str:
        return json.dumps(value)

    return f"""// @generated by tools/rust_lifecycle/generate_write_set_mapstore_any_hako_policy.py
// source: lang/src/compiler/lib/write_set_mapstore_any_policy_classifier.hako

use crate::mir::core_method_op::{{CoreMethodLoweringTier, CoreMethodOp}};
use crate::mir::generic_method_route_facts::GenericMethodValueDemand;
use crate::mir::generic_method_route_plan::GenericMethodRouteKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoMapStoreAnyPolicy {{
    pub(crate) surface: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) result_class: &'static str,
    pub(crate) return_shape: &'static str,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) value_boundary: &'static str,
    pub(crate) publication_policy: &'static str,
    pub(crate) effect_class: &'static str,
    pub(crate) mutation_class: &'static str,
    pub(crate) any_boundary_policy: &'static str,
    pub(crate) role: &'static str,
}}

pub(crate) const WRITE_SET_MAPSTORE_ANY_HAKO_POLICY: HakoMapStoreAnyPolicy =
    HakoMapStoreAnyPolicy {{
        surface: {lit(surface)},
        route_kind: GenericMethodRouteKind::{route_kind},
        core_op: CoreMethodOp::{core_op},
        lowering_tier: CoreMethodLoweringTier::{lowering_tier},
        result_class: {lit(result_class)},
        return_shape: {lit(return_shape)},
        value_demand: GenericMethodValueDemand::{value_demand},
        value_boundary: {lit(value_boundary)},
        publication_policy: {lit(publication_policy)},
        effect_class: {lit(effect_class)},
        mutation_class: {lit(mutation_class)},
        any_boundary_policy: {lit(any_boundary_policy)},
        role: {lit(role)},
    }};
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_policy_row(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
