#!/usr/bin/env python3
"""Generate the checked-in CollectionScalarI64 Hako shadow policy artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/collection_len_scalar_i64_policy_classifier.hako"


def read_policy_rows(source: Path) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find('"collection_')
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("Collection policy row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 13:
            raise SystemExit(f"Collection policy row has {len(fields)} fields, expected 13")
        rows.append(fields)
    if len(rows) != 4:
        raise SystemExit(f"expected 4 Collection policy rows, found {len(rows)}")
    return rows


def render(rows: list[list[str]]) -> str:
    expected = [
        ("collection_map_entry_count_scalar_i64_routes", "MapEntryCount", "MapLen", "MapBox"),
        ("collection_array_slot_len_scalar_i64_routes", "ArraySlotLen", "ArrayLen", "ArrayBox"),
        ("collection_string_len_scalar_i64_routes", "StringLen", "StringLen", "StringBox"),
        ("collection_any_length_scalar_i64_routes", "AnyLength", "AnyLen", "Box"),
    ]
    for fields, identity in zip(rows, expected):
        row_id, surface, route_kind, core_op, receiver_domain, *_ = fields
        actual = (row_id, route_kind, core_op, receiver_domain)
        if surface != "CollectionScalarI64Routes" or actual != identity:
            raise SystemExit(f"unexpected Collection policy identity: {actual!r}")

    def lit(value: str) -> str:
        return json.dumps(value)

    rendered_rows = []
    for fields in rows:
        (
            row_id,
            surface,
            route_kind,
            core_op,
            receiver_domain,
            lowering_tier,
            result_class,
            return_shape,
            value_demand,
            publication_policy,
            effect_class,
            proof,
            role,
        ) = fields
        rendered_rows.append(
            f"""    HakoCollectionLenScalarI64Policy {{
        policy_row_id: {lit(row_id)},
        surface: {lit(surface)},
        route_kind: GenericMethodRouteKind::{route_kind},
        core_op: CoreMethodOp::{core_op},
        receiver_domain: {lit(receiver_domain)},
        lowering_tier: CoreMethodLoweringTier::{lowering_tier},
        result_class: {lit(result_class)},
        return_shape: GenericMethodReturnShape::{return_shape},
        value_demand: GenericMethodValueDemand::{value_demand},
        publication_policy: GenericMethodPublicationPolicy::{publication_policy},
        effect_class: {lit(effect_class)},
        proof_or_policy_source: GenericMethodRouteProof::{proof},
        role: {lit(role)},
    }}"""
        )
    rendered_table = ",\n".join(rendered_rows)
    return f"""// @generated by tools/rust_lifecycle/generate_collection_len_scalar_i64_hako_policy.py
// source: lang/src/compiler/lib/collection_len_scalar_i64_policy_classifier.hako

use crate::mir::core_method_op::{{CoreMethodLoweringTier, CoreMethodOp}};
use crate::mir::generic_method_route_facts::{{
    GenericMethodPublicationPolicy, GenericMethodReturnShape, GenericMethodValueDemand,
}};
use crate::mir::generic_method_route_plan::{{
    GenericMethodRouteKind, GenericMethodRouteProof,
}};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoCollectionLenScalarI64Policy {{
    pub(crate) policy_row_id: &'static str,
    pub(crate) surface: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) receiver_domain: &'static str,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) result_class: &'static str,
    pub(crate) return_shape: GenericMethodReturnShape,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) publication_policy: GenericMethodPublicationPolicy,
    pub(crate) effect_class: &'static str,
    pub(crate) proof_or_policy_source: GenericMethodRouteProof,
    pub(crate) role: &'static str,
}}

pub(crate) const COLLECTION_LEN_SCALAR_I64_HAKO_POLICIES: &[HakoCollectionLenScalarI64Policy] = &[
{rendered_table},
];
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_policy_rows(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
