#!/usr/bin/env python3
"""Generate the checked-in MapLoad caller-orientation contract artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/map_load_scalar_i64_caller_orientation_contract.hako"


def read_contract_row(source: Path) -> list[str]:
    prefix = '"map_load_scalar_i64_routes|'
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find(prefix)
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("MapLoad caller-orientation contract row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 8:
            raise SystemExit(
                f"MapLoad caller-orientation contract has {len(fields)} fields, expected 8"
            )
        return fields
    raise SystemExit("MapLoad caller-orientation contract row not found")


def render(fields: list[str]) -> str:
    (
        policy_row_id,
        orientation_kind,
        scope,
        runtime_consumer,
        backend_lowering_consumer,
        mutation_consumer,
        publication_consumer,
        mismatch_policy,
    ) = fields
    expected = {
        "policy_row_id": "map_load_scalar_i64_routes",
        "orientation_kind": "CallerOrientationContractMetadataOnly",
        "scope": "SingleSurface",
        "runtime_consumer": "Forbidden",
        "backend_lowering_consumer": "Forbidden",
        "mutation_consumer": "Forbidden",
        "publication_consumer": "Forbidden",
        "mismatch_policy": "FailFast",
    }
    actual = {
        "policy_row_id": policy_row_id,
        "orientation_kind": orientation_kind,
        "scope": scope,
        "runtime_consumer": runtime_consumer,
        "backend_lowering_consumer": backend_lowering_consumer,
        "mutation_consumer": mutation_consumer,
        "publication_consumer": publication_consumer,
        "mismatch_policy": mismatch_policy,
    }
    if actual != expected:
        raise SystemExit(f"unexpected MapLoad caller-orientation contract: {actual!r}")

    def lit(value: str) -> str:
        return json.dumps(value)

    return f'''// @generated by tools/rust_lifecycle/generate_mapload_scalar_i64_caller_orientation_contract.py
// source: lang/src/compiler/lib/map_load_scalar_i64_caller_orientation_contract.hako

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoMapLoadCallerOrientationContract {{
    pub(crate) policy_row_id: &'static str,
    pub(crate) orientation_kind: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) runtime_consumer: &'static str,
    pub(crate) backend_lowering_consumer: &'static str,
    pub(crate) mutation_consumer: &'static str,
    pub(crate) publication_consumer: &'static str,
    pub(crate) mismatch_policy: &'static str,
}}

#[allow(dead_code)]
pub(crate) const MAPLOAD_SCALAR_I64_CALLER_ORIENTATION_CONTRACT: HakoMapLoadCallerOrientationContract =
    HakoMapLoadCallerOrientationContract {{
        policy_row_id: {lit(policy_row_id)},
        orientation_kind: {lit(orientation_kind)},
        scope: {lit(scope)},
        runtime_consumer: {lit(runtime_consumer)},
        backend_lowering_consumer: {lit(backend_lowering_consumer)},
        mutation_consumer: {lit(mutation_consumer)},
        publication_consumer: {lit(publication_consumer)},
        mismatch_policy: {lit(mismatch_policy)},
    }};
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_contract_row(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
