#!/usr/bin/env python3
"""Generate the checked-in String caller-orientation contract artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/string_scalar_i64_caller_orientation_contract.hako"
EXPECTED_IDS = [
    "string_indexof_scalar_i64_routes",
    "string_lastindexof_scalar_i64_routes",
    "string_contains_scalar_i64_routes",
]


def read_contract_rows(source: Path) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        start = line.find('"string_')
        if start < 0:
            continue
        rest = line[start + 1 :]
        end = rest.find('"')
        if end < 0:
            raise SystemExit("String caller-orientation contract row is unterminated")
        fields = rest[:end].split("|")
        if len(fields) != 8:
            raise SystemExit(f"String caller contract has {len(fields)} fields, expected 8")
        rows.append(fields)
    if [row[0] for row in rows] != EXPECTED_IDS:
        raise SystemExit(f"unexpected String caller contract IDs: {[row[0] for row in rows]!r}")
    return rows


def render(rows: list[list[str]]) -> str:
    expected_tail = [
        "CallerOrientationContractMetadataOnly",
        "SingleSurface",
        "Forbidden",
        "Forbidden",
        "Forbidden",
        "Forbidden",
        "FailFast",
    ]
    for row in rows:
        if row[1:] != expected_tail:
            raise SystemExit(f"unexpected String caller contract row: {row!r}")

    def lit(value: str) -> str:
        return json.dumps(value)

    rendered = ",\n".join(
        f'''    HakoStringCallerOrientationContract {{
        policy_row_id: {lit(row[0])},
        orientation_kind: {lit(row[1])},
        scope: {lit(row[2])},
        runtime_consumer: {lit(row[3])},
        backend_lowering_consumer: {lit(row[4])},
        mutation_consumer: {lit(row[5])},
        publication_consumer: {lit(row[6])},
        mismatch_policy: {lit(row[7])},
    }}'''
        for row in rows
    )
    return f'''// @generated by tools/rust_lifecycle/generate_string_scalar_i64_caller_orientation_contract.py
// source: lang/src/compiler/lib/string_scalar_i64_caller_orientation_contract.hako

#[allow(dead_code)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct HakoStringCallerOrientationContract {{
    pub(crate) policy_row_id: &'static str,
    pub(crate) orientation_kind: &'static str,
    pub(crate) scope: &'static str,
    pub(crate) runtime_consumer: &'static str,
    pub(crate) backend_lowering_consumer: &'static str,
    pub(crate) mutation_consumer: &'static str,
    pub(crate) publication_consumer: &'static str,
    pub(crate) mismatch_policy: &'static str,
}}

#[allow(dead_code)]
pub(crate) const STRING_SCALAR_I64_CALLER_ORIENTATION_CONTRACTS: &[HakoStringCallerOrientationContract] = &[
{rendered},
];
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_contract_rows(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
