#!/usr/bin/env python3
"""Generate the shared typed MapStore RoutePolicyRow artifact."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "lang/src/compiler/lib/write_set_mapstore_route_policy.hako"
EXPECTED = {
    "MapStoreI64": ("map_store_i64_set_surface", "I64", "Any"),
    "MapStoreAny": ("map_store_any_set_surface", "Any", "Any"),
}


def read_rows(source: Path) -> list[list[str]]:
    rows: list[list[str]] = []
    for line in source.read_text(encoding="utf-8").splitlines():
        marker = '"map_store_'
        start = line.find(marker)
        if start < 0:
            continue
        raw = line[start + 1 : line.rfind('"')]
        fields = raw.split("|")
        if len(fields) != 13:
            raise SystemExit(f"MapStore RoutePolicyRow has {len(fields)} fields, expected 13")
        rows.append(fields)
    if len(rows) != len(EXPECTED):
        raise SystemExit(f"MapStore RoutePolicyRow count drift: {len(rows)}")
    return rows


def validate(fields: list[str]) -> None:
    (
        row_id,
        route_kind,
        key_domain,
        stored_value_domain,
        result_shape,
        effect_class,
        mutation_class,
        publication_policy,
        surface,
        core_op,
        lowering_tier,
        value_demand,
        authority_kind,
    ) = fields
    expected = EXPECTED.get(route_kind)
    if expected is None or expected[1:] != (key_domain, stored_value_domain):
        raise SystemExit(f"{route_kind} key/value domain drift: {fields!r}")
    if row_id != expected[0]:
        raise SystemExit(f"{route_kind} policy row identity drift: {row_id}")
    expected_fields = {
        "result_shape": "None",
        "effect_class": "mutate",
        "mutation_class": "MutatesReceiverOrContainer",
        "publication_policy": "NonePublication",
        "core_op": "MapSet",
        "lowering_tier": "ColdFallback",
        "value_demand": "WriteAny",
        "authority_kind": "HakoPolicyRow",
    }
    actual = locals()
    for name, value in expected_fields.items():
        if actual[name] != value:
            raise SystemExit(f"{route_kind} {name} drift: {actual[name]!r}")
    if not surface.startswith("SetSurfacePolicy"):
        raise SystemExit(f"{route_kind} surface drift: {surface!r}")


def lit(value: str) -> str:
    return json.dumps(value)


def render(rows: list[list[str]]) -> str:
    for row in rows:
        validate(row)
    rendered_rows = []
    for row in rows:
        (
            row_id,
            route_kind,
            key_domain,
            stored_value_domain,
            result_shape,
            effect_class,
            mutation_class,
            publication_policy,
            surface,
            core_op,
            lowering_tier,
            value_demand,
            authority_kind,
        ) = row
        rendered_rows.append(
            "        MapStoreRoutePolicyRow {\n"
            f"            policy_row_id: {lit(row_id)},\n"
            f"            route_kind: GenericMethodRouteKind::{route_kind},\n"
            f"            key_domain: {lit(key_domain)},\n"
            f"            stored_value_domain: {lit(stored_value_domain)},\n"
            f"            result_shape: {lit(result_shape)},\n"
            f"            effect_class: {lit(effect_class)},\n"
            f"            mutation_class: {lit(mutation_class)},\n"
            f"            publication_policy: {lit(publication_policy)},\n"
            f"            surface: {lit(surface)},\n"
            f"            core_op: CoreMethodOp::{core_op},\n"
            f"            lowering_tier: CoreMethodLoweringTier::{lowering_tier},\n"
            f"            value_demand: GenericMethodValueDemand::{value_demand},\n"
            f"            authority_kind: {lit(authority_kind)},\n"
            "        },"
        )
    return """// @generated by tools/rust_lifecycle/generate_write_set_mapstore_route_policy.py
// source: lang/src/compiler/lib/write_set_mapstore_route_policy.hako

use crate::mir::core_method_op::{CoreMethodLoweringTier, CoreMethodOp};
use crate::mir::generic_method_route_facts::GenericMethodValueDemand;
use crate::mir::generic_method_route_plan::GenericMethodRouteKind;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) struct MapStoreRoutePolicyRow {
    pub(crate) policy_row_id: &'static str,
    pub(crate) route_kind: GenericMethodRouteKind,
    pub(crate) key_domain: &'static str,
    pub(crate) stored_value_domain: &'static str,
    pub(crate) result_shape: &'static str,
    pub(crate) effect_class: &'static str,
    pub(crate) mutation_class: &'static str,
    pub(crate) publication_policy: &'static str,
    pub(crate) surface: &'static str,
    pub(crate) core_op: CoreMethodOp,
    pub(crate) lowering_tier: CoreMethodLoweringTier,
    pub(crate) value_demand: GenericMethodValueDemand,
    pub(crate) authority_kind: &'static str,
}

pub(crate) const MAPSTORE_ROUTE_POLICY_ROWS: &[MapStoreRoutePolicyRow] = &[
""" + "\n".join(rendered_rows) + "\n];\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=SOURCE)
    args = parser.parse_args()
    print(render(read_rows(args.source)), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
