#!/usr/bin/env python3
"""Ordered-map crate-level bundle artifacts for MirBuilder easy tier."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from family_artifact_builders import build_family_artifact_hako_text
from mirbuilder_family_artifacts import (
    binding_context_spec,
    box_compilation_context_spec,
    variable_context_simple_map_spec,
    variable_context_snapshot_restore_spec,
)
from mirbuilder_core_context_artifacts import core_context_contract, core_context_spec
from mirbuilder_next_value_id_prepared_state_kernel_artifacts import (
    prepared_state_kernel_contract,
    prepared_state_kernel_spec,
)
from shared_family_generator import build_rust_derived_hako_manifest, rust_manifest_file_entry, sha256_text, stable_json
from shared_mirbuilder_emitter import render_main_operation
from shared_mirbuilder_emitter_common import indent
from verified_hako_family_ir import op


ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "lang/generated/rust_derived/hakorune_mir_builder"
BUNDLE_HAKO = OUT_DIR / "ordered_map_crate_bundle.hako"
BUNDLE_MANIFEST = OUT_DIR / "ordered_map_crate_bundle.artifact.json"


def _extract_balanced_block(hako_text: str, marker: str) -> str:
    start = hako_text.index(marker)
    depth = 0
    seen_open = False
    for offset, char in enumerate(hako_text[start:]):
        if char == "{":
            depth += 1
            seen_open = True
        elif char == "}":
            depth -= 1
            if seen_open and depth == 0:
                return hako_text[start : start + offset + 1].rstrip()
    raise ValueError(f"unterminated Hako block: {marker}")


def _extract_box_block(hako_text: str, box_name: str) -> str:
    return _extract_balanced_block(hako_text, f"box {box_name} {{")


def _extract_static_box_block(hako_text: str, static_box_name: str) -> str:
    return _extract_balanced_block(hako_text, f"static box {static_box_name} {{")


def _extract_static_box_methods(hako_text: str, static_box_name: str) -> list[str]:
    block = _extract_static_box_block(hako_text, static_box_name)
    lines = block.splitlines()
    if len(lines) < 2:
        raise ValueError(f"empty static box block: {static_box_name}")
    return lines[1:-1]


def _merge_static_box(static_box_name: str, *method_groups: list[str]) -> str:
    lines = [f"static box {static_box_name} {{"]
    for index, methods in enumerate(method_groups):
        if index:
            lines.append("")
        lines.extend(methods)
    lines.append("}")
    return "\n".join(lines)


def _extract_family_body_without_main(hako_text: str, *, box_name: str, static_box_name: str) -> str:
    return "\n\n".join(
        [
            _extract_box_block(hako_text, box_name),
            _extract_static_box_block(hako_text, static_box_name),
        ]
    )


def _bundle_header() -> list[str]:
    return [
        "// @generated by tools/rust_lifecycle/generate_mirbuilder_ordered_map_crate_bundle.py",
        f"// artifact-manifest: {BUNDLE_MANIFEST.relative_to(ROOT)}",
        "// family: hakorune_mir_builder::ordered_map_bundle",
        "// bundle-members: hakorune_mir_builder::binding_context, hakorune_mir_builder::context, hakorune_mir_builder::core_context.scalar_counters, hakorune_mir_builder::next_value_id_prepared_state_kernel, hakorune_mir_builder::variable_context.simple_map, hakorune_mir_builder::variable_context.snapshot_restore",
        "// manual-edit: forbidden",
        "",
        "using apps.lib.collections.ordered_map as OrderedMap",
        "",
        "using selfhost.shared.common.box_helpers as BoxHelpers",
        "",
    ]


def _bundle_main_operations() -> list[dict[str, Any]]:
    return [
        op("NewBox", target="binding_ctx", box="BindingContext").to_json(),
        op("StaticCall", target="binding_empty", callee="BindingContextApi.is_empty", args=["binding_ctx"]).to_json(),
        op("AssertEq", left="binding_empty", right=1, fail_message="ordered_map_bundle_binding_context_new_empty=fail", fail_code=1).to_json(),
        op("StaticCall", target="binding_inserted", callee="BindingContextApi.insert", args=["binding_ctx", {"literal": "x"}, 1]).to_json(),
        op("AssertEq", left="binding_inserted", right=1, fail_message="ordered_map_bundle_binding_context_insert=fail", fail_code=2).to_json(),
        op("StaticCall", target="binding_lookup", callee="BindingContextApi.lookup", args=["binding_ctx", {"literal": "x"}]).to_json(),
        op("AssertEq", left="binding_lookup", right=1, fail_message="ordered_map_bundle_binding_context_lookup=fail", fail_code=3).to_json(),
        op("NewBox", target="box_ctx", box="BoxCompilationContext").to_json(),
        op("StaticCall", target="box_empty", callee="BoxCompilationContextApi.is_empty", args=["box_ctx"]).to_json(),
        op("AssertEq", left="box_empty", right=1, fail_message="ordered_map_bundle_box_compilation_context_new_empty=fail", fail_code=4).to_json(),
        op("NewBox", target="core_ctx", box="CoreContext").to_json(),
        op("StaticCall", target="value0", callee="CoreContextApi.next_value", args=["core_ctx"]).to_json(),
        op("AssertEq", left="value0", right=0, fail_message="ordered_map_bundle_core_context_next_value_0=fail", fail_code=5).to_json(),
        op("StaticCall", target="peek_value1", callee="CoreContextApi.peek_next_value", args=["core_ctx"]).to_json(),
        op("AssertEq", left="peek_value1", right=1, fail_message="ordered_map_bundle_core_context_peek_next_value_1=fail", fail_code=6).to_json(),
        op("StaticCall", target="block0", callee="CoreContextApi.next_block", args=["core_ctx"]).to_json(),
        op("AssertEq", left="block0", right=0, fail_message="ordered_map_bundle_core_context_next_block_0=fail", fail_code=7).to_json(),
        op("StaticCall", target="peek_block1", callee="CoreContextApi.peek_next_block", args=["core_ctx"]).to_json(),
        op("AssertEq", left="peek_block1", right=1, fail_message="ordered_map_bundle_core_context_peek_next_block_1=fail", fail_code=8).to_json(),
        op("StaticCall", target="binding0", callee="CoreContextApi.next_binding", args=["core_ctx"]).to_json(),
        op("AssertEq", left="binding0", right=0, fail_message="ordered_map_bundle_core_context_next_binding_0=fail", fail_code=9).to_json(),
        op("StaticCall", target="binding1", callee="CoreContextApi.next_binding", args=["core_ctx"]).to_json(),
        op("AssertEq", left="binding1", right=1, fail_message="ordered_map_bundle_core_context_next_binding_1=fail", fail_code=10).to_json(),
        op("StaticCall", target="temp0", callee="CoreContextApi.next_temp_slot", args=["core_ctx"]).to_json(),
        op("AssertEq", left="temp0", right=0, fail_message="ordered_map_bundle_core_context_next_temp_slot_0=fail", fail_code=11).to_json(),
        op("StaticCall", target="debug0", callee="CoreContextApi.next_debug_join", args=["core_ctx"]).to_json(),
        op("AssertEq", left="debug0", right=0, fail_message="ordered_map_bundle_core_context_next_debug_join_0=fail", fail_code=12).to_json(),
        op("NewBox", target="alloc_function_present", box="FunctionValueIdCounterState").to_json(),
        op("SetField", target="alloc_function_present", field="next_value_id", value=1).to_json(),
        op("NewBox", target="alloc_reserved_present", box="ReservedValueIdMembershipView").to_json(),
        op("StaticCall", callee="ReservedValueIdMembershipViewApi.add", args=["alloc_reserved_present", 2]).to_json(),
        op("StaticCall", target="alloc_present0", callee="MirBuilderAllocationPolicyApi.next_value_id", args=[1, "alloc_function_present", "core_ctx", "alloc_reserved_present"]).to_json(),
        op("AssertEq", left="alloc_present0", right=1, fail_message="ordered_map_bundle_next_value_id_present0=fail", fail_code=13).to_json(),
        op("StaticCall", target="alloc_present1", callee="MirBuilderAllocationPolicyApi.next_value_id", args=[1, "alloc_function_present", "core_ctx", "alloc_reserved_present"]).to_json(),
        op("AssertEq", left="alloc_present1", right=3, fail_message="ordered_map_bundle_next_value_id_present1=fail", fail_code=14).to_json(),
        op("AssertEq", left="alloc_function_present.next_value_id", right=4, fail_message="ordered_map_bundle_next_value_id_present_counter=fail", fail_code=15).to_json(),
        op("AssertEq", left="core_ctx.value_next_id", right=1, fail_message="ordered_map_bundle_next_value_id_present_core_unchanged=fail", fail_code=16).to_json(),
        op("NewBox", target="alloc_function_absent", box="FunctionValueIdCounterState").to_json(),
        op("SetField", target="alloc_function_absent", field="next_value_id", value=100).to_json(),
        op("NewBox", target="alloc_core_absent", box="CoreContext").to_json(),
        op("NewBox", target="alloc_reserved_absent", box="ReservedValueIdMembershipView").to_json(),
        op("StaticCall", callee="ReservedValueIdMembershipViewApi.add", args=["alloc_reserved_absent", 1]).to_json(),
        op("StaticCall", target="alloc_absent0", callee="MirBuilderAllocationPolicyApi.next_value_id", args=[0, "alloc_function_absent", "alloc_core_absent", "alloc_reserved_absent"]).to_json(),
        op("AssertEq", left="alloc_absent0", right=0, fail_message="ordered_map_bundle_next_value_id_absent0=fail", fail_code=17).to_json(),
        op("StaticCall", target="alloc_absent1", callee="MirBuilderAllocationPolicyApi.next_value_id", args=[0, "alloc_function_absent", "alloc_core_absent", "alloc_reserved_absent"]).to_json(),
        op("AssertEq", left="alloc_absent1", right=2, fail_message="ordered_map_bundle_next_value_id_absent1=fail", fail_code=18).to_json(),
        op("AssertEq", left="alloc_function_absent.next_value_id", right=100, fail_message="ordered_map_bundle_next_value_id_absent_function_unchanged=fail", fail_code=19).to_json(),
        op("AssertEq", left="alloc_core_absent.value_next_id", right=3, fail_message="ordered_map_bundle_next_value_id_absent_core_counter=fail", fail_code=20).to_json(),
        op("NewBox", target="variable_ctx", box="VariableContext").to_json(),
        op("StaticCall", target="variable_empty", callee="VariableContextApi.is_empty", args=["variable_ctx"]).to_json(),
        op("AssertEq", left="variable_empty", right=1, fail_message="ordered_map_bundle_variable_context_new_empty=fail", fail_code=21).to_json(),
        op("StaticCall", target="variable_inserted", callee="VariableContextApi.insert", args=["variable_ctx", {"literal": "y"}, 42]).to_json(),
        op("AssertEq", left="variable_inserted", right=1, fail_message="ordered_map_bundle_variable_context_insert=fail", fail_code=22).to_json(),
        op("StaticCall", target="variable_lookup", callee="VariableContextApi.lookup", args=["variable_ctx", {"literal": "y"}]).to_json(),
        op("AssertEq", left="variable_lookup", right=42, fail_message="ordered_map_bundle_variable_context_lookup=fail", fail_code=23).to_json(),
        op("StaticCall", target="snapshot", callee="VariableContextApi.snapshot", args=["variable_ctx"]).to_json(),
        op("MethodCall", callee="snapshot_set", receiver="snapshot", method="set", args=[{"literal": "y"}, 7]).to_json(),
        op("MethodCall", target="snapshot_lookup", receiver="snapshot", method="get", args=[{"literal": "y"}]).to_json(),
        op("AssertEq", left="snapshot_lookup", right=7, fail_message="ordered_map_bundle_variable_context_snapshot_get=fail", fail_code=24).to_json(),
        op("StaticCall", target="post_snapshot_mutation_lookup", callee="VariableContextApi.lookup", args=["variable_ctx", {"literal": "y"}]).to_json(),
        op("AssertEq", left="post_snapshot_mutation_lookup", right=42, fail_message="ordered_map_bundle_variable_context_snapshot_alias=fail", fail_code=25).to_json(),
        op("StaticCall", callee="VariableContextApi.restore", args=["variable_ctx", "snapshot"]).to_json(),
        op("StaticCall", target="lookup_after_restore", callee="VariableContextApi.lookup", args=["variable_ctx", {"literal": "y"}]).to_json(),
        op("AssertEq", left="lookup_after_restore", right=7, fail_message="ordered_map_bundle_variable_context_restore=fail", fail_code=26).to_json(),
        op("Print", text="ordered_map_crate_bundle=ok").to_json(),
        op("ReturnI64", return_value=0).to_json(),
    ]


def build_ordered_map_crate_bundle_hako_text() -> str:
    binding_spec = binding_context_spec()
    box_spec = box_compilation_context_spec()
    core_spec = core_context_spec()
    allocation_spec = prepared_state_kernel_spec()
    variable_spec = variable_context_simple_map_spec()
    snapshot_spec = variable_context_snapshot_restore_spec()
    binding_hako = build_family_artifact_hako_text(binding_spec)
    box_hako = build_family_artifact_hako_text(box_spec)
    core_hako = build_family_artifact_hako_text(core_spec)
    allocation_hako = build_family_artifact_hako_text(allocation_spec)
    variable_hako = build_family_artifact_hako_text(variable_spec)
    snapshot_hako = build_family_artifact_hako_text(snapshot_spec)

    binding_body = _extract_family_body_without_main(binding_hako, box_name=binding_spec.box.name, static_box_name=binding_spec.api_name)
    box_body = _extract_family_body_without_main(box_hako, box_name=box_spec.box.name, static_box_name=box_spec.api_name)
    core_body = _extract_family_body_without_main(core_hako, box_name=core_spec.box.name, static_box_name=core_spec.api_name)
    allocation_blocks = [
        _extract_box_block(allocation_hako, "FunctionValueIdCounterState"),
        _extract_box_block(allocation_hako, "ReservedValueIdMembershipView"),
        _extract_static_box_block(allocation_hako, "FunctionValueIdCounterStateApi"),
        _extract_static_box_block(allocation_hako, "ReservedValueIdMembershipViewApi"),
        _extract_static_box_block(allocation_hako, "MirBuilderAllocationPolicyApi"),
    ]
    variable_box = _extract_box_block(variable_hako, variable_spec.box.name)
    variable_api = _merge_static_box(
        variable_spec.api_name,
        _extract_static_box_methods(variable_hako, variable_spec.api_name),
        _extract_static_box_methods(snapshot_hako, snapshot_spec.api_name),
    )

    lines = _bundle_header()
    lines.extend(binding_body.splitlines())
    lines.append("")
    lines.extend(box_body.splitlines())
    lines.append("")
    lines.extend(core_body.splitlines())
    lines.append("")
    lines.extend("\n\n".join(allocation_blocks).splitlines())
    lines.append("")
    lines.extend(variable_box.splitlines())
    lines.append("")
    lines.extend(variable_api.splitlines())
    lines.append("")
    lines.append("static box Main {")
    lines.append("    main() {")
    lines.extend(indent([line for operation in _bundle_main_operations() for line in render_main_operation(operation)], 8))
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build_ordered_map_crate_bundle_manifest_text(hako_text: str) -> str:
    binding_spec = binding_context_spec()
    box_spec = box_compilation_context_spec()
    core_spec = core_context_spec()
    core_contract = core_context_contract()
    allocation_spec = prepared_state_kernel_spec()
    allocation_contract = prepared_state_kernel_contract()
    variable_spec = variable_context_simple_map_spec()
    snapshot_spec = variable_context_snapshot_restore_spec()
    bundle_members = [
        {
            "name": "binding_context",
            "family_id": binding_spec.family_id,
            "artifact_manifest": binding_spec.artifact_manifest,
            "hako_path": str(binding_spec.hako_path.relative_to(ROOT)),
        },
        {
            "name": "box_compilation_context",
            "family_id": box_spec.family_id,
            "artifact_manifest": box_spec.artifact_manifest,
            "hako_path": str(box_spec.hako_path.relative_to(ROOT)),
        },
        {
            "name": "core_context",
            "family_id": core_spec.family_id,
            "artifact_manifest": core_spec.artifact_manifest,
            "hako_path": str(core_spec.hako_path.relative_to(ROOT)),
            "contract": {
                "kind": "VerifiedFamilyArtifactContractV1",
                "family_id": core_contract.family_id,
                "manifest_path": core_contract.artifact.manifest_path,
                "schema_version": core_contract.artifact.schema_version,
            },
        },
        {
            "name": "mirbuilder_next_value_id_prepared_state_kernel",
            "family_id": allocation_spec.family_id,
            "artifact_manifest": allocation_spec.artifact_manifest,
            "hako_path": str(allocation_spec.hako_path.relative_to(ROOT)),
            "contract": {
                "kind": "VerifiedFamilyArtifactContractV1",
                "family_id": allocation_contract.family_id,
                "manifest_path": allocation_contract.artifact.manifest_path,
                "schema_version": allocation_contract.artifact.schema_version,
            },
        },
        {
            "name": "variable_context_simple_map",
            "family_id": variable_spec.family_id,
            "artifact_manifest": variable_spec.artifact_manifest,
            "hako_path": str(variable_spec.hako_path.relative_to(ROOT)),
        },
        {
            "name": "variable_context_snapshot_restore",
            "family_id": snapshot_spec.family_id,
            "artifact_manifest": snapshot_spec.artifact_manifest,
            "hako_path": str(snapshot_spec.hako_path.relative_to(ROOT)),
        },
    ]
    manifest = build_rust_derived_hako_manifest(
        family_id="hakorune_mir_builder::ordered_map_bundle",
        state="DerivedShadow",
        source_rust_files=[
            rust_manifest_file_entry(path=binding_spec.source_rust_file, root=ROOT),
            rust_manifest_file_entry(path=box_spec.source_rust_file, root=ROOT),
            rust_manifest_file_entry(path=core_spec.source_rust_file, root=ROOT),
            rust_manifest_file_entry(path=allocation_spec.source_rust_file, root=ROOT),
            rust_manifest_file_entry(path=variable_spec.source_rust_file, root=ROOT),
        ],
        generator_tool="tools/rust_lifecycle/generate_mirbuilder_ordered_map_crate_bundle.py",
        generator_version="mirbuilder-easy-v0-ordered-map-bundle-v4",
        hako_path=str(BUNDLE_HAKO.relative_to(ROOT)),
        hako_sha256=sha256_text(hako_text),
        claims={
            "generated_hako_manual_edit": 0,
            "mainline_selected": 0,
            "rust_bootstrap_retained": 1,
            "backend_behavior_changed": 0,
            "source_selfhost_claim": 0,
        },
        pilot_scope="MirBuilder_easy_v0_ordered_map_bundle",
        inputs={
            "bundle_kind": "mirbuilder_easy_v0_ordered_map_bundle",
            "bundle_members": bundle_members,
        },
        extra_fields={
            "bundle_kind": "mirbuilder_easy_v0_ordered_map_bundle",
            "bundle_contract_model": "membership_only_v1",
            "bundle_members": [member["name"] for member in bundle_members],
            "bundle_member_contracts": [
                {
                    "member": member["name"],
                    "family_id": member["family_id"],
                    "contract": member.get("contract"),
                    "artifact_manifest": member["artifact_manifest"],
                }
                for member in bundle_members
            ],
            "exercised_capabilities": [
                "BindingContext.insert_lookup",
                "BoxCompilationContext.new_is_empty",
                "CoreContext.scalar_counters_and_id_generators",
                "MirBuilderAllocationPolicy.prepared_state_next_value_id",
                "VariableContext.simple_map.insert_lookup",
                "VariableContext.snapshot_owned_projection_set_get",
                "VariableContext.snapshot_restore",
            ],
            "deferred_capabilities": [],
        },
    )
    return stable_json(manifest)


def run_ordered_map_crate_bundle_generator(*, check: bool) -> None:
    hako_text = build_ordered_map_crate_bundle_hako_text()
    manifest_text = build_ordered_map_crate_bundle_manifest_text(hako_text)
    outputs = [
        (BUNDLE_HAKO, hako_text),
        (BUNDLE_MANIFEST, manifest_text),
    ]
    if check:
        for path, text in outputs:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f"generated files differ: {path.relative_to(ROOT)}")
        print("ordered_map_crate_bundle_generated_artifact=unchanged")
        return
    BUNDLE_HAKO.parent.mkdir(parents=True, exist_ok=True)
    for path, text in outputs:
        path.write_text(text)
    print("updated=lang/generated/rust_derived/hakorune_mir_builder/ordered_map_crate_bundle.hako,lang/generated/rust_derived/hakorune_mir_builder/ordered_map_crate_bundle.artifact.json")
