#!/usr/bin/env python3
"""Ordered-map crate-level bundle artifacts for MirBuilder easy tier."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from family_artifact_builders import build_family_artifact_hako_text
from mirbuilder_family_artifacts import binding_context_spec, variable_context_simple_map_spec
from shared_family_generator import build_rust_derived_hako_manifest, rust_manifest_file_entry, sha256_text, stable_json
from shared_mirbuilder_emitter import _indent, _render_main_operation
from verified_hako_family_ir import op


ROOT = Path(__file__).resolve().parents[2]
OUT_DIR = ROOT / "lang/generated/rust_derived/hakorune_mir_builder"
BUNDLE_HAKO = OUT_DIR / "ordered_map_crate_bundle.hako"
BUNDLE_MANIFEST = OUT_DIR / "ordered_map_crate_bundle.artifact.json"


def _extract_member_body(hako_text: str, *, box_name: str) -> str:
    start = hako_text.index(f"box {box_name} {{")
    main = hako_text.index("static box Main {")
    return hako_text[start:main].rstrip()


def _bundle_header() -> list[str]:
    return [
        "// @generated by tools/rust_lifecycle/generate_mirbuilder_ordered_map_crate_bundle.py",
        f"// artifact-manifest: {BUNDLE_MANIFEST.relative_to(ROOT)}",
        "// family: hakorune_mir_builder::ordered_map_bundle",
        "// bundle-members: hakorune_mir_builder::binding_context, hakorune_mir_builder::variable_context",
        "// manual-edit: forbidden",
        "",
        "using apps.lib.collections.ordered_map as OrderedMap",
        "",
        "using selfhost.shared.common.box_helpers as BoxHelpers",
        "",
    ]


def _bundle_main_operations() -> list[dict[str, Any]]:
    return [
        op("NewBox", target="binding_ctx", box="BindingContext").to_json(),
        op("StaticCall", target="binding_empty", callee="BindingContextApi.is_empty", args=["binding_ctx"]).to_json(),
        op("AssertEq", left="binding_empty", right=1, fail_message="ordered_map_bundle_binding_context_new_empty=fail", fail_code=1).to_json(),
        op("StaticCall", target="binding_inserted", callee="BindingContextApi.insert", args=["binding_ctx", '"x"', 1]).to_json(),
        op("AssertEq", left="binding_inserted", right=1, fail_message="ordered_map_bundle_binding_context_insert=fail", fail_code=2).to_json(),
        op("StaticCall", target="binding_lookup", callee="BindingContextApi.lookup", args=["binding_ctx", '"x"']).to_json(),
        op("AssertEq", left="binding_lookup", right=1, fail_message="ordered_map_bundle_binding_context_lookup=fail", fail_code=3).to_json(),
        op("NewBox", target="variable_ctx", box="VariableContext").to_json(),
        op("StaticCall", target="variable_empty", callee="VariableContextApi.is_empty", args=["variable_ctx"]).to_json(),
        op("AssertEq", left="variable_empty", right=1, fail_message="ordered_map_bundle_variable_context_new_empty=fail", fail_code=4).to_json(),
        op("StaticCall", target="variable_inserted", callee="VariableContextApi.insert", args=["variable_ctx", '"y"', 42]).to_json(),
        op("AssertEq", left="variable_inserted", right=1, fail_message="ordered_map_bundle_variable_context_insert=fail", fail_code=5).to_json(),
        op("StaticCall", target="variable_lookup", callee="VariableContextApi.lookup", args=["variable_ctx", '"y"']).to_json(),
        op("AssertEq", left="variable_lookup", right=42, fail_message="ordered_map_bundle_variable_context_lookup=fail", fail_code=6).to_json(),
        op("Print", text="ordered_map_crate_bundle=ok").to_json(),
        op("ReturnI64", return_value=0).to_json(),
    ]


def build_ordered_map_crate_bundle_hako_text() -> str:
    binding_spec = binding_context_spec()
    variable_spec = variable_context_simple_map_spec()
    binding_hako = build_family_artifact_hako_text(binding_spec)
    variable_hako = build_family_artifact_hako_text(variable_spec)

    binding_body = _extract_member_body(binding_hako, box_name=binding_spec.box.name)
    variable_body = _extract_member_body(variable_hako, box_name=variable_spec.box.name)

    lines = _bundle_header()
    lines.extend(binding_body.splitlines())
    lines.append("")
    lines.extend(variable_body.splitlines())
    lines.append("")
    lines.append("static box Main {")
    lines.append("    main() {")
    lines.extend(_indent([line for operation in _bundle_main_operations() for line in _render_main_operation(operation)], 8))
    lines.append("    }")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def build_ordered_map_crate_bundle_manifest_text(hako_text: str) -> str:
    binding_spec = binding_context_spec()
    variable_spec = variable_context_simple_map_spec()
    manifest = build_rust_derived_hako_manifest(
        family_id="hakorune_mir_builder::ordered_map_bundle",
        state="DerivedShadow",
        source_rust_files=[
            rust_manifest_file_entry(path=binding_spec.source_rust_file, root=ROOT),
            rust_manifest_file_entry(path=variable_spec.source_rust_file, root=ROOT),
        ],
        generator_tool="tools/rust_lifecycle/generate_mirbuilder_ordered_map_crate_bundle.py",
        generator_version="ordered-map-crate-bundle-v0",
        hako_path=str(BUNDLE_HAKO.relative_to(ROOT)),
        hako_sha256=sha256_text(hako_text),
        claims={
            "generated_hako_manual_edit": 0,
            "mainline_selected": 0,
            "rust_bootstrap_retained": 1,
            "backend_behavior_changed": 0,
            "source_selfhost_claim": 0,
        },
        pilot_scope="BindingContext_and_VariableContext_simple_map",
        inputs={
            "bundle_kind": "ordered_map_crate_bundle_v0",
            "bundle_members": [
                {
                    "name": "binding_context",
                    "family_id": binding_spec.family_id,
                    "artifact_manifest": binding_spec.artifact_manifest,
                    "hako_path": str(binding_spec.hako_path.relative_to(ROOT)),
                },
                {
                    "name": "variable_context_simple_map",
                    "family_id": variable_spec.family_id,
                    "artifact_manifest": variable_spec.artifact_manifest,
                    "hako_path": str(variable_spec.hako_path.relative_to(ROOT)),
                },
            ],
        },
        extra_fields={
            "bundle_kind": "ordered_map_crate_bundle_v0",
            "bundle_members": [
                "hakorune_mir_builder::binding_context",
                "hakorune_mir_builder::variable_context",
            ],
        },
    )
    return stable_json(manifest)


def run_ordered_map_crate_bundle_generator(*, check: bool) -> None:
    hako_text = build_ordered_map_crate_bundle_hako_text()
    manifest_text = build_ordered_map_crate_bundle_manifest_text(hako_text)
    outputs = [
        (BUNDLE_HAKO, hako_text),
        (BUNDLE_MANIFEST, manifest_text),
    ]
    if check:
        for path, text in outputs:
            if not path.exists() or path.read_text() != text:
                raise SystemExit(f"generated files differ: {path.relative_to(ROOT)}")
        print("ordered_map_crate_bundle_generated_artifact=unchanged")
        return
    BUNDLE_HAKO.parent.mkdir(parents=True, exist_ok=True)
    for path, text in outputs:
        path.write_text(text)
    print("updated=lang/generated/rust_derived/hakorune_mir_builder/ordered_map_crate_bundle.hako,lang/generated/rust_derived/hakorune_mir_builder/ordered_map_crate_bundle.artifact.json")
