use super::consts::*;

pub(crate) const STR_CONCAT2_ROUTE_TOTAL_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_TOTAL, 47);
pub(crate) const STR_CONCAT2_ROUTE_DISPATCH_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_DISPATCH_HIT, 48);
pub(crate) const STR_CONCAT2_ROUTE_FAST_STR_OWNED_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_FAST_STR_OWNED, 49);
pub(crate) const STR_CONCAT2_ROUTE_FAST_STR_RETURN_HANDLE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_FAST_STR_RETURN_HANDLE, 50);
pub(crate) const STR_CONCAT2_ROUTE_SPAN_FREEZE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_SPAN_FREEZE, 51);
pub(crate) const STR_CONCAT2_ROUTE_SPAN_RETURN_HANDLE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_SPAN_RETURN_HANDLE, 52);
pub(crate) const STR_CONCAT2_ROUTE_MATERIALIZE_FALLBACK_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_CONCAT2_ROUTE_MATERIALIZE_FALLBACK, 53);
pub(crate) const STR_CONCAT2_ROUTE_SUMMARY_FIELDS: [SnapshotCounterField; 7] = [
    STR_CONCAT2_ROUTE_TOTAL_FIELD,
    STR_CONCAT2_ROUTE_DISPATCH_HIT_FIELD,
    STR_CONCAT2_ROUTE_FAST_STR_OWNED_FIELD,
    STR_CONCAT2_ROUTE_FAST_STR_RETURN_HANDLE_FIELD,
    STR_CONCAT2_ROUTE_SPAN_FREEZE_FIELD,
    STR_CONCAT2_ROUTE_SPAN_RETURN_HANDLE_FIELD,
    STR_CONCAT2_ROUTE_MATERIALIZE_FALLBACK_FIELD,
];

pub(crate) const STR_LEN_ROUTE_TOTAL_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_TOTAL, 54);
pub(crate) const STR_LEN_ROUTE_DISPATCH_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_DISPATCH_HIT, 55);
pub(crate) const STR_LEN_ROUTE_FAST_STR_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_FAST_STR_HIT, 56);
pub(crate) const STR_LEN_ROUTE_FALLBACK_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_FALLBACK_HIT, 57);
pub(crate) const STR_LEN_ROUTE_MISS_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_MISS, 58);
pub(crate) const STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FAST_STR_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FAST_STR_HIT, 59);
pub(crate) const STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FALLBACK_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FALLBACK_HIT, 60);
pub(crate) const STR_LEN_ROUTE_SUMMARY_FIELDS: [SnapshotCounterField; 7] = [
    STR_LEN_ROUTE_TOTAL_FIELD,
    STR_LEN_ROUTE_DISPATCH_HIT_FIELD,
    STR_LEN_ROUTE_FAST_STR_HIT_FIELD,
    STR_LEN_ROUTE_FALLBACK_HIT_FIELD,
    STR_LEN_ROUTE_MISS_FIELD,
    STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FAST_STR_HIT_FIELD,
    STR_LEN_ROUTE_LATEST_FRESH_HANDLE_FALLBACK_HIT_FIELD,
];

pub(crate) const STR_SUBSTRING_ROUTE_TOTAL_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_TOTAL, 61);
pub(crate) const STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_HANDLE_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_HANDLE_HIT, 62);
pub(crate) const STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_REISSUE_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_REISSUE_HIT, 63);
pub(crate) const STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_MISS_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_MISS, 64);
pub(crate) const STR_SUBSTRING_ROUTE_FAST_CACHE_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_FAST_CACHE_HIT, 65);
pub(crate) const STR_SUBSTRING_ROUTE_DISPATCH_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_DISPATCH_HIT, 66);
pub(crate) const STR_SUBSTRING_ROUTE_SLOW_PLAN_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_SLOW_PLAN, 67);
pub(crate) const STR_SUBSTRING_ROUTE_SLOW_PLAN_RETURN_HANDLE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_SLOW_PLAN_RETURN_HANDLE, 68);
pub(crate) const STR_SUBSTRING_ROUTE_SLOW_PLAN_RETURN_EMPTY_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_SLOW_PLAN_RETURN_EMPTY, 69);
pub(crate) const STR_SUBSTRING_ROUTE_SLOW_PLAN_FREEZE_SPAN_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_SLOW_PLAN_FREEZE_SPAN, 70);
pub(crate) const STR_SUBSTRING_ROUTE_SLOW_PLAN_VIEW_SPAN_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(STR_SUBSTRING_ROUTE_SLOW_PLAN_VIEW_SPAN, 71);
pub(crate) const STR_SUBSTRING_ROUTE_SUMMARY_FIELDS: [SnapshotCounterField; 11] = [
    STR_SUBSTRING_ROUTE_TOTAL_FIELD,
    STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_HANDLE_HIT_FIELD,
    STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_REISSUE_HIT_FIELD,
    STR_SUBSTRING_ROUTE_VIEW_ARC_CACHE_MISS_FIELD,
    STR_SUBSTRING_ROUTE_FAST_CACHE_HIT_FIELD,
    STR_SUBSTRING_ROUTE_DISPATCH_HIT_FIELD,
    STR_SUBSTRING_ROUTE_SLOW_PLAN_FIELD,
    STR_SUBSTRING_ROUTE_SLOW_PLAN_RETURN_HANDLE_FIELD,
    STR_SUBSTRING_ROUTE_SLOW_PLAN_RETURN_EMPTY_FIELD,
    STR_SUBSTRING_ROUTE_SLOW_PLAN_FREEZE_SPAN_FIELD,
    STR_SUBSTRING_ROUTE_SLOW_PLAN_VIEW_SPAN_FIELD,
];

pub(crate) const PIECEWISE_SUBRANGE_TOTAL_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_TOTAL, 102);
pub(crate) const PIECEWISE_SUBRANGE_SINGLE_SESSION_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_SINGLE_SESSION_HIT, 103);
pub(crate) const PIECEWISE_SUBRANGE_FALLBACK_INSERT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_FALLBACK_INSERT, 104);
pub(crate) const PIECEWISE_SUBRANGE_EMPTY_RETURN_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_EMPTY_RETURN, 105);
pub(crate) const PIECEWISE_SUBRANGE_PREFIX_ONLY_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_PREFIX_ONLY, 106);
pub(crate) const PIECEWISE_SUBRANGE_MIDDLE_ONLY_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_MIDDLE_ONLY, 107);
pub(crate) const PIECEWISE_SUBRANGE_SUFFIX_ONLY_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_SUFFIX_ONLY, 108);
pub(crate) const PIECEWISE_SUBRANGE_PREFIX_MIDDLE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_PREFIX_MIDDLE, 109);
pub(crate) const PIECEWISE_SUBRANGE_MIDDLE_SUFFIX_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_MIDDLE_SUFFIX, 110);
pub(crate) const PIECEWISE_SUBRANGE_PREFIX_SUFFIX_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_PREFIX_SUFFIX, 111);
pub(crate) const PIECEWISE_SUBRANGE_ALL_THREE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(PIECEWISE_SUBRANGE_ALL_THREE, 112);
pub(crate) const PIECEWISE_SUBRANGE_SUMMARY_FIELDS: [SnapshotCounterField; 11] = [
    PIECEWISE_SUBRANGE_TOTAL_FIELD,
    PIECEWISE_SUBRANGE_SINGLE_SESSION_HIT_FIELD,
    PIECEWISE_SUBRANGE_FALLBACK_INSERT_FIELD,
    PIECEWISE_SUBRANGE_EMPTY_RETURN_FIELD,
    PIECEWISE_SUBRANGE_PREFIX_ONLY_FIELD,
    PIECEWISE_SUBRANGE_MIDDLE_ONLY_FIELD,
    PIECEWISE_SUBRANGE_SUFFIX_ONLY_FIELD,
    PIECEWISE_SUBRANGE_PREFIX_MIDDLE_FIELD,
    PIECEWISE_SUBRANGE_MIDDLE_SUFFIX_FIELD,
    PIECEWISE_SUBRANGE_PREFIX_SUFFIX_FIELD,
    PIECEWISE_SUBRANGE_ALL_THREE_FIELD,
];

pub(crate) const BORROWED_ALIAS_TO_STRING_BOX_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_TO_STRING_BOX, 72);
pub(crate) const BORROWED_ALIAS_EQUALS_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_EQUALS, 73);
pub(crate) const BORROWED_ALIAS_CLONE_BOX_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_CLONE_BOX, 74);
pub(crate) const BORROWED_ALIAS_TO_STRING_BOX_LATEST_FRESH_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_TO_STRING_BOX_LATEST_FRESH, 75);
pub(crate) const BORROWED_ALIAS_EQUALS_LATEST_FRESH_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_EQUALS_LATEST_FRESH, 76);
pub(crate) const BORROWED_ALIAS_CLONE_BOX_LATEST_FRESH_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_CLONE_BOX_LATEST_FRESH, 77);
pub(crate) const BORROWED_ALIAS_BORROWED_SOURCE_FAST_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_BORROWED_SOURCE_FAST, 78);
pub(crate) const BORROWED_ALIAS_AS_STR_FAST_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_AS_STR_FAST, 79);
pub(crate) const BORROWED_ALIAS_AS_STR_FAST_LIVE_SOURCE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_AS_STR_FAST_LIVE_SOURCE, 80);
pub(crate) const BORROWED_ALIAS_AS_STR_FAST_STALE_SOURCE_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_AS_STR_FAST_STALE_SOURCE, 81);
pub(crate) const BORROWED_ALIAS_ARRAY_LEN_BY_INDEX_LATEST_FRESH_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ARRAY_LEN_BY_INDEX_LATEST_FRESH, 82);
pub(crate) const BORROWED_ALIAS_ARRAY_INDEXOF_BY_INDEX_LATEST_FRESH_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ARRAY_INDEXOF_BY_INDEX_LATEST_FRESH, 83);
pub(crate) const BORROWED_ALIAS_ENCODE_EPOCH_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_EPOCH_HIT, 84);
pub(crate) const BORROWED_ALIAS_ENCODE_PTR_EQ_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_PTR_EQ_HIT, 85);
pub(crate) const BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC, 86);
pub(crate) const BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_ARRAY_GET_INDEX_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_ARRAY_GET_INDEX, 87);
pub(crate) const BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_MAP_RUNTIME_DATA_GET_ANY_FIELD:
    SnapshotCounterField = SnapshotCounterField::new(
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_MAP_RUNTIME_DATA_GET_ANY,
    88,
);
pub(crate) const BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT, 143);
pub(crate) const BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_ARRAY_GET_INDEX_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_ARRAY_GET_INDEX, 144);
pub(crate) const BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_MAP_RUNTIME_DATA_GET_ANY_FIELD:
    SnapshotCounterField = SnapshotCounterField::new(
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_MAP_RUNTIME_DATA_GET_ANY,
    145,
);
pub(crate) const BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_FIELD: SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT, 146);
pub(crate) const BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_ARRAY_GET_INDEX_FIELD:
    SnapshotCounterField =
    SnapshotCounterField::new(BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_ARRAY_GET_INDEX, 147);
pub(crate) const BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_MAP_RUNTIME_DATA_GET_ANY_FIELD:
    SnapshotCounterField = SnapshotCounterField::new(
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_MAP_RUNTIME_DATA_GET_ANY,
    148,
);

pub(crate) const BORROWED_ALIAS_ENCODE_SNAPSHOT_FIELDS: [SnapshotCounterField; 9] = [
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_FIELD,
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_ARRAY_GET_INDEX_FIELD,
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_MAP_RUNTIME_DATA_GET_ANY_FIELD,
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_FIELD,
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_ARRAY_GET_INDEX_FIELD,
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_MAP_RUNTIME_DATA_GET_ANY_FIELD,
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_FIELD,
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_ARRAY_GET_INDEX_FIELD,
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_MAP_RUNTIME_DATA_GET_ANY_FIELD,
];

pub(crate) const BORROWED_ALIAS_SUMMARY_FIELDS: [SnapshotCounterField; 23] = [
    BORROWED_ALIAS_TO_STRING_BOX_FIELD,
    BORROWED_ALIAS_EQUALS_FIELD,
    BORROWED_ALIAS_CLONE_BOX_FIELD,
    BORROWED_ALIAS_TO_STRING_BOX_LATEST_FRESH_FIELD,
    BORROWED_ALIAS_EQUALS_LATEST_FRESH_FIELD,
    BORROWED_ALIAS_CLONE_BOX_LATEST_FRESH_FIELD,
    BORROWED_ALIAS_BORROWED_SOURCE_FAST_FIELD,
    BORROWED_ALIAS_AS_STR_FAST_FIELD,
    BORROWED_ALIAS_AS_STR_FAST_LIVE_SOURCE_FIELD,
    BORROWED_ALIAS_AS_STR_FAST_STALE_SOURCE_FIELD,
    BORROWED_ALIAS_ARRAY_LEN_BY_INDEX_LATEST_FRESH_FIELD,
    BORROWED_ALIAS_ARRAY_INDEXOF_BY_INDEX_LATEST_FRESH_FIELD,
    BORROWED_ALIAS_ENCODE_EPOCH_HIT_FIELD,
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_FIELD,
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_ARRAY_GET_INDEX_FIELD,
    BORROWED_ALIAS_ENCODE_LIVE_SOURCE_HIT_MAP_RUNTIME_DATA_GET_ANY_FIELD,
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_FIELD,
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_ARRAY_GET_INDEX_FIELD,
    BORROWED_ALIAS_ENCODE_CACHED_HANDLE_HIT_MAP_RUNTIME_DATA_GET_ANY_FIELD,
    BORROWED_ALIAS_ENCODE_PTR_EQ_HIT_FIELD,
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_FIELD,
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_ARRAY_GET_INDEX_FIELD,
    BORROWED_ALIAS_ENCODE_TO_HANDLE_ARC_MAP_RUNTIME_DATA_GET_ANY_FIELD,
];
