use super::CoreMethodSpec;
use crate::runtime::core_box_ids::{CoreBoxId, CoreMethodId};

pub(super) const SPECS: &[CoreMethodSpec] = &[
    // StringBox methods
    CoreMethodSpec {
        id: CoreMethodId::StringLength,
        box_id: CoreBoxId::String,
        name: "length",
        arity: 0,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: true,
        allowed_in_init: true,
        vtable_slot: Some(300),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringUpper,
        box_id: CoreBoxId::String,
        name: "toUpper",
        arity: 0,
        return_type_name: "StringBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::StringLower,
        box_id: CoreBoxId::String,
        name: "toLower",
        arity: 0,
        return_type_name: "StringBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::StringConcat,
        box_id: CoreBoxId::String,
        name: "concat",
        arity: 1,
        return_type_name: "StringBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(302),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringSubstring,
        box_id: CoreBoxId::String,
        name: "substring",
        arity: 2,
        return_type_name: "StringBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(301),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringIndexOf,
        box_id: CoreBoxId::String,
        name: "indexOf",
        arity: 1,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(303),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringIndexOfFrom,
        box_id: CoreBoxId::String,
        name: "indexOf",
        arity: 2,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(303),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringReplace,
        box_id: CoreBoxId::String,
        name: "replace",
        arity: 2,
        return_type_name: "StringBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(304),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringTrim,
        box_id: CoreBoxId::String,
        name: "trim",
        arity: 0,
        return_type_name: "StringBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(305),
    },
    CoreMethodSpec {
        id: CoreMethodId::StringSplit,
        box_id: CoreBoxId::String,
        name: "split",
        arity: 1,
        return_type_name: "Unknown",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: None,
    },
    // IntegerBox methods
    CoreMethodSpec {
        id: CoreMethodId::IntegerAbs,
        box_id: CoreBoxId::Integer,
        name: "abs",
        arity: 0,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::IntegerMin,
        box_id: CoreBoxId::Integer,
        name: "min",
        arity: 1,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::IntegerMax,
        box_id: CoreBoxId::Integer,
        name: "max",
        arity: 1,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: None,
    },
    // BoolBox methods
    CoreMethodSpec {
        id: CoreMethodId::BoolNot,
        box_id: CoreBoxId::Bool,
        name: "not",
        arity: 0,
        return_type_name: "BoolBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::BoolAnd,
        box_id: CoreBoxId::Bool,
        name: "and",
        arity: 1,
        return_type_name: "BoolBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::BoolOr,
        box_id: CoreBoxId::Bool,
        name: "or",
        arity: 1,
        return_type_name: "BoolBox",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: None,
    },
    // ArrayBox methods
    CoreMethodSpec {
        id: CoreMethodId::ArrayLength,
        box_id: CoreBoxId::Array,
        name: "length",
        arity: 0,
        return_type_name: "IntegerBox",
        is_pure: true,
        allowed_in_condition: true,
        allowed_in_init: true,
        vtable_slot: Some(102),
    },
    CoreMethodSpec {
        id: CoreMethodId::ArrayPush,
        box_id: CoreBoxId::Array,
        name: "push",
        arity: 1,
        return_type_name: "Void",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: Some(103),
    },
    CoreMethodSpec {
        id: CoreMethodId::ArrayPop,
        box_id: CoreBoxId::Array,
        name: "pop",
        arity: 0,
        return_type_name: "Void",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: Some(104),
    },
    CoreMethodSpec {
        id: CoreMethodId::ArrayGet,
        box_id: CoreBoxId::Array,
        name: "get",
        arity: 1,
        return_type_name: "Unknown",
        is_pure: true,
        allowed_in_condition: true,
        allowed_in_init: true,
        vtable_slot: Some(100),
    },
    // MapBox methods
    CoreMethodSpec {
        id: CoreMethodId::MapGet,
        box_id: CoreBoxId::Map,
        name: "get",
        arity: 1,
        return_type_name: "Unknown",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(203),
    },
    CoreMethodSpec {
        id: CoreMethodId::MapSet,
        box_id: CoreBoxId::Map,
        name: "set",
        arity: 2,
        return_type_name: "StringBox",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: Some(204),
    },
    CoreMethodSpec {
        id: CoreMethodId::MapHas,
        box_id: CoreBoxId::Map,
        name: "has",
        arity: 1,
        return_type_name: "BoolBox",
        is_pure: true,
        allowed_in_condition: true,
        allowed_in_init: true,
        vtable_slot: Some(202),
    },
    CoreMethodSpec {
        id: CoreMethodId::MapKeys,
        box_id: CoreBoxId::Map,
        name: "keys",
        arity: 0,
        return_type_name: "Unknown",
        is_pure: true,
        allowed_in_condition: false,
        allowed_in_init: true,
        vtable_slot: Some(206),
    },
    // ConsoleBox methods
    CoreMethodSpec {
        id: CoreMethodId::ConsolePrintln,
        box_id: CoreBoxId::Console,
        name: "println",
        arity: 1,
        return_type_name: "Void",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: Some(400),
    },
    CoreMethodSpec {
        id: CoreMethodId::ConsoleLog,
        box_id: CoreBoxId::Console,
        name: "log",
        arity: 1,
        return_type_name: "Void",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: Some(400),
    },
    CoreMethodSpec {
        id: CoreMethodId::ConsoleError,
        box_id: CoreBoxId::Console,
        name: "error",
        arity: 1,
        return_type_name: "Void",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: Some(402),
    },
    // FileBox methods
    CoreMethodSpec {
        id: CoreMethodId::FileRead,
        box_id: CoreBoxId::File,
        name: "read",
        arity: 1,
        return_type_name: "StringBox",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::FileWrite,
        box_id: CoreBoxId::File,
        name: "write",
        arity: 1,
        return_type_name: "Void",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: None,
    },
    CoreMethodSpec {
        id: CoreMethodId::FileOpen,
        box_id: CoreBoxId::File,
        name: "open",
        arity: 1,
        return_type_name: "FileBox",
        is_pure: false,
        allowed_in_condition: false,
        allowed_in_init: false,
        vtable_slot: None,
    },
];
