#!/usr/bin/env python3
"""Generate a .hako embedded RustSubset JSON fixture provider.

This tool belongs to the input-route boundary, not converter core. It turns a
host-produced RustSubset JSON file into a static .hako fixture module.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def hako_string_literal(text: str) -> str:
    return json.dumps(text, ensure_ascii=False)


def render(box_name: str, json_text: str) -> str:
    literal = hako_string_literal(json_text)
    return f"""// generated by apps/rust-subset-to-hako/tools/embed_fixture.py
// host-generated embedded RustSubset JSON v0 fixture.

static box {box_name} {{
    json_text() {{
        return {literal}
    }}
}}
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("input_json", type=Path)
    parser.add_argument("-o", "--output", type=Path, required=True)
    parser.add_argument("--box-name", default="RustSubsetSimpleEmbeddedFixture")
    args = parser.parse_args()

    json_text = args.input_json.read_text(encoding="utf-8")
    # Fail fast if the producer did not hand off valid JSON.
    json.loads(json_text)
    args.output.write_text(render(args.box_name, json_text), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
