#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-runtime-data-dispatch-route-policy-contract"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_396="docs/development/current/main/phases/phase-296x/296x-396-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-INVENTORY.md"
CARD_397="docs/development/current/main/phases/phase-296x/296x-397-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-CONTRACT.md"
CARD_398="docs/development/current/main/phases/phase-296x/296x-398-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-IMPLEMENTATION.md"
CARD_399="docs/development/current/main/phases/phase-296x/296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT.md"
CARD_400="docs/development/current/main/phases/phase-296x/296x-400-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_runtime_data_dispatch_route_policy_contract_guard.sh"
RUNTIME_DATA_DISPATCH="src/llvm_py/instructions/mir_call/runtime_data_dispatch.py"
AUTO_SPECIALIZE="src/llvm_py/instructions/mir_call/auto_specialize.py"
TEST_POLICY="src/llvm_py/tests/test_runtime_data_dispatch_policy.py"

echo "[$TAG] checking RuntimeDataBox route policy contract"

guard_require_files "$TAG" "$CARD_396" "$CARD_397" "$CARD_398" "$CARD_399" "$CARD_400" "$STATE" "$INDEX" "$SELF_SCRIPT" "$RUNTIME_DATA_DISPATCH" "$AUTO_SPECIALIZE" "$TEST_POLICY"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_396" "row396 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_397" "row397 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_398" "row398 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_399" "row399 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_400" "row400 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-data-dispatch-route-policy-contract-v0' "$CARD_397" "row397 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=runtime-data-dispatch-route-policy-inventory-v0' "$CARD_397" "row397 must consume row396"
guard_expect_fixed_in_file "$TAG" 'runtime_data_array_route_policy_present=1' "$CARD_397" "row397 must keep the env policy visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_array_route_policy_env_present=1' "$CARD_397" "row397 must keep the env contract visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_select_call_spec_present=1' "$CARD_397" "row397 must keep the selector visible"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_route_present=1' "$CARD_397" "row397 must keep the array route predicate visible"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_i64_key_route_present=1' "$CARD_397" "row397 must keep the i64 key predicate visible"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_i64_key_i64_value_route_present=1' "$CARD_397" "row397 must keep the i64 key/value predicate visible"
guard_expect_fixed_in_file "$TAG" 'route_policy_surface_is_split_between_runtime_data_dispatch_and_auto_specialize=1' "$CARD_397" "row397 must keep the split visible"
guard_expect_fixed_in_file "$TAG" 'route_policy_invalid_env_fail_fast=1' "$CARD_397" "row397 must keep the env fail-fast visible"
guard_expect_fixed_in_file "$TAG" 'route_policy_default_uses_array_hint_predicates=1' "$CARD_397" "row397 must keep the default predicate relation visible"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_dispatch_is_not_direct_array=1' "$CARD_397" "row397 must keep DirectArray distinct"
guard_expect_fixed_in_file "$TAG" 'direct_array_handle_reinterpretation_allowed=0' "$CARD_397" "row397 must keep direct reinterpretation closed"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_route_policy_implementation' "$CARD_397" "row397 must point to the next implementation row"
guard_expect_fixed_in_file "$TAG" 'selected_reason=the_route_split_is_visible_but_the_contract_surface_needs_to_be_frozen_before_implementation' "$CARD_397" "row397 must explain why implementation is next"
guard_expect_fixed_in_file "$TAG" 'RPC-001: Route Policy Contract Surface Inventory' "$CARD_397" "row397 must split the contract surface inventory"
guard_expect_fixed_in_file "$TAG" 'RPC-002: Fail-Fast Boundary Note' "$CARD_397" "row397 must split the boundary note"
guard_expect_fixed_in_file "$TAG" 'RPC-003: Guard And Index' "$CARD_397" "row397 must keep the guard/index task"
guard_expect_fixed_in_file "$TAG" '_runtime_data_array_route_policy' "$RUNTIME_DATA_DISPATCH" "runtime_data_dispatch.py must keep the env-backed route policy"
guard_expect_fixed_in_file "$TAG" 'select_runtime_data_call_spec' "$RUNTIME_DATA_DISPATCH" "runtime_data_dispatch.py must keep the call-spec selector"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_route' "$AUTO_SPECIALIZE" "auto_specialize.py must keep the array route predicate"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_i64_key_route' "$AUTO_SPECIALIZE" "auto_specialize.py must keep the i64-key predicate"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_i64_key_i64_value_route' "$AUTO_SPECIALIZE" "auto_specialize.py must keep the i64 key/value predicate"
guard_expect_fixed_in_file "$TAG" 'test_default_prefers_array_i64_route_when_hints_match' "$TEST_POLICY" "policy tests must keep the array route case"
guard_expect_fixed_in_file "$TAG" 'test_policy_runtime_data_only_switch' "$TEST_POLICY" "policy tests must keep the env-switch case"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH-296X-001"' "$STATE" "current state must point to row400 owner refresh blocker"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT"' "$STATE" "current state must keep row399 as the latest landed card"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
