#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-runtime-data-dispatch-route-policy-implementation"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_397="docs/development/current/main/phases/phase-296x/296x-397-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-CONTRACT.md"
CARD_398="docs/development/current/main/phases/phase-296x/296x-398-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-IMPLEMENTATION.md"
CARD_399="docs/development/current/main/phases/phase-296x/296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT.md"
CARD_400="docs/development/current/main/phases/phase-296x/296x-400-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_runtime_data_dispatch_route_policy_implementation_guard.sh"
RUNTIME_DATA_DISPATCH="src/llvm_py/instructions/mir_call/runtime_data_dispatch.py"
RUNTIME_DATA_ROUTE_POLICY="src/llvm_py/instructions/mir_call/runtime_data_route_policy.py"
TEST_POLICY="src/llvm_py/tests/test_runtime_data_dispatch_policy.py"

echo "[$TAG] checking RuntimeDataBox route policy implementation"

guard_require_files "$TAG" "$CARD_397" "$CARD_398" "$CARD_399" "$CARD_400" "$STATE" "$INDEX" "$SELF_SCRIPT" "$RUNTIME_DATA_DISPATCH" "$RUNTIME_DATA_ROUTE_POLICY" "$TEST_POLICY"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_397" "row397 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_398" "row398 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_399" "row399 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_400" "row400 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-data-dispatch-route-policy-implementation-v0' "$CARD_398" "row398 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=runtime-data-dispatch-route-policy-contract-v0' "$CARD_398" "row398 must consume row397"
guard_expect_fixed_in_file "$TAG" 'policy_source_module=src/llvm_py/instructions/mir_call/runtime_data_route_policy.py' "$CARD_398" "row398 must pin the extracted policy source module"
guard_expect_fixed_in_file "$TAG" 'runtime_data_dispatch_thin_consumer=1' "$CARD_398" "row398 must keep runtime_data_dispatch thin"
guard_expect_fixed_in_file "$TAG" 'runtime_data_array_route_policy_present=1' "$CARD_398" "row398 must keep the env policy visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_array_route_policy_env_present=1' "$CARD_398" "row398 must keep the env contract visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_select_call_spec_present=1' "$CARD_398" "row398 must keep the selector visible"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_route_present=1' "$CARD_398" "row398 must keep the array route predicate visible"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_i64_key_route_present=1' "$CARD_398" "row398 must keep the i64 key predicate visible"
guard_expect_fixed_in_file "$TAG" 'prefer_runtime_data_array_i64_key_i64_value_route_present=1' "$CARD_398" "row398 must keep the i64 key/value predicate visible"
guard_expect_fixed_in_file "$TAG" 'route_policy_surface_is_split_between_runtime_data_dispatch_and_auto_specialize=1' "$CARD_398" "row398 must keep the split visible"
guard_expect_fixed_in_file "$TAG" 'route_policy_invalid_env_fail_fast=1' "$CARD_398" "row398 must keep the env fail-fast visible"
guard_expect_fixed_in_file "$TAG" 'route_policy_default_uses_array_hint_predicates=1' "$CARD_398" "row398 must keep the default predicate relation visible"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_dispatch_is_not_direct_array=1' "$CARD_398" "row398 must keep DirectArray distinct"
guard_expect_fixed_in_file "$TAG" 'direct_array_handle_reinterpretation_allowed=0' "$CARD_398" "row398 must keep direct reinterpretation closed"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_route_policy_keeper_measurement' "$CARD_398" "row398 must point to the keeper measurement row"
guard_expect_fixed_in_file "$TAG" 'selected_reason=the_policy_surface_now_has_a_dedicated_source_module_and_the_next_row_should_only_verify_the_extraction_is_stable' "$CARD_398" "row398 must explain why the keeper measurement row opens"
guard_expect_fixed_in_file "$TAG" 'RPI-001: Policy Source Module Extraction' "$CARD_398" "row398 must split the source-module extraction"
guard_expect_fixed_in_file "$TAG" 'RPI-002: Thin-Consumer Boundary Note' "$CARD_398" "row398 must split the boundary note"
guard_expect_fixed_in_file "$TAG" 'RPI-003: Guard And Index' "$CARD_398" "row398 must keep the guard/index task"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-data-dispatch-route-policy-keeper-measurement-v0' "$CARD_399" "row399 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=runtime-data-dispatch-route-policy-implementation-v0' "$CARD_399" "row399 must consume row398"
guard_expect_fixed_in_file "$TAG" 'policy_source_module=src/llvm_py/instructions/mir_call/runtime_data_route_policy.py' "$CARD_399" "row399 must pin the extracted policy source module"
guard_expect_fixed_in_file "$TAG" 'runtime_data_dispatch_thin_consumer=1' "$CARD_399" "row399 must keep runtime_data_dispatch thin"
guard_expect_fixed_in_file "$TAG" 'keeper_measurement_stability_smoke=ok' "$CARD_399" "row399 must keep the stability smoke visible"
guard_expect_fixed_in_file "$TAG" 'keeper_measurement_thin_consumer_smoke=ok' "$CARD_399" "row399 must keep the thin-consumer smoke visible"
guard_expect_fixed_in_file "$TAG" 'keeper_measurement_default_policy_smoke=ok' "$CARD_399" "row399 must keep the default-policy smoke visible"
guard_expect_fixed_in_file "$TAG" 'keeper_measurement_runtime_data_only_smoke=ok' "$CARD_399" "row399 must keep the runtime-data-only smoke visible"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_route_policy_owner_refresh' "$CARD_399" "row399 must point to the next owner refresh"
guard_expect_fixed_in_file "$TAG" 'selected_reason=the_policy_source_module_is_stable_and_the_next_row_should_refresh_the_owner_before_any_new_policy_change' "$CARD_399" "row399 must explain why the owner refresh opens"
guard_expect_fixed_in_file "$TAG" 'RKM-001: Stability Smoke' "$CARD_399" "row399 must split the stability smoke"
guard_expect_fixed_in_file "$TAG" 'RKM-002: Thin-Consumer Boundary Smoke' "$CARD_399" "row399 must split the thin-consumer smoke"
guard_expect_fixed_in_file "$TAG" 'RKM-003: Guard And Index' "$CARD_399" "row399 must keep the guard/index task"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-data-dispatch-route-policy-owner-refresh-v0' "$CARD_400" "row400 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=runtime-data-dispatch-route-policy-keeper-measurement-v0' "$CARD_400" "row400 must consume row399"
guard_expect_fixed_in_file "$TAG" 'runtime_data_dispatch_thin_consumer=1' "$CARD_400" "row400 must keep runtime_data_dispatch thin"
guard_expect_fixed_in_file "$TAG" 'runtime_data_route_policy_source_stable=1' "$CARD_400" "row400 must keep the policy source stable"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_consumer_callsite_attribution_refresh' "$CARD_400" "row400 must point to the next consumer attribution row"
guard_expect_fixed_in_file "$TAG" 'selected_reason=the_route_policy_module_is_stable_and_the_remaining_consumer_surface_needs_callsite_attribution_before_any_new_policy_change' "$CARD_400" "row400 must explain why the consumer attribution row opens"
guard_expect_fixed_in_file "$TAG" 'RDO-001: Collection-Method Surface Inventory' "$CARD_400" "row400 must split the collection-method inventory"
guard_expect_fixed_in_file "$TAG" 'RDO-006: Guard And Index' "$CARD_400" "row400 must keep the guard/index task"
guard_expect_fixed_in_file "$TAG" 'from .runtime_data_route_policy import' "$RUNTIME_DATA_DISPATCH" "runtime_data_dispatch.py must import the dedicated route-policy source"
guard_expect_fixed_in_file "$TAG" 'runtime_data_array_route_policy' "$RUNTIME_DATA_ROUTE_POLICY" "runtime_data_route_policy.py must keep the route policy source"
guard_expect_fixed_in_file "$TAG" 'prefer_array_mono_route_default' "$RUNTIME_DATA_ROUTE_POLICY" "runtime_data_route_policy.py must keep the default helper"
guard_expect_fixed_in_file "$TAG" 'reset_runtime_data_array_route_policy_cache_for_tests' "$RUNTIME_DATA_ROUTE_POLICY" "runtime_data_route_policy.py must keep the test cache reset helper"
guard_expect_fixed_in_file "$TAG" 'prefer_array_mono_route_default as _prefer_array_mono_route_default' "$TEST_POLICY" "policy tests must use the extracted route-policy source"
guard_expect_fixed_in_file "$TAG" 'reset_runtime_data_array_route_policy_cache_for_tests as _reset_runtime_data_array_route_policy_cache_for_tests' "$TEST_POLICY" "policy tests must use the extracted cache reset helper"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH-296X-001"' "$STATE" "current state must point to row400"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT"' "$STATE" "current state must keep row399 as the latest landed card"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
