#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-typed-object-legacy-field-helper-callsite-inventory"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_392="docs/development/current/main/phases/phase-296x/296x-392-SYMBOL-PRESENCE-PROBE.md"
CARD_393="docs/development/current/main/phases/phase-296x/296x-393-TYPED-OBJECT-LEGACY-FIELD-HELPER-CALLSITE-INVENTORY.md"
CARD_394="docs/development/current/main/phases/phase-296x/296x-394-RUNTIME-DATABOX-FIELD-DISPATCH-ROOT-CAUSE-INVENTORY.md"
CARD_395="docs/development/current/main/phases/phase-296x/296x-395-RUNTIME-DATA-DISPATCH-FIELD-ROUTE-INVENTORY.md"
CARD_396="docs/development/current/main/phases/phase-296x/296x-396-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-INVENTORY.md"
CARD_397="docs/development/current/main/phases/phase-296x/296x-397-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-CONTRACT.md"
CARD_398="docs/development/current/main/phases/phase-296x/296x-398-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-IMPLEMENTATION.md"
CARD_399="docs/development/current/main/phases/phase-296x/296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT.md"
CARD_400="docs/development/current/main/phases/phase-296x/296x-400-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_typed_object_legacy_field_helper_callsite_inventory_guard.sh"

echo "[$TAG] checking typed-object legacy field helper callsite inventory"

guard_require_files "$TAG" "$CARD_392" "$CARD_393" "$CARD_394" "$CARD_395" "$CARD_396" "$CARD_397" "$CARD_398" "$CARD_399" "$CARD_400" "$STATE" "$INDEX" "$SELF_SCRIPT"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_392" "row392 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_393" "row393 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_394" "row394 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_395" "row395 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_396" "row396 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_397" "row397 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_398" "row398 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_399" "row399 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_400" "row400 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=typed-object-legacy-field-helper-callsite-inventory-v0' "$CARD_393" "row393 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=symbol-presence-probe-v0' "$CARD_393" "row393 must consume row392"
guard_expect_fixed_in_file "$TAG" 'producer_files=newbox.py|constructor_call.py' "$CARD_393" "row393 must keep the producer split visible"
guard_expect_fixed_in_file "$TAG" 'consumer_files=collection_method_call.py' "$CARD_393" "row393 must keep the consumer split visible"
guard_expect_fixed_in_file "$TAG" 'carrier_file=resolver_helpers.py' "$CARD_393" "row393 must keep the fact carrier visible"
guard_expect_fixed_in_file "$TAG" 'miss_file=field_access.py' "$CARD_393" "row393 must keep the miss point visible"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_databox_field_dispatch_root_cause_inventory' "$CARD_393" "row393 must point to the RuntimeDataBox field-dispatch root cause inventory"
guard_expect_fixed_in_file "$TAG" 'selected_reason=producer_consumer_and_fact_carrier_are_located_but_the_runtime_databox_miss_still_needs_field_dispatch_root_cause_split' "$CARD_393" "row393 must explain why the next owner opens"
guard_expect_fixed_in_file "$TAG" 'CTI-001: newbox.py Producer Inventory' "$CARD_393" "row393 must split newbox into its own mini task"
guard_expect_fixed_in_file "$TAG" 'CTI-002: constructor_call.py Producer Inventory' "$CARD_393" "row393 must split constructor_call into its own mini task"
guard_expect_fixed_in_file "$TAG" 'CTI-003: collection_method_call.py Consumer Inventory' "$CARD_393" "row393 must split collection_method_call into its own mini task"
guard_expect_fixed_in_file "$TAG" 'CTI-004: resolver_helpers.py Carrier Inventory' "$CARD_393" "row393 must split resolver_helpers into its own mini task"
guard_expect_fixed_in_file "$TAG" 'CTI-005: field_access.py Miss Point Inventory' "$CARD_393" "row393 must split field_access into its own mini task"
guard_expect_fixed_in_file "$TAG" 'CTI-006: Next Owner Selection' "$CARD_393" "row393 must pick a next owner"
guard_expect_fixed_in_file "$TAG" 'CTI-007: Guard And Index' "$CARD_393" "row393 must keep the guard/index task"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT"' "$STATE" "current state must keep row399 as the latest landed card"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH-296X-001"' "$STATE" "current state must point to row400"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
