#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-typed-object-legacy-field-helper-owner-inventory"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_388="docs/development/current/main/phases/phase-296x/296x-388-LEGACY-HELPER-CACHE-OWNER-SELECTION-AFTER-ARRAYREPR-REBASE.md"
CARD_389="docs/development/current/main/phases/phase-296x/296x-389-TYPED-OBJECT-LEGACY-FIELD-HELPER-OWNER-INVENTORY.md"
CARD_390="docs/development/current/main/phases/phase-296x/296x-390-ARRAYREPR-FASTPATH-MISS-ROOT-CAUSE-INVENTORY.md"
CARD_391="docs/development/current/main/phases/phase-296x/296x-391-PUBLIC-ARRAYBOX-RUNTIME-SURFACE-CLASSIFIER-REFRESH.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_typed_object_legacy_field_helper_owner_inventory_guard.sh"

echo "[$TAG] checking typed-object legacy field helper owner inventory"

guard_require_files "$TAG" "$CARD_388" "$CARD_389" "$CARD_390" "$CARD_391" "$STATE" "$INDEX" "$SELF_SCRIPT"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_388" "row388 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_389" "row389 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_390" "row390 must be landed"
guard_expect_fixed_in_file "$TAG" 'output_contract=typed-object-legacy-field-helper-owner-inventory-v0' "$CARD_389" "row389 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=legacy-helper-cache-owner-selection-after-arrayrepr-rebase-v0' "$CARD_389" "row389 must consume row388"
guard_expect_fixed_in_file "$TAG" 'typed_object_legacy_field_helper_pct=76.34' "$CARD_389" "row389 must record the dominant legacy field helper pct"
guard_expect_fixed_in_file "$TAG" 'array_slot_backend_safe_pct=21.30' "$CARD_389" "row389 must record the ArrayBox runtime surface"
guard_expect_fixed_in_file "$TAG" 'array_handle_cache_pct=0.91' "$CARD_389" "row389 must record the array handle-cache surface"
guard_expect_fixed_in_file "$TAG" 'arraybox_runtime_total_pct=22.21' "$CARD_389" "row389 must record the combined ArrayBox runtime surface"
guard_expect_fixed_in_file "$TAG" 'typed_object_legacy_field_helper_dominates=1' "$CARD_389" "row389 must keep typed-object legacy field helpers dominant"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_runtime_surface=present_but_underclassified_by_row387' "$CARD_389" "row389 must keep ArrayBox runtime cost split out"
guard_expect_fixed_in_file "$TAG" 'arrayrepr_fastpath_miss_inventory_required=1' "$CARD_389" "row389 must require fastpath miss inventory"
guard_expect_fixed_in_file "$TAG" 'TLF-004: newbox.py Route Inventory' "$CARD_389" "row389 must split newbox into its own mini task"
guard_expect_fixed_in_file "$TAG" 'TLF-005: constructor_call.py Route Inventory' "$CARD_389" "row389 must split constructor_call into its own mini task"
guard_expect_fixed_in_file "$TAG" 'TLF-006: collection_method_call.py Route Inventory' "$CARD_389" "row389 must split collection_method_call into its own mini task"
guard_expect_fixed_in_file "$TAG" 'TLF-007: resolver_helpers.py Route Inventory' "$CARD_389" "row389 must split resolver_helpers into its own mini task"
guard_expect_fixed_in_file "$TAG" 'selected_next=arrayrepr_fastpath_miss_root_cause_inventory' "$CARD_389" "row389 must point to the fastpath miss root-cause inventory row"
guard_expect_fixed_in_file "$TAG" 'selected_reason=typed_object_route_inventory_is_complete_but_the_fastpath_miss_still_needs_root_cause_split' "$CARD_389" "row389 must explain why root-cause inventory is next"
guard_expect_fixed_in_file "$TAG" 'output_contract=arrayrepr-fastpath-miss-root-cause-inventory-v0' "$CARD_390" "row390 must define output contract"
guard_expect_fixed_in_file "$TAG" 'selected_next=public_arraybox_runtime_surface_classifier_refresh' "$CARD_390" "row390 must point to the public ArrayBox runtime surface classifier refresh"
guard_expect_fixed_in_file "$TAG" 'selected_reason=producer_consumer_carrier_split_still_leaves_public_arraybox_runtime_surface_underclassified' "$CARD_390" "row390 must explain why classifier refresh is next"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_391" "row391 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=public-arraybox-runtime-surface-classifier-refresh-v0' "$CARD_391" "row391 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=arrayrepr-fastpath-miss-root-cause-inventory-v0' "$CARD_391" "row391 must consume row390"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_runtime_surface=present_but_underclassified_by_row387' "$CARD_391" "row391 must keep the public ArrayBox runtime surface visible"
guard_expect_fixed_in_file "$TAG" 'array_slot_backend_safe_pct=21.30' "$CARD_391" "row391 must keep the safe backend split visible"
guard_expect_fixed_in_file "$TAG" 'array_handle_cache_pct=0.91' "$CARD_391" "row391 must keep the handle-cache split visible"
guard_expect_fixed_in_file "$TAG" 'arraybox_runtime_total_pct=22.21' "$CARD_391" "row391 must keep the combined public ArrayBox runtime surface visible"
guard_expect_fixed_in_file "$TAG" 'selected_next=symbol_presence_probe' "$CARD_391" "row391 must point to symbol presence probe"
guard_expect_fixed_in_file "$TAG" 'selected_reason=source_surface_is_known_but_symbol_presence_is_still_needed_to_pin_the_public_arraybox_runtime_surface_boundary' "$CARD_391" "row391 must explain why symbol presence probe is next"
guard_expect_fixed_in_file "$TAG" 'implementation_open=0' "$CARD_389" "row389 must keep implementation closed"
guard_expect_fixed_in_file "$TAG" 'optimization_open=0' "$CARD_389" "row389 must keep optimization closed"
guard_expect_fixed_in_file "$TAG" 'winner_claim=0' "$CARD_389" "row389 must keep winner claims closed"
guard_expect_fixed_in_file "$TAG" 'replacement_active=0' "$CARD_389" "row389 must keep replacement closed"
guard_expect_fixed_in_file "$TAG" 'hook_installed=0' "$CARD_389" "row389 must keep hooks closed"
guard_expect_fixed_in_file "$TAG" 'global_allocator=0' "$CARD_389" "row389 must keep global allocator closed"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "PUBLIC-ARRAYBOX-RUNTIME-SURFACE-CLASSIFIER-REFRESH-296X-001"' "$STATE" "current state must point to row391"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-390-ARRAYREPR-FASTPATH-MISS-ROOT-CAUSE-INVENTORY"' "$STATE" "current state must keep row390 as latest landed card"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
