#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-runtime-data-dispatch-field-route-inventory"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_394="docs/development/current/main/phases/phase-296x/296x-394-RUNTIME-DATABOX-FIELD-DISPATCH-ROOT-CAUSE-INVENTORY.md"
CARD_395="docs/development/current/main/phases/phase-296x/296x-395-RUNTIME-DATA-DISPATCH-FIELD-ROUTE-INVENTORY.md"
CARD_396="docs/development/current/main/phases/phase-296x/296x-396-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-INVENTORY.md"
CARD_397="docs/development/current/main/phases/phase-296x/296x-397-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-CONTRACT.md"
CARD_398="docs/development/current/main/phases/phase-296x/296x-398-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-IMPLEMENTATION.md"
CARD_399="docs/development/current/main/phases/phase-296x/296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT.md"
CARD_400="docs/development/current/main/phases/phase-296x/296x-400-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_runtime_data_dispatch_field_route_inventory_guard.sh"
RUNTIME_DATA_DISPATCH="src/llvm_py/instructions/mir_call/runtime_data_dispatch.py"
FIELD_ACCESS="src/llvm_py/instructions/field_access.py"

echo "[$TAG] checking RuntimeDataBox field route inventory"

guard_require_files "$TAG" "$CARD_394" "$CARD_395" "$CARD_396" "$CARD_397" "$CARD_398" "$CARD_399" "$CARD_400" "$STATE" "$INDEX" "$SELF_SCRIPT" "$RUNTIME_DATA_DISPATCH" "$FIELD_ACCESS"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_394" "row394 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_395" "row395 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_396" "row396 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_397" "row397 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_398" "row398 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_399" "row399 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_400" "row400 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-data-dispatch-field-route-inventory-v0' "$CARD_395" "row395 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=runtime-databox-field-dispatch-root-cause-inventory-v0' "$CARD_395" "row395 must consume row394"
guard_expect_fixed_in_file "$TAG" 'runtime_data_field_methods_present=1' "$CARD_395" "row395 must keep the field route map visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_field_route_policy_present=1' "$CARD_395" "row395 must keep the route policy visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_select_call_spec_present=1' "$CARD_395" "row395 must keep the call-spec selector visible"
guard_expect_fixed_in_file "$TAG" 'field_access_sink_present=1' "$CARD_395" "row395 must keep the field access sink visible"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_dispatch_is_not_direct_array=1' "$CARD_395" "row395 must keep DirectArray distinct"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_route_policy_inventory' "$CARD_395" "row395 must point to the next policy inventory"
guard_expect_fixed_in_file "$TAG" 'selected_reason=field_route_map_and_sink_are_pinned_but_the_route_policy_surface_still_needs_its_own_inventory' "$CARD_395" "row395 must explain why the next owner opens"
guard_expect_fixed_in_file "$TAG" 'RFI-001: Runtime Data Field Route Map Inventory' "$CARD_395" "row395 must split the route-map inventory"
guard_expect_fixed_in_file "$TAG" 'RFI-002: RuntimeDataBox Field Sink Check' "$CARD_395" "row395 must split the field sink check"
guard_expect_fixed_in_file "$TAG" 'RFI-003: Route Policy Boundary Note' "$CARD_395" "row395 must keep the route boundary note"
guard_expect_fixed_in_file "$TAG" 'RFI-004: Guard And Index' "$CARD_395" "row395 must keep the guard/index task"
guard_expect_fixed_in_file "$TAG" 'select_runtime_data_call_spec' "$RUNTIME_DATA_DISPATCH" "runtime_data_dispatch.py must keep the call-spec selector"
guard_expect_fixed_in_file "$TAG" '_RUNTIME_DATA_FIELD_METHODS' "$RUNTIME_DATA_DISPATCH" "runtime_data_dispatch.py must keep the field-route map"
guard_expect_fixed_in_file "$TAG" 'lower_runtime_data_field_call' "$RUNTIME_DATA_DISPATCH" "runtime_data_dispatch.py must keep the field sink lowerer"
guard_expect_fixed_in_file "$TAG" 'lower_runtime_data_field_call(' "$FIELD_ACCESS" "field_access.py must keep the field sink lowerer"
guard_expect_fixed_in_file "$TAG" 'method="getField"' "$FIELD_ACCESS" "field_access.py must keep the getField sink"
guard_expect_fixed_in_file "$TAG" 'method="setField"' "$FIELD_ACCESS" "field_access.py must keep the setField sink"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT"' "$STATE" "current state must keep row399 as the latest landed card"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH-296X-001"' "$STATE" "current state must point to row400"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
