#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-public-arraybox-runtime-surface-classifier-refresh"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_390="docs/development/current/main/phases/phase-296x/296x-390-ARRAYREPR-FASTPATH-MISS-ROOT-CAUSE-INVENTORY.md"
CARD_391="docs/development/current/main/phases/phase-296x/296x-391-PUBLIC-ARRAYBOX-RUNTIME-SURFACE-CLASSIFIER-REFRESH.md"
CARD_392="docs/development/current/main/phases/phase-296x/296x-392-SYMBOL-PRESENCE-PROBE.md"
CARD_393="docs/development/current/main/phases/phase-296x/296x-393-TYPED-OBJECT-LEGACY-FIELD-HELPER-CALLSITE-INVENTORY.md"
CARD_394="docs/development/current/main/phases/phase-296x/296x-394-RUNTIME-DATABOX-FIELD-DISPATCH-ROOT-CAUSE-INVENTORY.md"
CARD_395="docs/development/current/main/phases/phase-296x/296x-395-RUNTIME-DATA-DISPATCH-FIELD-ROUTE-INVENTORY.md"
CARD_396="docs/development/current/main/phases/phase-296x/296x-396-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-INVENTORY.md"
CARD_397="docs/development/current/main/phases/phase-296x/296x-397-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-CONTRACT.md"
CARD_398="docs/development/current/main/phases/phase-296x/296x-398-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-IMPLEMENTATION.md"
CARD_399="docs/development/current/main/phases/phase-296x/296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT.md"
CARD_400="docs/development/current/main/phases/phase-296x/296x-400-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
ARRAY_RS="crates/nyash_kernel/src/plugin/array.rs"
ARRAY_COMPAT="crates/nyash_kernel/src/plugin/array_compat.rs"
ARRAY_HANDLE_CACHE="crates/nyash_kernel/src/plugin/array_handle_cache.rs"
ARRAY_SLOT_BACKEND="crates/nyash_kernel/src/plugin/array_slot_backend.rs"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_public_arraybox_runtime_surface_classifier_refresh_guard.sh"

echo "[$TAG] checking public ArrayBox runtime surface classifier refresh"

guard_require_files "$TAG" "$CARD_390" "$CARD_391" "$CARD_392" "$CARD_393" "$CARD_394" "$CARD_395" "$CARD_396" "$CARD_397" "$CARD_398" "$CARD_399" "$CARD_400" "$STATE" "$INDEX" "$ARRAY_RS" "$ARRAY_COMPAT" "$ARRAY_HANDLE_CACHE" "$ARRAY_SLOT_BACKEND" "$SELF_SCRIPT"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_390" "row390 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_391" "row391 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_392" "row392 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_393" "row393 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_394" "row394 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_395" "row395 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_396" "row396 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_397" "row397 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_398" "row398 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_399" "row399 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_400" "row400 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=public-arraybox-runtime-surface-classifier-refresh-v0' "$CARD_391" "row391 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=arrayrepr-fastpath-miss-root-cause-inventory-v0' "$CARD_391" "row391 must consume row390"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_runtime_surface=present_but_underclassified_by_row387' "$CARD_391" "row391 must keep the public ArrayBox runtime surface visible"
guard_expect_fixed_in_file "$TAG" 'array_slot_backend_safe_pct=21.30' "$CARD_391" "row391 must keep the safe backend split visible"
guard_expect_fixed_in_file "$TAG" 'array_handle_cache_pct=0.91' "$CARD_391" "row391 must keep the handle-cache split visible"
guard_expect_fixed_in_file "$TAG" 'arraybox_runtime_total_pct=22.21' "$CARD_391" "row391 must keep the combined public ArrayBox runtime surface visible"
guard_expect_fixed_in_file "$TAG" 'selected_next=symbol_presence_probe' "$CARD_391" "row391 must point to symbol presence probe"
guard_expect_fixed_in_file "$TAG" 'selected_reason=source_surface_is_known_but_symbol_presence_is_still_needed_to_pin_the_public_arraybox_runtime_surface_boundary' "$CARD_391" "row391 must explain why symbol presence probe is next"
guard_expect_fixed_in_file "$TAG" 'output_contract=symbol-presence-probe-v0' "$CARD_392" "row392 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=public-arraybox-runtime-surface-classifier-refresh-v0' "$CARD_392" "row392 must consume row391"
guard_expect_fixed_in_file "$TAG" 'symbol_table_source=target/release/libnyash_kernel.a' "$CARD_392" "row392 must probe the built artifact"
guard_expect_fixed_in_file "$TAG" 'public_array_birth_symbol_present=1' "$CARD_392" "row392 must keep public ArrayBox birth present"
guard_expect_fixed_in_file "$TAG" 'direct_array_birth_symbol_present=1' "$CARD_392" "row392 must keep DirectArray birth present"
guard_expect_fixed_in_file "$TAG" 'legacy_object_field_symbol_present=1' "$CARD_392" "row392 must keep legacy field helpers present"
guard_expect_fixed_in_file "$TAG" 'legacy_object_exact_slot_symbol_present=1' "$CARD_392" "row392 must keep exact-slot helpers present"
guard_expect_fixed_in_file "$TAG" 'selected_next=typed_object_legacy_field_helper_callsite_inventory' "$CARD_392" "row392 must point to the next diagnostic owner"
guard_expect_fixed_in_file "$TAG" 'selected_reason=emitted_symbols_confirm_public_and_direct_array_surfaces_but_legacy_field_helper_callsites_still_need_attribution' "$CARD_392" "row392 must explain the next diagnostic owner"
guard_expect_fixed_in_file "$TAG" 'output_contract=typed-object-legacy-field-helper-callsite-inventory-v0' "$CARD_393" "row393 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=symbol-presence-probe-v0' "$CARD_393" "row393 must consume row392"
guard_expect_fixed_in_file "$TAG" 'producer_files=newbox.py|constructor_call.py' "$CARD_393" "row393 must keep the producer split visible"
guard_expect_fixed_in_file "$TAG" 'consumer_files=collection_method_call.py' "$CARD_393" "row393 must keep the consumer split visible"
guard_expect_fixed_in_file "$TAG" 'carrier_file=resolver_helpers.py' "$CARD_393" "row393 must keep the fact carrier visible"
guard_expect_fixed_in_file "$TAG" 'miss_file=field_access.py' "$CARD_393" "row393 must keep the miss point visible"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_databox_field_dispatch_root_cause_inventory' "$CARD_393" "row393 must point to the RuntimeDataBox field-dispatch root cause inventory"
guard_expect_fixed_in_file "$TAG" 'selected_reason=producer_consumer_and_fact_carrier_are_located_but_the_runtime_databox_miss_still_needs_field_dispatch_root_cause_split' "$CARD_393" "row393 must explain why the next owner opens"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-databox-field-dispatch-root-cause-inventory-v0' "$CARD_394" "row394 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=typed-object-legacy-field-helper-callsite-inventory-v0' "$CARD_394" "row394 must consume row393"
guard_expect_fixed_in_file "$TAG" 'field_access_sink_present=1' "$CARD_394" "row394 must keep the field access sink visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_dispatch_map_abi_present=1' "$CARD_394" "row394 must keep the dispatch map visible"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_get_sink=RuntimeDataBox.getField' "$CARD_394" "row394 must pin RuntimeDataBox.getField"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_set_sink=RuntimeDataBox.setField' "$CARD_394" "row394 must pin RuntimeDataBox.setField"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_dispatch_is_not_direct_array=1' "$CARD_394" "row394 must keep DirectArray distinct"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_field_route_inventory' "$CARD_394" "row394 must point to the next route inventory"
guard_expect_fixed_in_file "$TAG" 'selected_reason=field_access_falls_back_to_runtime_databox_map_abi_and_the_dispatch_surface_still_needs_route_attribution' "$CARD_394" "row394 must explain why the next owner opens"
guard_expect_fixed_in_file "$TAG" 'output_contract=runtime-data-dispatch-field-route-inventory-v0' "$CARD_395" "row395 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=runtime-databox-field-dispatch-root-cause-inventory-v0' "$CARD_395" "row395 must consume row394"
guard_expect_fixed_in_file "$TAG" 'runtime_data_field_methods_present=1' "$CARD_395" "row395 must keep the field route map visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_field_route_policy_present=1' "$CARD_395" "row395 must keep the route policy visible"
guard_expect_fixed_in_file "$TAG" 'runtime_data_select_call_spec_present=1' "$CARD_395" "row395 must keep the call-spec selector visible"
guard_expect_fixed_in_file "$TAG" 'field_access_sink_present=1' "$CARD_395" "row395 must keep the field access sink visible"
guard_expect_fixed_in_file "$TAG" 'runtime_databox_field_dispatch_is_not_direct_array=1' "$CARD_395" "row395 must keep DirectArray distinct"
guard_expect_fixed_in_file "$TAG" 'selected_next=runtime_data_dispatch_route_policy_inventory' "$CARD_395" "row395 must point to the next policy inventory"
guard_expect_fixed_in_file "$TAG" 'selected_reason=field_route_map_and_sink_are_pinned_but_the_route_policy_surface_still_needs_its_own_inventory' "$CARD_395" "row395 must explain why the next owner opens"
guard_expect_fixed_in_file "$TAG" 'pub use super::array_compat::*;' "$ARRAY_RS" "array.rs must remain the thin public facade"
guard_expect_fixed_in_file "$TAG" 'use super::array_handle_cache::with_array_box;' "$ARRAY_COMPAT" "array_compat.rs must keep the compat bridge"
guard_expect_fixed_in_file "$TAG" 'array_get_index_encoded_i64' "$ARRAY_HANDLE_CACHE" "array_handle_cache.rs must keep the handle-cache runtime surface"
guard_expect_fixed_in_file "$TAG" 'safe_store_i64' "$ARRAY_SLOT_BACKEND" "array_slot_backend.rs must keep the safe backend surface"
guard_expect_fixed_in_file "$TAG" 'implementation_open=0' "$CARD_391" "row391 must keep implementation closed"
guard_expect_fixed_in_file "$TAG" 'optimization_open=0' "$CARD_391" "row391 must keep optimization closed"
guard_expect_fixed_in_file "$TAG" 'winner_claim=0' "$CARD_391" "row391 must keep winner claims closed"
guard_expect_fixed_in_file "$TAG" 'replacement_active=0' "$CARD_391" "row391 must keep replacement closed"
guard_expect_fixed_in_file "$TAG" 'hook_installed=0' "$CARD_391" "row391 must keep hooks closed"
guard_expect_fixed_in_file "$TAG" 'global_allocator=0' "$CARD_391" "row391 must keep global allocator closed"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-399-RUNTIME-DATA-DISPATCH-ROUTE-POLICY-KEEPER-MEASUREMENT"' "$STATE" "current state must keep row399 as the latest landed card"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "RUNTIME-DATA-DISPATCH-ROUTE-POLICY-OWNER-REFRESH-296X-001"' "$STATE" "current state must point to row400"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
