#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-mimalloc-source-level-owner-refresh"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_413="docs/development/current/main/phases/phase-296x/296x-413-POST-DIRECTARRAY-REMAINING-DIRECT-PATH-SURFACE-CHECK.md"
CARD_414="docs/development/current/main/phases/phase-296x/296x-414-MIMALLOC-SOURCE-LEVEL-OWNER-REFRESH.md"
CARD_415="docs/development/current/main/phases/phase-296x/296x-415-MIMALLOC-SOURCE-LEVEL-OWNER-SELECTION.md"
MSR_001_NOTE="docs/development/current/main/investigations/phase296x-414-msr001-object-lifecycle-facade-scan.md"
MSR_002_NOTE="docs/development/current/main/investigations/phase296x-414-msr002-page-model-page-queue-scan.md"
MSR_003_NOTE="docs/development/current/main/investigations/phase296x-414-msr003-result-capsule-scan.md"
MSR_005_NOTE="docs/development/current/main/investigations/phase296x-414-msr005-array-lane-backlog-freeze.md"
ARRAY_ROADMAP="docs/development/current/main/design/array-lane-extension-roadmap-ssot.md"
ROUTE_TAXONOMY="docs/development/current/main/design/mimalloc-benchmark-route-taxonomy-ssot.md"
TYPE_ROUTE_PLANE="docs/development/current/main/design/type-abi-route-descriptor-plane-ssot.md"
MIMALLOC_WORKSTREAM="docs/development/current/main/workstreams/mimalloc-current.md"
TYPE_ROUTE_READONLY="tools/allocator/type_abi_route_descriptor_readonly.py"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_mimalloc_source_level_owner_refresh_guard.sh"

echo "[$TAG] checking mimalloc source-level owner refresh"

guard_require_files "$TAG" "$CARD_413" "$CARD_414" "$CARD_415" "$MSR_001_NOTE" "$MSR_002_NOTE" "$MSR_003_NOTE" "$MSR_005_NOTE" "$ARRAY_ROADMAP" "$ROUTE_TAXONOMY" "$TYPE_ROUTE_PLANE" "$MIMALLOC_WORKSTREAM" "$TYPE_ROUTE_READONLY" "$STATE" "$INDEX" "$SELF_SCRIPT"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_413" "row413 remaining direct-path check must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_414" "row414 source-level owner refresh must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Current' "$CARD_415" "row415 source-level owner selection must be current"
guard_expect_fixed_in_file "$TAG" 'provider_host_adapter_ldpreload' "$ROUTE_TAXONOMY" "route taxonomy must name provider-host adapter route"
guard_expect_fixed_in_file "$TAG" 'provider_hako_object_lifecycle_ldpreload' "$ROUTE_TAXONOMY" "route taxonomy must name hako object-lifecycle provider route"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_ldpreload' "$ROUTE_TAXONOMY" "route taxonomy must name future replacement-front product route"
guard_expect_fixed_in_file "$TAG" 'replacement_front_c_shim' "$ROUTE_TAXONOMY" "route taxonomy must name replacement-front C shim class"
guard_expect_fixed_in_file "$TAG" 'subject_N_benchmark_front_class' "$ROUTE_TAXONOMY" "route taxonomy must require subject front class"
guard_expect_fixed_in_file "$TAG" 'subject_N_hako_hot_path_claim=0|1' "$ROUTE_TAXONOMY" "route taxonomy must require subject hako hot path claim"
guard_expect_fixed_in_file "$TAG" 'metadata_verification_only' "$ROUTE_TAXONOMY" "route taxonomy must separate metadata verification from hot path"
guard_expect_fixed_in_file "$TAG" 'Descriptor Plane:' "$TYPE_ROUTE_PLANE" "type route plane must define descriptor plane"
guard_expect_fixed_in_file "$TAG" 'Execution Plane:' "$TYPE_ROUTE_PLANE" "type route plane must define execution plane"
guard_expect_fixed_in_file "$TAG" 'Hot Replacement Plane:' "$TYPE_ROUTE_PLANE" "type route plane must define hot replacement plane"
guard_expect_fixed_in_file "$TAG" 'Host Escape Plane:' "$TYPE_ROUTE_PLANE" "type route plane must define host escape plane"
guard_expect_fixed_in_file "$TAG" 'type_abi_hot_path_lookup_count=0' "$TYPE_ROUTE_PLANE" "type route plane must forbid hot path lookup"
guard_expect_fixed_in_file "$TAG" 'TYPEROUTE-001:' "$TYPE_ROUTE_PLANE" "type route plane must define first task"
guard_expect_fixed_in_file "$TAG" 'behavior change: none' "$TYPE_ROUTE_PLANE" "type route plane first task must be docs/report only"
guard_expect_fixed_in_file "$TAG" 'TYPEROUTE-002:' "$TYPE_ROUTE_PLANE" "type route plane must define report boundary task"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_present=1' "$TYPE_ROUTE_PLANE" "type route plane must require descriptor present field"
guard_expect_fixed_in_file "$TAG" 'TYPEROUTE-003:' "$TYPE_ROUTE_PLANE" "type route plane must define declared/execution split task"
guard_expect_fixed_in_file "$TAG" 'subject_N_declared_route' "$TYPE_ROUTE_PLANE" "type route plane must require subject declared route"
guard_expect_fixed_in_file "$TAG" 'subject_N_execution_route' "$TYPE_ROUTE_PLANE" "type route plane must require subject execution route"
guard_expect_fixed_in_file "$TAG" 'TYPEROUTE-004:' "$TYPE_ROUTE_PLANE" "type route plane must define readonly descriptor consumption task"
guard_expect_fixed_in_file "$TAG" 'output_contract=type-abi-route-descriptor-readonly-v0' "$TYPE_ROUTE_PLANE" "type route plane must require readonly descriptor output contract"
guard_expect_fixed_in_file "$TAG" 'readonly_descriptor_consumption=1' "$TYPE_ROUTE_PLANE" "type route plane must require readonly descriptor consumption"
guard_expect_fixed_in_file "$TAG" 'TYPEROUTE-005:' "$TYPE_ROUTE_PLANE" "type route plane must define provider registration report pairing task"
guard_expect_fixed_in_file "$TAG" 'provider_registration_v1_present=1' "$TYPE_ROUTE_PLANE" "type route plane must require provider registration report field"
guard_expect_fixed_in_file "$TAG" 'provider_registration_hot_path_uses=provider_ops_only' "$TYPE_ROUTE_PLANE" "type route plane must keep provider registration hot path on ops only"
guard_expect_fixed_in_file "$TAG" 'output_contract=mimalloc-source-level-owner-refresh-v0' "$CARD_414" "row414 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=post-directarray-remaining-direct-path-surface-check-v0' "$CARD_414" "row414 must consume row413"
guard_expect_fixed_in_file "$TAG" 'source_level_owner_surface=object_lifecycle_facade' "$CARD_414" "row414 must name the source-level owner surface"
guard_expect_fixed_in_file "$TAG" 'source_level_owner_file=lang/src/hako_alloc/memory/object_lifecycle_facade_box.hako' "$CARD_414" "row414 must name the source-level owner file"
guard_expect_fixed_in_file "$TAG" 'docs/development/current/main/investigations/phase296x-414-msr001-object-lifecycle-facade-scan.md' "$CARD_414" "row414 must link the MSR-001 note"
guard_expect_fixed_in_file "$TAG" 'docs/development/current/main/investigations/phase296x-414-msr002-page-model-page-queue-scan.md' "$CARD_414" "row414 must link the MSR-002 note"
guard_expect_fixed_in_file "$TAG" 'object_lifecycle_facade remains the top source-level owner surface for row414' "$MSR_001_NOTE" "MSR-001 note must confirm the source-level owner surface"
guard_expect_fixed_in_file "$TAG" 'Do not reopen any helper or substrate lane from this scan.' "$MSR_001_NOTE" "MSR-001 note must keep the lane closed"
guard_expect_fixed_in_file "$TAG" 'page-model/page-queue remain parked as source-level work for row414' "$MSR_002_NOTE" "MSR-002 note must keep page-model/page-queue parked"
guard_expect_fixed_in_file "$TAG" 'Do not reopen any direct-path surface from this scan.' "$MSR_002_NOTE" "MSR-002 note must keep the lane closed"
guard_expect_fixed_in_file "$TAG" 'The result capsule work remains closed for this lane.' "$MSR_003_NOTE" "MSR-003 note must keep result capsule closed"
guard_expect_fixed_in_file "$TAG" 'No ValueAggregate reopen is proposed from this scan.' "$MSR_003_NOTE" "MSR-003 note must keep ValueAggregate closed"
guard_expect_fixed_in_file "$TAG" 'Array extension work remains backlog for this row.' "$MSR_005_NOTE" "MSR-005 note must keep Array extension in backlog"
guard_expect_fixed_in_file "$TAG" 'Do not reopen the DirectArray fast-path lane from this scan.' "$MSR_005_NOTE" "MSR-005 note must keep the DirectArray lane closed"
guard_expect_fixed_in_file "$TAG" 'array_lane_extension_backlog_documented=1' "$CARD_414" "row414 must document the Array lane backlog"
guard_expect_fixed_in_file "$TAG" 'new_fast_path_open=0' "$CARD_414" "row414 must keep new fast paths closed"
guard_expect_fixed_in_file "$TAG" 'new_fast_path_owner=none' "$CARD_414" "row414 must not select a new fast-path owner"
guard_expect_fixed_in_file "$TAG" 'return_to_mimalloc_source_level=1' "$CARD_414" "row414 must return to mimalloc source-level optimization"
guard_expect_fixed_in_file "$TAG" 'selected_boundary=mimalloc_source_level_owner_selection' "$CARD_414" "row414 must open the source-level owner selection row"
guard_expect_fixed_in_file "$TAG" 'next_diagnostic=mimalloc_source_level_owner_selection' "$CARD_414" "row414 must point to the source-level owner selection row"
guard_expect_fixed_in_file "$TAG" 'selected_next=mimalloc_source_level_owner_selection' "$CARD_414" "row414 must point to the source-level owner selection row"
guard_expect_fixed_in_file "$TAG" 'output_contract=mimalloc-source-level-owner-selection-v0' "$CARD_415" "row415 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=mimalloc-source-level-owner-refresh-v0' "$CARD_415" "row415 must consume row414 refresh"
guard_expect_fixed_in_file "$TAG" 'source_level_owner_surface=object_lifecycle_facade' "$CARD_415" "row415 must keep object_lifecycle_facade as source-level owner"
guard_expect_fixed_in_file "$TAG" 'source_level_owner_file=lang/src/hako_alloc/memory/object_lifecycle_facade_box.hako' "$CARD_415" "row415 must name the source-level owner file"
guard_expect_fixed_in_file "$TAG" 'selected_boundary=object_lifecycle_facade_source_shape_inventory' "$CARD_415" "row415 must open source-shape inventory"
guard_expect_fixed_in_file "$TAG" 'selected_next=object_lifecycle_facade_source_shape_inventory' "$CARD_415" "row415 must point to source-shape inventory"
guard_expect_fixed_in_file "$TAG" 'selected_reason=object_lifecycle_facade_remains_top_source_level_owner_surface_after_refresh' "$CARD_415" "row415 must keep the source-level owner reason"
guard_expect_fixed_in_file "$TAG" 'docs/development/current/main/design/mimalloc-benchmark-route-taxonomy-ssot.md' "$CARD_415" "row415 must link route taxonomy"
guard_expect_fixed_in_file "$TAG" 'docs/development/current/main/design/type-abi-route-descriptor-plane-ssot.md' "$CARD_415" "row415 must link type route descriptor plane"
guard_expect_fixed_in_file "$TAG" 'provider_ldpreload_measurement_route=provider_host_adapter_ldpreload' "$CARD_415" "row415 must classify provider-host route"
guard_expect_fixed_in_file "$TAG" 'provider_ldpreload_hako_hot_path_claim=0' "$CARD_415" "row415 must not call provider-host thread evidence hako hot path"
guard_expect_fixed_in_file "$TAG" 'hako_mimalloc_thread_hot_path_claim=0' "$CARD_415" "row415 must not call provider-host thread evidence hako thread hot path"
guard_expect_fixed_in_file "$TAG" 'task_id=TYPEROUTE-001' "$CARD_415" "row415 must select TYPEROUTE-001 docs/report task"
guard_expect_fixed_in_file "$TAG" 'provider_benchmark_front_class=provider_host_adapter' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must classify provider benchmark front"
guard_expect_fixed_in_file "$TAG" 'provider_ldpreload_measurement_route=provider_host_adapter_ldpreload' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must classify provider-host route"
guard_expect_fixed_in_file "$TAG" 'provider_ldpreload_hako_hot_path_claim=0' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must close provider-host hako hot path claim"
guard_expect_fixed_in_file "$TAG" 'provider_manifest_hako_provider_object_lifecycle_entrypoint_usage=metadata_verification_only' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must mark object lifecycle as metadata only"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_plane_task_2026_06_04' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list type route descriptor task"
guard_expect_fixed_in_file "$TAG" 'type_abi_hot_path_lookup_allowed=0' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must forbid type ABI hot path lookup"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_report_boundary_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list type route descriptor report task"
guard_expect_fixed_in_file "$TAG" 'selected_next_task=TYPEROUTE-003' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must select declared/execution route split next"
guard_expect_fixed_in_file "$TAG" 'type_abi_declared_execution_route_split_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list declared/execution route split"
guard_expect_fixed_in_file "$TAG" 'selected_next_task=TYPEROUTE-004' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must select readonly descriptor consumption next"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_readonly_consumption_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list readonly descriptor consumption"
guard_expect_fixed_in_file "$TAG" 'selected_next_task=TYPEROUTE-005' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must select provider registration report pairing next"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_readonly.py' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name readonly descriptor adapter"
guard_expect_fixed_in_file "$TAG" 'provider_registration_report_pairing_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list provider registration report pairing"
guard_expect_fixed_in_file "$TAG" 'provider_registration_descriptor_ops_pairing=1' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must pair provider descriptor and ops in reports"
guard_expect_fixed_in_file "$TAG" 'provider_registration_type_abi_hot_path_lookup_count=0' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must keep type ABI out of provider hot path"
guard_expect_fixed_in_file "$TAG" 'bench_route_equivalence_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list route-equivalent benchmark task"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-001' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name route-equivalent benchmark task"
guard_expect_fixed_in_file "$TAG" 'candidate_benchmark_front_class=replacement_front_c_shim' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must compare C mimalloc against replacement front"
guard_expect_fixed_in_file "$TAG" 'replacement_front_bypasses_provider_dispatch=1' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must require replacement front provider-dispatch bypass"
guard_expect_fixed_in_file "$TAG" 'bench_route_equivalence_quality_refresh_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list route-equivalent measurement quality refresh"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-002' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name route-equivalent quality task"
guard_expect_fixed_in_file "$TAG" 'required_measurement_quality_fields=min_sample_seconds_required,min_observed_sample_seconds,measurement_quality' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must require measurement quality fields"
guard_expect_fixed_in_file "$TAG" 'corrected_interpretation=previous_8192_iter_threaded_gap_was_measurement_quality_too_short_not_thread_shape_evidence' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must correct short-sample threaded gap interpretation"
guard_expect_fixed_in_file "$TAG" 'replacement_front_ordinary_app_route_descriptor_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list ordinary app replacement-front route descriptor"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-003' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name ordinary app route descriptor task"
guard_expect_fixed_in_file "$TAG" 'ordinary_app_route_candidate=replacement_front_product_ldpreload' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must separate ordinary app product replacement candidate"
guard_expect_fixed_in_file "$TAG" 'product_gate=closed' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must keep product gate closed"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_contract_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list replacement-front product activation contract"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-004' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name replacement-front product activation contract task"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_contract_v0=1' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must require product activation contract"
guard_expect_fixed_in_file "$TAG" 'activation_blockers_initial=benchmark_only,product_gate_closed,no_activation_row,no_rollback_optout_plan' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list initial product activation blockers"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_smoke_pack_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list product replacement-front smoke pack"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-005' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name product replacement-front smoke pack task"
guard_expect_fixed_in_file "$TAG" 'product_smoke_pack_non_activating=1' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must keep product smoke pack non-activating"
guard_expect_fixed_in_file "$TAG" 'malloc_family_smoke=malloc,calloc,realloc,free,null_free' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must include malloc family smoke"
guard_expect_fixed_in_file "$TAG" 'smoke_pack_report=target/replacement-front-product-smoke-pack-gap.out' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must record product smoke pack evidence"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_smoke_pack_long_quality_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list product smoke pack long quality evidence"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-006' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name product smoke pack long quality task"
guard_expect_fixed_in_file "$TAG" 'report=target/replacement-front-product-smoke-pack-long-quality.out' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must record product smoke pack long quality report"
guard_expect_fixed_in_file "$TAG" 'replacement_front_vs_mimalloc_ratio=1.402' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must record long quality replacement-front ratio"
guard_expect_fixed_in_file "$TAG" 'selected_next_owner=product_replacement_rollback_optout_plan' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must select rollback optout plan next"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_rollback_optout_plan_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list replacement-front rollback optout plan"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-007' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name rollback optout task"
guard_expect_fixed_in_file "$TAG" 'rollback_optout_env=HAKORUNE_REPLACEMENT_FRONT_DISABLE' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must define rollback optout env"
guard_expect_fixed_in_file "$TAG" 'activation_blockers=benchmark_only,product_gate_closed,no_activation_row' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must remove rollback optout blocker"
guard_expect_fixed_in_file "$TAG" 'removed_activation_blocker=no_rollback_optout_plan' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must record removed rollback blocker"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_preflight_2026_06_05' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must list product activation preflight report"
guard_expect_fixed_in_file "$TAG" 'task_id=BENCH-ROUTE-EQUIV-008' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must name preflight report task"
guard_expect_fixed_in_file "$TAG" 'product_preflight_non_activating=1' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must keep preflight non-activating"
guard_expect_fixed_in_file "$TAG" 'preflight_evidence_ready_reported=1' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must report preflight evidence readiness"
guard_expect_fixed_in_file "$TAG" 'preflight_activation_ready=0' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must keep preflight activation closed"
guard_expect_fixed_in_file "$TAG" 'preflight_missing_always_includes=product_gate_open,activation_row' "$MIMALLOC_WORKSTREAM" "mimalloc workstream must keep product gate and activation row missing"
guard_expect_fixed_in_file "$TAG" 'type-abi-route-descriptor-readonly-v0' "$TYPE_ROUTE_READONLY" "readonly adapter must emit stable output contract"
guard_expect_fixed_in_file "$TAG" 'readonly_descriptor_consumption=1' "$TYPE_ROUTE_READONLY" "readonly adapter must emit readonly consumption field"
guard_expect_fixed_in_file "$TAG" 'hako_check_core_change=0' "$TYPE_ROUTE_READONLY" "readonly adapter must not change hako_check core"
guard_expect_fixed_in_file "$TAG" 'provider_abi_execution_change=0' "$TYPE_ROUTE_READONLY" "readonly adapter must not change Provider ABI execution"
guard_expect_fixed_in_file "$TAG" 'replacement_front_hot_path_change=0' "$TYPE_ROUTE_READONLY" "readonly adapter must not change replacement-front hot path"
guard_expect_fixed_in_file "$TAG" 'host_backed_adapter provider route must not claim .hako hot path' "$TYPE_ROUTE_READONLY" "readonly adapter must guard host-backed hako hot path claim"
guard_expect_fixed_in_file "$TAG" 'benchmark replacement-front route must not claim product replacement' "$TYPE_ROUTE_READONLY" "readonly adapter must guard benchmark replacement-front product claims"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_contract_v0' "$TYPE_ROUTE_READONLY" "readonly adapter must expose product activation contract"
guard_expect_fixed_in_file "$TAG" 'replacement_front_rollback_optout_plan_v0' "$TYPE_ROUTE_READONLY" "readonly adapter must expose rollback optout plan"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_report_v0' "$TYPE_ROUTE_READONLY" "readonly adapter must expose product preflight report"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_activation_ready' "$TYPE_ROUTE_READONLY" "readonly adapter must expose product preflight activation readiness"
guard_expect_fixed_in_file "$TAG" 'provider_ldpreload_declared_route' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit provider declared route"
guard_expect_fixed_in_file "$TAG" 'provider_ldpreload_execution_route' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit provider execution route"
guard_expect_fixed_in_file "$TAG" 'host_backed_adapter provider route must not claim .hako hot path' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must guard host-backed hako hot path claim"
guard_expect_fixed_in_file "$TAG" 'subject_{index}_declared_route' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit subject declared route"
guard_expect_fixed_in_file "$TAG" 'subject_{index}_execution_route' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit subject execution route"
guard_expect_fixed_in_file "$TAG" 'provider_declared_route' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift provider declared route"
guard_expect_fixed_in_file "$TAG" 'provider_execution_route' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift provider execution route"
guard_expect_fixed_in_file "$TAG" 'provider_registration_v1_present=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit provider registration report pairing"
guard_expect_fixed_in_file "$TAG" 'provider_registration_hot_path_uses=provider_ops_only' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must keep provider registration hot path on ops"
guard_expect_fixed_in_file "$TAG" 'provider_registration_type_abi_hot_path_lookup_count=0' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must keep type ABI lookup out of hot path"
guard_expect_fixed_in_file "$TAG" 'provider_registration_v1_present' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift provider registration field"
guard_expect_fixed_in_file "$TAG" 'provider_registration_hot_path_uses' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift provider registration hot path field"
guard_expect_fixed_in_file "$TAG" 'replacement_front_subject_present=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must summarize replacement-front subject presence"
guard_expect_fixed_in_file "$TAG" 'same_benchmark_binary=1' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must report same benchmark binary"
guard_expect_fixed_in_file "$TAG" 'min_sample_seconds_required=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must report required minimum sample seconds"
guard_expect_fixed_in_file "$TAG" 'measurement_quality=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must report measurement quality"
guard_expect_fixed_in_file "$TAG" 'measurement_too_short' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must fail short measurement quality"
guard_expect_fixed_in_file "$TAG" 'replacement_front_ordinary_app_route_candidate=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift ordinary app replacement-front route candidate"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_gate=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift replacement-front product gate"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_contract_v0=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift replacement-front product activation contract"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_blockers=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift replacement-front product activation blockers"
guard_expect_fixed_in_file "$TAG" 'replacement_front_rollback_optout_plan_v0=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift rollback optout plan"
guard_expect_fixed_in_file "$TAG" 'replacement_front_rollback_optout_env=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift rollback optout env"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_report_v0=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift product preflight report"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_activation_ready=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift product preflight activation readiness"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_missing=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift product preflight missing fields"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_smoke_pack_v0' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift product smoke pack"
guard_expect_fixed_in_file "$TAG" 'replacement_front_malloc_family_smoke_ok' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift malloc family smoke"
guard_expect_fixed_in_file "$TAG" '--replacement-front-cross-thread-smoke' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must expose replacement-front cross-thread smoke"
guard_expect_fixed_in_file "$TAG" 'replacement_front_bypasses_type_abi=1' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must report replacement front bypasses Type ABI"
guard_expect_fixed_in_file "$TAG" 'replacement_front_bypasses_provider_dispatch=' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must report replacement front bypasses provider dispatch"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_present=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit type ABI descriptor present"
guard_expect_fixed_in_file "$TAG" 'type_abi_hot_path_lookup_count=0' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit zero type ABI hot path lookup"
guard_expect_fixed_in_file "$TAG" 'measurement_quality=' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit measurement quality"
guard_expect_fixed_in_file "$TAG" 'subject_{index}_sample_seconds_min' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit subject sample seconds"
guard_expect_fixed_in_file "$TAG" 'replacement_front_ordinary_app_route_candidate=replacement_front_product_ldpreload' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit ordinary app replacement-front route candidate"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_gate=closed' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must keep replacement-front product gate closed"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_contract_v0=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit replacement-front product activation contract"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_activation_blockers=' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit replacement-front product activation blockers"
guard_expect_fixed_in_file "$TAG" 'replacement_front_rollback_optout_plan_v0=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit rollback optout plan"
guard_expect_fixed_in_file "$TAG" 'replacement_front_rollback_optout_env=HAKORUNE_REPLACEMENT_FRONT_DISABLE' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit rollback optout env"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_report_v0=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit product preflight report"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_activation_ready=0' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must keep product preflight activation readiness closed"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_preflight_missing=' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit product preflight missing fields"
guard_expect_fixed_in_file "$TAG" 'REPLACEMENT_FRONT_MALLOC_FAMILY_SMOKE_C' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must import malloc family smoke"
guard_expect_fixed_in_file "$TAG" 'replacement_front_product_smoke_pack_non_activating=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit non-activating product smoke pack"
guard_expect_fixed_in_file "$TAG" 'replacement_front_malloc_family_null_free_smoke_ok=1' "tools/allocator/hakozuna_mixed_ws_ldpreload_compare.py" "hakozuna compare must emit null free smoke"
guard_expect_fixed_in_file "$TAG" 'REPLACEMENT_FRONT_MALLOC_FAMILY_SMOKE_C' "tools/allocator/replacement_front_templates.py" "replacement front templates must define malloc family smoke"
guard_expect_fixed_in_file "$TAG" 'type_abi_route_descriptor_present' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift type ABI descriptor present"
guard_expect_fixed_in_file "$TAG" 'type_abi_hot_path_lookup_count' "tools/allocator/hakozuna_mixed_ws_gap_ladder.py" "gap ladder must lift type ABI hot path lookup"
guard_expect_fixed_in_file "$TAG" 'open_new_fast_path_only_if_positive_net_helper_delta=1' "$CARD_414" "row414 must keep positive-net helper delta required"
guard_expect_fixed_in_file "$TAG" 'open_new_fast_path_only_if_perf_owner_pct_above_threshold=1' "$CARD_414" "row414 must keep perf-owner evidence required"
guard_expect_fixed_in_file "$TAG" 'open_new_fast_path_only_if_selected_callsite_or_family=1' "$CARD_414" "row414 must keep selected callsite/family evidence required"
guard_expect_fixed_in_file "$TAG" 'open_new_fast_path_only_if_no_recent_nonkeeper=1' "$CARD_414" "row414 must keep recent non-keeper repeats out"
guard_expect_fixed_in_file "$TAG" 'open_new_fast_path_only_if_no_silent_fallback=1' "$CARD_414" "row414 must keep silent fallback forbidden"
guard_expect_fixed_in_file "$TAG" 'optimization_open=0' "$CARD_414" "row414 must keep optimization closed"
guard_expect_fixed_in_file "$TAG" 'winner_claim=0' "$CARD_414" "row414 must keep winner claims closed"
guard_expect_fixed_in_file "$TAG" 'replacement_active=0' "$CARD_414" "row414 must keep replacement closed"
guard_expect_fixed_in_file "$TAG" 'hook_installed=0' "$CARD_414" "row414 must keep hooks closed"
guard_expect_fixed_in_file "$TAG" 'global_allocator=0' "$CARD_414" "row414 must keep global allocator closed"
guard_expect_fixed_in_file "$TAG" 'summary=ok' "$CARD_414" "row414 must end ok"
guard_expect_fixed_in_file "$TAG" 'Layer 1: public ArrayBox identity' "$ARRAY_ROADMAP" "Array roadmap must preserve public identity layer"
guard_expect_fixed_in_file "$TAG" 'Layer 2: internal residence lane' "$ARRAY_ROADMAP" "Array roadmap must define internal residence layer"
guard_expect_fixed_in_file "$TAG" 'Layer 3: ABI / plugin / type-specific transport' "$ARRAY_ROADMAP" "Array roadmap must define transport layer"
guard_expect_fixed_in_file "$TAG" 'ArrayStorage::InlineI64' "$ARRAY_ROADMAP" "Array roadmap must list InlineI64"
guard_expect_fixed_in_file "$TAG" 'ArrayStorage::InlineBool' "$ARRAY_ROADMAP" "Array roadmap must list InlineBool"
guard_expect_fixed_in_file "$TAG" 'ArrayStorage::InlineF64' "$ARRAY_ROADMAP" "Array roadmap must list InlineF64"
guard_expect_fixed_in_file "$TAG" 'ArrayStorage::Text' "$ARRAY_ROADMAP" "Array roadmap must list Text"
guard_expect_fixed_in_file "$TAG" 'plugin object:' "$ARRAY_ROADMAP" "Array roadmap must define plugin object transport"
guard_expect_fixed_in_file "$TAG" 'Boxed / handle' "$ARRAY_ROADMAP" "Array roadmap must keep plugin objects boxed/handled first"
guard_expect_fixed_in_file "$TAG" 'DirectRecord' "$ARRAY_ROADMAP" "Array roadmap must defer DirectRecord"
guard_expect_fixed_in_file "$TAG" 'ARR-001: Scalar Residence Truth Refresh' "$ARRAY_ROADMAP" "Array roadmap must list scalar refresh task"
guard_expect_fixed_in_file "$TAG" 'ARR-007: Record / Union Inline Layout Inventory' "$ARRAY_ROADMAP" "Array roadmap must list record/union inventory task"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "MIMALLOC-SOURCE-LEVEL-OWNER-SELECTION-296X-001"' "$STATE" "current state must point to row415"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-414-MIMALLOC-SOURCE-LEVEL-OWNER-REFRESH"' "$STATE" "current state must land row414"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
