#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
TAG="k2-wide-phase295x-malloc-large-workload-contract"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD="docs/development/current/main/phases/phase-295x/295x-187-MIMALLOC-COMPARISON-MIMALLOC-BENCH-MALLOC-LARGE-WORKLOAD-CONTRACT.md"
NEXT_CARD="docs/development/current/main/phases/phase-295x/295x-188-MIMALLOC-COMPARISON-MIMALLOC-BENCH-MALLOC-LARGE-EVIDENCE-RUN.md"
TASKBOARD="docs/development/current/main/phases/phase-295x/295x-90-mimalloc-comparison-execution-taskboard.md"
CATALOG="docs/development/current/main/phases/phase-295x/295x-hakmem-external-results-catalog-v0.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase295x_malloc_large_workload_contract_guard.sh"
BENCH="tools/allocator/hakmem_external_bench.py"
NORMALIZER="tools/allocator/mimalloc_comparison_memory_report.py"
HUGE_APP="apps/hako-alloc-mimalloc-comparison-huge-ish-exe-proof/main.hako"

echo "[$TAG] checking phase-295x malloc-large workload contract"

guard_require_files "$TAG" "$CARD" "$NEXT_CARD" "$TASKBOARD" "$CATALOG" "$INDEX" "$SELF_SCRIPT" "$BENCH" "$NORMALIZER" "$HUGE_APP"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_in_file "$TAG" 'MIMALLOC-COMPARISON-MIMALLOC-BENCH-MALLOC-LARGE-WORKLOAD-CONTRACT-295X-001' "$CARD" "card must identify the current blocker"
guard_expect_in_file "$TAG" 'workload=representative-huge-ish-v0' "$CARD" "card must select the huge-ish workload"
guard_expect_in_file "$TAG" 'operation_family=huge-ish' "$CARD" "card must publish the huge-ish operation family"
guard_expect_in_file "$TAG" 'operation_sequence_id=representative-huge-ish-v0-seq' "$CARD" "card must publish the huge-ish operation sequence id"
guard_expect_in_file "$TAG" 'free_order_id=ascending-release-v0' "$CARD" "card must publish the huge-ish free-order id"
guard_expect_in_file "$TAG" 'allocation_count=2' "$CARD" "card must keep the allocation count fixed"
guard_expect_in_file "$TAG" 'free_count=2' "$CARD" "card must keep the free count fixed"
guard_expect_in_file "$TAG" 'requested_bytes=4194321' "$CARD" "card must keep the requested bytes fixed"
guard_expect_in_file "$TAG" 'large_request_count=1' "$CARD" "card must keep the large request count fixed"
guard_expect_in_file "$TAG" 'MIMALLOC-COMPARISON-MIMALLOC-BENCH-MALLOC-LARGE-EVIDENCE-295X-RUN-001' "$CARD" "card must select the next evidence row"
guard_expect_in_file "$TAG" 'MIMALLOC-COMPARISON-MIMALLOC-BENCH-MALLOC-LARGE-EVIDENCE-295X-RUN-001' "$NEXT_CARD" "next card must be the evidence run"
guard_expect_in_file "$TAG" 'mimalloc-bench-malloc-large' "$NEXT_CARD" "next card must keep the external malloc-large family"
guard_expect_in_file "$TAG" 'representative-huge-ish-v0' "$NEXT_CARD" "next card must keep the selected .hako alignment seam"
guard_expect_in_file "$TAG" 'selected_next_workload_family = "mimalloc-bench-malloc-large"' "$CATALOG" "catalog must keep malloc-large selected"
guard_expect_in_file "$TAG" 'bench_results/s51_malloc_large_b40795031_20260105_105541' "$CATALOG" "catalog must keep the malloc-large secondary evidence"
guard_expect_in_file "$TAG" 'malloc-large' "$BENCH" "external bench helper must support malloc-large"
guard_expect_in_file "$TAG" 'malloc-large-old' "$BENCH" "external bench helper must keep the historical malloc-large alias"
guard_expect_in_file "$TAG" 'operation_sequence_match=' "$NORMALIZER" "normalizer must keep operation sequence comparison"
guard_expect_in_file "$TAG" 'free_order_match=' "$NORMALIZER" "normalizer must keep free order comparison"
guard_expect_in_file "$TAG" 'large_request_count_delta=' "$NORMALIZER" "normalizer must keep large request count comparison"
guard_expect_in_file "$TAG" 'workload=representative-huge-ish-v0' "$HUGE_APP" "huge-ish app must keep the aligned workload id"
guard_expect_in_file "$TAG" 'operation_family=huge-ish' "$HUGE_APP" "huge-ish app must keep the aligned operation family"
guard_expect_in_file "$TAG" 'operation_sequence_id=representative-huge-ish-v0-seq' "$HUGE_APP" "huge-ish app must keep the aligned sequence id"
guard_expect_in_file "$TAG" 'free_order_id=ascending-release-v0' "$HUGE_APP" "huge-ish app must keep the aligned free order"
guard_expect_in_file "$TAG" 'requested_bytes=4194321' "$HUGE_APP" "huge-ish app must keep the requested bytes contract"
guard_expect_in_file "$TAG" 'large_request_count=1' "$HUGE_APP" "huge-ish app must keep the large request count contract"
guard_expect_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check script index must list this guard"
guard_expect_in_file "$TAG" '295x-187' "$TASKBOARD" "taskboard must keep the landed contract row"
guard_expect_in_file "$TAG" 'MIMALLOC-COMPARISON-MIMALLOC-BENCH-MALLOC-LARGE-EVIDENCE-295X-RUN-001' "$TASKBOARD" "taskboard must keep the evidence blocker row"

echo "[$TAG] ok"
