#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="k2-wide-phase296x-collection-method-direct-array-lane-legacy-helper-cache-retirement-implementation"
cd "$ROOT_DIR"
source tools/checks/lib/guard_common.sh

CARD_409="docs/development/current/main/phases/phase-296x/296x-409-COLLECTION-METHOD-DIRECT-ARRAY-LANE-LEGACY-HELPER-CACHE-RETIREMENT-SELECTION.md"
CARD_410="docs/development/current/main/phases/phase-296x/296x-410-COLLECTION-METHOD-DIRECT-ARRAY-LANE-LEGACY-HELPER-CACHE-RETIREMENT-IMPLEMENTATION.md"
CARD_411="docs/development/current/main/phases/phase-296x/296x-411-COLLECTION-METHOD-DIRECT-ARRAY-LANE-LEGACY-HELPER-CACHE-RETIREMENT-SEMANTIC-SMOKE.md"
CARD_412="docs/development/current/main/phases/phase-296x/296x-412-COLLECTION-METHOD-DIRECT-ARRAY-LANE-POST-RETIREMENT-PERF-OWNER-REFRESH.md"
CARD_413="docs/development/current/main/phases/phase-296x/296x-413-POST-DIRECTARRAY-REMAINING-DIRECT-PATH-SURFACE-CHECK.md"
CARD_414="docs/development/current/main/phases/phase-296x/296x-414-MIMALLOC-SOURCE-LEVEL-OWNER-REFRESH.md"
CARD_373="docs/development/current/main/phases/phase-296x/296x-373-ARRAYBOX-PUBLIC-SEMANTICS-AND-DIRECTARRAY-SPLIT-SSOT.md"
STATE="docs/development/current/main/CURRENT_STATE.toml"
INDEX="docs/tools/check-scripts-index.md"
SELF_SCRIPT="tools/checks/k2_wide_phase296x_collection_method_direct_array_lane_legacy_helper_cache_retirement_implementation_guard.sh"

echo "[$TAG] checking collection-method direct-array lane legacy helper/cache retirement implementation"

guard_require_files "$TAG" "$CARD_409" "$CARD_410" "$CARD_411" "$CARD_412" "$CARD_413" "$CARD_414" "$CARD_373" "$STATE" "$INDEX" "$SELF_SCRIPT"
guard_require_exec_files "$TAG" "$SELF_SCRIPT"

guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_409" "row409 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_410" "row410 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_411" "row411 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_412" "row412 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_413" "row413 must be landed"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_414" "row414 must be current"
guard_expect_fixed_in_file "$TAG" 'output_contract=collection-method-direct-array-lane-legacy-helper-cache-retirement-implementation-v0' "$CARD_410" "row410 must define output contract"
guard_expect_fixed_in_file "$TAG" 'input_contract=collection-method-direct-array-lane-legacy-helper-cache-retirement-selection-v0' "$CARD_410" "row410 must consume row409"
guard_expect_fixed_in_file "$TAG" 'implementation_scope=single_thread_exact_array_helper_backend' "$CARD_410" "row410 must scope only the exact-array helper backend"
guard_expect_fixed_in_file "$TAG" 'selected_retirement_target=single_thread_exact_array_helper_backend' "$CARD_410" "row410 must keep the scoped retirement target fixed"
guard_expect_fixed_in_file "$TAG" 'selected_backend=direct_array_i64_exact' "$CARD_410" "row410 must keep the direct backend fixed"
guard_expect_fixed_in_file "$TAG" 'handle_entry_cache_retirement_deferred=1' "$CARD_410" "row410 must defer handle-entry cache retirement"
guard_expect_fixed_in_file "$TAG" 'public_helper_fast_lane_retirement_deferred=1' "$CARD_410" "row410 must defer public helper fast-lane retirement"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_semantics_preserved=1' "$CARD_410" "row410 must preserve public ArrayBox semantics"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_behavior_deletion=0' "$CARD_410" "row410 must forbid public ArrayBox deletion"
guard_expect_fixed_in_file "$TAG" 'handle_entry_cache_deletion=0' "$CARD_410" "row410 must forbid handle-entry cache deletion"
guard_expect_fixed_in_file "$TAG" 'public_helper_abi_removal=0' "$CARD_410" "row410 must forbid public helper ABI removal"
guard_expect_fixed_in_file "$TAG" 'directarray_helper_route_fail_fast_until_scoped_replaced=1' "$CARD_410" "row410 must keep the DirectArray helper route fail-fast until replaced"
guard_expect_fixed_in_file "$TAG" 'selected_next=collection_method_call_direct_array_lane_legacy_helper_cache_retirement_semantic_smoke' "$CARD_410" "row410 must point to the post-retirement semantic smoke"
guard_expect_fixed_in_file "$TAG" 'selected_next=collection_method_call_direct_array_lane_post_retirement_perf_owner_refresh' "$CARD_411" "row411 must point to the post-retirement perf owner refresh"
guard_expect_fixed_in_file "$TAG" 'selected_method=HakoAllocPageModel.acquire_usize/1' "$CARD_411" "row411 must keep the selected method fixed"
guard_expect_fixed_in_file "$TAG" 'selected_backend=direct_array_i64_exact' "$CARD_411" "row411 must keep the direct backend fixed"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_birth_smoke=ok' "$CARD_411" "row411 must smoke public ArrayBox birth"
guard_expect_fixed_in_file "$TAG" 'direct_array_birth_smoke=ok' "$CARD_411" "row411 must smoke DirectArray birth"
guard_expect_fixed_in_file "$TAG" 'direct_array_materialization_snapshot_smoke=ok' "$CARD_411" "row411 must smoke DirectArray materialization"
guard_expect_fixed_in_file "$TAG" 'selected_method_direct_array_lowering_smoke=ok' "$CARD_411" "row411 must smoke selected-method direct lowering"
guard_expect_fixed_in_file "$TAG" 'proof_app_summary=ok' "$CARD_411" "row411 must keep proof-app summary ok"
guard_expect_fixed_in_file "$TAG" 'silent_fallback_allowed=0' "$CARD_411" "row411 must keep silent fallback forbidden"
guard_expect_fixed_in_file "$TAG" 'public_arraybox_behavior_deletion=0' "$CARD_411" "row411 must keep public ArrayBox behavior intact"
guard_expect_fixed_in_file "$TAG" 'handle_entry_cache_deletion=0' "$CARD_411" "row411 must keep handle-entry cache retirement deferred"
guard_expect_fixed_in_file "$TAG" 'public_helper_abi_removal=0' "$CARD_411" "row411 must keep public helper ABI intact"
guard_expect_fixed_in_file "$TAG" 'selected_next=collection_method_call_direct_array_lane_post_retirement_perf_owner_refresh' "$CARD_411" "row411 must point to the post-retirement perf owner refresh"
guard_expect_fixed_in_file "$TAG" 'Status: Landed' "$CARD_373" "row373 split SSOT must stay landed"
guard_expect_fixed_in_file "$TAG" 'selected_next=array_repr_design_row' "$CARD_412" "row412 must point to the ArrayRepr design row"
guard_expect_fixed_in_file "$TAG" 'selected_next=mimalloc_source_level_owner_refresh' "$CARD_413" "row413 must point to mimalloc source-level owner refresh"
guard_expect_fixed_in_file "$TAG" 'selected_next=mimalloc_source_level_owner_selection' "$CARD_414" "row414 must point to the source-level owner selection row"
guard_expect_fixed_in_file "$TAG" 'current_blocker_token = "MIMALLOC-SOURCE-LEVEL-OWNER-SELECTION-296X-001"' "$STATE" "current state must point to row415"
guard_expect_fixed_in_file "$TAG" 'latest_card = "296x-414-MIMALLOC-SOURCE-LEVEL-OWNER-REFRESH"' "$STATE" "current state must land row414row413"
guard_expect_fixed_in_file "$TAG" "$SELF_SCRIPT" "$INDEX" "check index must list this guard"

echo "[$TAG] ok"
