#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/../.." && pwd)"
cd "$ROOT_DIR"

bash tools/checks/rust_lifecycle_binding_context_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_binding_context_derived_route_selection_guard.sh

python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family canonical-explicit-phi --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family multi-carrier-exit-phi --check

bash tools/checks/rust_lifecycle_core_context_facts_guard.sh
bash tools/checks/rust_mirbuilder_core_context_plan_oracle_guard.sh
bash tools/checks/rust_lifecycle_core_context_derived_artifact_guard.sh

python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family metadata-context-scalar-source-file --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family metadata-context-region-parent --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family metadata-context-value-caller --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family single-scalar-loop-carrier --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family structured-loop-without-carried-state --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family type-context-value-kind --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family type-context-origin-map --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family type-context-string-literal --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family type-context-value-type --check
python3 tools/rust_lifecycle/convert_mirbuilder_lightweight_facts.py --family type-context-snapshot-restore --check

bash tools/checks/rust_lifecycle_variable_context_simple_map_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_variable_context_simple_map_derived_route_selection_guard.sh

bash tools/checks/rust_lifecycle_variable_context_immutable_borrow_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_variable_context_immutable_borrow_derived_route_selection_guard.sh

bash tools/checks/rust_lifecycle_variable_context_snapshot_restore_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_variable_context_snapshot_restore_derived_route_selection_guard.sh
bash tools/checks/rust_lifecycle_variable_context_snapshot_restore_guard.sh

bash tools/checks/rust_lifecycle_variable_context_carrier_snapshot_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_variable_context_carrier_snapshot_derived_route_selection_guard.sh
bash tools/checks/rust_lifecycle_variable_context_explicit_carrier_snapshot_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_variable_context_explicit_carrier_snapshot_derived_route_selection_guard.sh

bash tools/checks/rust_lifecycle_ordered_map_crate_bundle_guard.sh
bash tools/checks/rust_lifecycle_explicit_phi_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_metadata_context_region_parent_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_metadata_context_value_caller_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_multi_carrier_exit_phi_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_single_scalar_loop_carrier_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_structured_loop_derived_artifact_guard.sh
bash tools/checks/rust_lifecycle_type_context_string_literal_derived_artifact_guard.sh

bash tools/checks/rust_mirbuilder_negative_converter_fixtures_guard.sh
bash tools/checks/rust_lifecycle_no_silent_hardcode_guard.sh

cat <<'REPORT'
matrix=rust-mirbuilder-converter-v0
binding_context=green
canonical_explicit_phi=green
core_context_scalar_counters=green
metadata_context_scalar_source_file=green
metadata_context_region_parent=mir_only
metadata_context_region_parent_backend=skipped_pending_boxed_i64_payload
metadata_context_value_caller=green
multi_carrier_exit_phi=green
single_scalar_loop_carrier=green
structured_loop_without_carried_state=green
type_context_value_kind=green
type_context_origin_map=green
type_context_string_literal=green
type_context_value_type=green
type_context_snapshot_restore=green
variable_context_simple_map=green
returned_read_borrow=Deny(ReturnedReadBorrow)
variable_context_snapshot_restore=green
variable_context_carrier_snapshot=green
variable_context_explicit_carrier_snapshot=green
ordered_map_crate_bundle=green
negative_converter_fixtures=green
no_silent_hardcode=green
shared_emitter=green
summary=ok
REPORT
