#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
TAG="rust-lifecycle-mirbuilder-scalar-known-fastpath-hako-generated-typed-artifact-shadow-consume-set-mapstore-i64-guard"

source "$ROOT/tools/checks/lib/guard_common.sh"

FIXTURE="$ROOT/docs/development/current/main/design/fixtures/rust-lifecycle/mirbuilder-scalar-known-fastpath-hako-generated-typed-artifact-shadow-consume-set-mapstore-i64-v0.json"
CARD="$ROOT/docs/development/current/main/phases/phase-296x/3361-MIRBUILDER-SCALAR-KNOWN-FASTPATH-HAKO-GENERATED-TYPED-ARTIFACT-SHADOW-CONSUME-SET-MAPSTORE-I64-001.md"
ARTIFACT="$ROOT/src/mir/generic_method_route_plan/generated/write_set_mapstore_i64_hako_policy.rs"
GENERATED_MOD="$ROOT/src/mir/generic_method_route_plan/generated/mod.rs"
GENERATOR="$ROOT/tools/rust_lifecycle/generate_write_set_mapstore_route_policy.py"
SHADOW_RS="$ROOT/src/mir/generic_method_route_plan/scalar_known_hako_shadow.rs"
WRITE_ROUTES="$ROOT/src/mir/generic_method_route_plan/write_routes.rs"
PLAN_MOD="$ROOT/src/mir/generic_method_route_plan.rs"
HAKO_POLICY="$ROOT/lang/src/compiler/lib/write_set_mapstore_i64_policy_classifier.hako"
TASK_ORDER="$ROOT/docs/development/current/main/design/mirbuilder-rust-to-hako-converter-task-order-ssot.md"

guard_require_command "$TAG" python3
guard_require_command "$TAG" diff
guard_require_files "$TAG" "$FIXTURE" "$CARD" "$ARTIFACT" "$GENERATED_MOD" "$GENERATOR" "$SHADOW_RS" "$WRITE_ROUTES" "$PLAN_MOD" "$HAKO_POLICY" "$TASK_ORDER"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
python3 "$GENERATOR" --artifact i64_policy > "$TMP"
diff -u "$ARTIFACT" "$TMP"

python3 - "$FIXTURE" "$CARD" "$ARTIFACT" "$GENERATED_MOD" "$GENERATOR" "$SHADOW_RS" "$WRITE_ROUTES" "$PLAN_MOD" "$HAKO_POLICY" "$TASK_ORDER" <<'PY'
import json
import sys
from pathlib import Path

fixture = json.loads(Path(sys.argv[1]).read_text(encoding="utf-8"))
card = Path(sys.argv[2]).read_text(encoding="utf-8")
artifact = Path(sys.argv[3]).read_text(encoding="utf-8")
generated_mod = Path(sys.argv[4]).read_text(encoding="utf-8")
generator = Path(sys.argv[5]).read_text(encoding="utf-8")
shadow_rs = Path(sys.argv[6]).read_text(encoding="utf-8")
write_routes = Path(sys.argv[7]).read_text(encoding="utf-8")
plan_mod = Path(sys.argv[8]).read_text(encoding="utf-8")
hako_policy = Path(sys.argv[9]).read_text(encoding="utf-8")
task_order = Path(sys.argv[10]).read_text(encoding="utf-8")


def need(cond, msg):
    if not cond:
        raise SystemExit(msg)


token = "MIRBUILDER-SCALAR-KNOWN-FASTPATH-HAKO-GENERATED-TYPED-ARTIFACT-SHADOW-CONSUME-SET-MAPSTORE-I64-001"
next_card = "MIRBUILDER-CARRIER-TYPE-SCALAR-KNOWN-WRITE-SET-MAPSTORE-ANY-WRITE-BOUNDARY-BASIS-001"

need(fixture.get("schema_version") == 0, "bad schema_version")
need(fixture.get("kind") == "MirBuilderScalarKnownFastpathHakoGeneratedTypedArtifactShadowConsumeSetMapstoreI64V1", "bad kind")
need(fixture.get("token") == token, "bad token")
need(fixture.get("selected_next_card") == next_card, "bad selected next")

decision = fixture.get("decision") or {}
need(decision.get("kind") == "GeneratedTypedHakoArtifactShadowConsume", "bad decision kind")
need(decision.get("route_kind") == "MapStoreI64", "bad route kind")
need(decision.get("rust_authority") == "retained", "rust authority must be retained")
need(decision.get("runtime_build_parses_hako_source_text") is False, "runtime text parsing must be false")
need(decision.get("build_rs_hako_compiler_invocation") is False, "build.rs hako invocation must be false")

claims = fixture.get("claims") or {}
for key in [
    "generated_typed_hako_artifact_shadow_consumed",
    "checked_in_generated_typed_artifact",
    "include_str_split_shadow_parsing_removed",
    "mapstore_i64_fastpath_shadow_still_consumed",
    "rust_hako_policy_match",
    "generator_check_guard",
    "rust_authority_retained",
]:
    need(claims.get(key) == 1, f"missing positive claim: {key}")
for key in [
    "runtime_hako_source_text_parsing",
    "hako_runtime_route_authority",
    "rust_fastpath_rewired",
    "route_selection_authority_switch",
    "backend_lowering_authority",
    "runtime_mutation_authority",
    "publication_execution",
    "build_rs_hako_compiler_invocation",
    "live_hako_authority",
    "caller_orientation_runtime_path",
    "new_backend_route",
    "new_abi",
    "runtime_fallback",
    "source_selfhost_claim",
]:
    need(claims.get(key) == 0, f"forbidden claim drift: {key}")

for needle in [
    "@generated by tools/rust_lifecycle/generate_write_set_mapstore_route_policy.py",
    "pub(crate) struct HakoMapStoreI64Policy",
    "WRITE_SET_MAPSTORE_I64_HAKO_POLICY",
    "route_kind: GenericMethodRouteKind::MapStoreI64",
    "core_op: CoreMethodOp::MapSet",
    "lowering_tier: CoreMethodLoweringTier::ColdFallback",
    "value_demand: GenericMethodValueDemand::WriteAny",
    'value_boundary: "ScalarI64"',
    'role: "classifier_policy_mirror_only"',
]:
    need(needle in artifact, f"artifact missing: {needle}")

need("pub(super) mod write_set_mapstore_i64_hako_policy;" in generated_mod, "generated mod missing policy module")
need("mod generated;" in plan_mod, "route plan module does not include generated module")

for forbidden in [
    "include_str!",
    "row.split('|')",
    "write_set_mapstore_i64_policy_classifier.hako",
    "map_store_i64_set_surface|",
]:
    need(forbidden not in shadow_rs, f"runtime consumer still has source-text parser debt: {forbidden}")
for needle in [
    "WRITE_SET_MAPSTORE_I64_HAKO_POLICY",
    "assert_hako_policy_matches_rust",
    "GenericMethodRouteKind::MapStoreI64",
    "GenericMethodValueDemand::WriteAny",
]:
    need(needle in shadow_rs, f"runtime typed artifact consumer missing: {needle}")

need("scalar_known_hako_shadow::mapstore_i64_hako_route_authority_pilot_decision()" in write_routes, "fast path no longer consumes shadow decision")
need("map_store_i64_set_surface|SetSurfacePolicy|MapStoreI64" in hako_policy, "hako source row missing")
need("read_rows" in generator and "MapStore RoutePolicyRow" in generator, "generator does not read policy rows")

for needle in [
    token,
    next_card,
    "generated_typed_hako_artifact_shadow_consumed = 1",
    "runtime_hako_source_text_parsing = 0",
    "hako_runtime_route_authority = 0",
    "source_selfhost_claim = 0",
]:
    need(needle in card, f"card missing: {needle}")
for needle in [token, next_card]:
    need(needle in task_order, f"task-order missing: {needle}")
PY

cat <<'REPORT'
output_contract=rust-lifecycle-mirbuilder-scalar-known-fastpath-hako-generated-typed-artifact-shadow-consume-set-mapstore-i64-guard-v0
token=MIRBUILDER-SCALAR-KNOWN-FASTPATH-HAKO-GENERATED-TYPED-ARTIFACT-SHADOW-CONSUME-SET-MAPSTORE-I64-001
generated_typed_hako_artifact_shadow_consumed=1
checked_in_generated_typed_artifact=1
runtime_hako_source_text_parsing=0
include_str_split_shadow_parsing_removed=1
mapstore_i64_fastpath_shadow_still_consumed=1
rust_hako_policy_match=1
generator_check_guard=1
rust_authority_retained=1
hako_runtime_route_authority=0
rust_fastpath_rewired=0
route_selection_authority_switch=0
backend_lowering_authority=0
runtime_mutation_authority=0
publication_execution=0
build_rs_hako_compiler_invocation=0
live_hako_authority=0
caller_orientation_runtime_path=0
new_backend_route=0
new_abi=0
runtime_fallback=0
source_selfhost_claim=0
selected_next_card=MIRBUILDER-CARRIER-TYPE-SCALAR-KNOWN-WRITE-SET-MAPSTORE-ANY-WRITE-BOUNDARY-BASIS-001
summary=ok
REPORT
