use crate::{ASTNode, Span};

impl ASTNode {
    /// ASTノードからSpan情報を取得
    pub fn span(&self) -> Span {
        match self {
            ASTNode::Program { span, .. } => *span,
            ASTNode::Assignment { span, .. } => *span,
            ASTNode::Print { span, .. } => *span,
            ASTNode::If { span, .. } => *span,
            ASTNode::Loop { span, .. } => *span,
            ASTNode::LoopRange { span, .. } => *span,
            ASTNode::Return { span, .. } => *span,
            ASTNode::Break { span, .. } => *span,
            ASTNode::Continue { span, .. } => *span,
            ASTNode::UsingStatement { span, .. } => *span,
            ASTNode::ImportStatement { span, .. } => *span,
            ASTNode::BuildGate { span, .. } => *span,
            ASTNode::Nowait { span, .. } => *span,
            ASTNode::TaskScope { span, .. } => *span,
            ASTNode::ContextScope { span, .. } => *span,
            ASTNode::FastMemRegion { span, .. } => *span,
            ASTNode::Arrow { span, .. } => *span,
            ASTNode::TryCatch { span, .. } => *span,
            ASTNode::Throw { span, .. } => *span,
            ASTNode::BoxDeclaration { span, .. } => *span,
            ASTNode::EnumDeclaration { span, .. } => *span,
            ASTNode::BrandDeclaration { span, .. } => *span,
            ASTNode::TypeAliasDeclaration { span, .. } => *span,
            ASTNode::FunctionDeclaration { span, .. } => *span,
            ASTNode::GlobalVar { span, .. } => *span,
            ASTNode::StaticConstTable { span, .. } => *span,
            ASTNode::Literal { span, .. } => *span,
            ASTNode::Variable { span, .. } => *span,
            ASTNode::UnaryOp { span, .. } => *span,
            ASTNode::BinaryOp { span, .. } => *span,
            ASTNode::CheckExpr { span, .. } => *span,
            ASTNode::MethodCall { span, .. } => *span,
            ASTNode::FieldAccess { span, .. } => *span,
            ASTNode::Index { span, .. } => *span,
            ASTNode::New { span, .. } => *span,
            ASTNode::This { span, .. } => *span,
            ASTNode::Me { span, .. } => *span,
            ASTNode::FromCall { span, .. } => *span,
            ASTNode::ThisField { span, .. } => *span,
            ASTNode::MeField { span, .. } => *span,
            ASTNode::Local { span, .. } => *span,
            ASTNode::Outbox { span, .. } => *span,
            ASTNode::FunctionCall { span, .. } => *span,
            ASTNode::Call { span, .. } => *span,
            ASTNode::AwaitExpression { span, .. } => *span,
            ASTNode::MatchExpr { span, .. } => *span,
            ASTNode::EnumMatchExpr { span, .. } => *span,
            ASTNode::QMarkPropagate { span, .. } => *span,
            ASTNode::Lambda { span, .. } => *span,
            ASTNode::ArrayLiteral { span, .. } => *span,
            ASTNode::MapLiteral { span, .. } => *span,
            ASTNode::RecordLiteral { span, .. } => *span,
            ASTNode::RecordUpdate { span, .. } => *span,
            ASTNode::BlockExpr { span, .. } => *span,
            ASTNode::ScopeBox { span, .. } => *span,
            ASTNode::GroupedAssignmentExpr { span, .. } => *span,
        }
    }
}
