// Selected Dynamic V2 static artifact descriptor ABI (revision 1).
//
// This header owns only the fixed byte layout embedded in Boundary-produced
// objects and executables.  MIR/candidate metadata remains the source of the
// values, and the Rust link transaction is the sole post-link observer.

#pragma once
#include <stdint.h>

#define HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_SYMBOL \
  "hako_dynamic_v2_static_artifact_descriptor_v1"
#define HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_SECTION \
  ".hako_dynamic_v2_descriptor"
#define HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_MAGIC "HAKODV2"

#define HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_SCHEMA UINT32_C(1)
#define HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_SIZE UINT32_C(192)
#define HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_MAGIC_SIZE UINT32_C(8)
#define HAKO_DYNAMIC_V2_ARTIFACT_CONTRACT_CAPACITY UINT32_C(32)
#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_SYMBOL_CAPACITY UINT32_C(40)
#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_SIZE UINT32_C(52)
#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_COUNT UINT32_C(2)

#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_MAGIC UINT32_C(0)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_SCHEMA UINT32_C(8)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_SIZE UINT32_C(12)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_PROFILE UINT32_C(16)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_ABI UINT32_C(20)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_WIRE UINT32_C(24)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_ENTRY_COUNT UINT32_C(28)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_COMPILER_DOMAIN UINT32_C(32)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_INVOCATION_ORDINAL UINT32_C(40)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_REGISTRY_GENERATION UINT32_C(48)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_CONTRACT_ID UINT32_C(56)
#define HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_ENTRIES UINT32_C(88)

#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_OFFSET_SITE_ID UINT32_C(0)
#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_OFFSET_ID UINT32_C(4)
#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_OFFSET_ARITY UINT32_C(8)
#define HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_OFFSET_SYMBOL UINT32_C(12)

#if defined(__cplusplus)
#define HAKO_DYNAMIC_V2_ARTIFACT_STATIC_ASSERT static_assert
#else
#define HAKO_DYNAMIC_V2_ARTIFACT_STATIC_ASSERT _Static_assert
#endif

HAKO_DYNAMIC_V2_ARTIFACT_STATIC_ASSERT(
    HAKO_DYNAMIC_V2_ARTIFACT_OFFSET_ENTRIES +
            HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_COUNT *
                HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_SIZE ==
        HAKO_DYNAMIC_V2_ARTIFACT_DESCRIPTOR_SIZE,
    "Dynamic V2 artifact descriptor size");
HAKO_DYNAMIC_V2_ARTIFACT_STATIC_ASSERT(
    HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_OFFSET_SYMBOL +
            HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_SYMBOL_CAPACITY ==
        HAKO_DYNAMIC_V2_ARTIFACT_ENTRY_SIZE,
    "Dynamic V2 artifact entry size");

#undef HAKO_DYNAMIC_V2_ARTIFACT_STATIC_ASSERT
