#!/usr/bin/env python3
"""Generate C global-call route descriptor rows from Rust route proof metadata."""

from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUST_MODEL = ROOT / "src/mir/global_call_route_plan/model.rs"
C_OUT = ROOT / "lang/c-abi/shims/hako_llvmc_ffi_global_call_route_registry.inc"


def parse_global_call_proofs() -> list[str]:
    text = RUST_MODEL.read_text()
    enum_match = re.search(
        r"enum\s+GlobalCallProof\s*\{(?P<body>.*?)\n\}",
        text,
        re.S,
    )
    if not enum_match:
        raise SystemExit("failed to find GlobalCallProof enum")
    variants = [
        item.strip()
        for item in enum_match.group("body").split(",")
        if item.strip() and not item.strip().startswith("//")
    ]
    variants = [re.sub(r"\s.*$", "", item) for item in variants]
    if not variants:
        raise SystemExit("GlobalCallProof enum has no variants")

    fn_match = re.search(
        r"pub\(super\)\s+fn\s+as_json_name\(self\)\s*->\s*&'static\s+str\s*\{",
        text,
        re.S,
    )
    if not fn_match:
        raise SystemExit("failed to find GlobalCallProof::as_json_name")
    body = balanced_body_after_open_brace(text, fn_match.end() - 1)
    proofs_by_variant: dict[str, str] = {}
    for variant in variants:
        pattern = (
            r"Self::"
            + re.escape(variant)
            + r"\s*=>\s*(?:\{\s*)?\"(?P<proof>[^\"]+)\""
        )
        match = re.search(pattern, body, re.S)
        if not match:
            raise SystemExit(f"missing as_json_name arm for GlobalCallProof::{variant}")
        proof = match.group("proof")
        if not proof.startswith("typed_global_call_"):
            raise SystemExit(
                f"unexpected GlobalCallProof JSON name for {variant}: {proof}"
            )
        if proof in proofs_by_variant.values():
            raise SystemExit(f"duplicate GlobalCallProof JSON name: {proof}")
        proofs_by_variant[variant] = proof
    return [proofs_by_variant[variant] for variant in variants]


def balanced_body_after_open_brace(text: str, open_brace_index: int) -> str:
    depth = 0
    for index in range(open_brace_index, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace_index + 1 : index]
    raise SystemExit("unterminated Rust function body")


def cq(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_c(proofs: list[str]) -> str:
    lines = [
        "/* @generated by tools/global_call_route_descriptor_codegen.py */",
        "/* source: src/mir/global_call_route_plan/model.rs */",
        "#ifndef HAKO_LLVMC_GLOBAL_CALL_ROUTE_REGISTRY_INC",
        "#define HAKO_LLVMC_GLOBAL_CALL_ROUTE_REGISTRY_INC",
        "",
        "      struct HakoLlvmcGlobalCallProofRegistryRow {",
        "        const char* proof;",
        "      };",
        "",
        "      static const struct HakoLlvmcGlobalCallProofRegistryRow",
        "          hako_llvmc_global_call_proof_registry_rows[] = {",
    ]
    for proof in proofs:
        lines.append(f"              {{{cq(proof)}}},")
    lines.extend(
        [
            "          };",
            "",
            "      auto int hako_llvmc_global_call_proof_registry_contains(",
            "          const char* proof) {",
            "        size_t i = 0;",
            "        if (!proof) return 0;",
            "        for (i = 0;",
            "             i < sizeof(hako_llvmc_global_call_proof_registry_rows) /",
            "                     sizeof(hako_llvmc_global_call_proof_registry_rows[0]);",
            "             i++) {",
            "          const struct HakoLlvmcGlobalCallProofRegistryRow* row =",
            "              &hako_llvmc_global_call_proof_registry_rows[i];",
            "          if (row->proof && !strcmp(row->proof, proof)) return 1;",
            "        }",
            "        return 0;",
            "      }",
            "",
            "#endif /* HAKO_LLVMC_GLOBAL_CALL_ROUTE_REGISTRY_INC */",
            "",
        ]
    )
    return "\n".join(lines)


def write_or_check(path: Path, content: str, check: bool) -> bool:
    old = path.read_text() if path.exists() else ""
    if old == content:
        return False
    if check:
        diff = "\n".join(
            difflib.unified_diff(
                old.splitlines(),
                content.splitlines(),
                fromfile=str(path),
                tofile=str(path) + " (generated)",
                lineterm="",
            )
        )
        raise SystemExit(diff)
    path.write_text(content)
    return True


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    changed = write_or_check(C_OUT, render_c(parse_global_call_proofs()), args.check)
    print(f"global_call_route_descriptors={'changed' if changed else 'unchanged'}")


if __name__ == "__main__":
    main()
