#!/usr/bin/env python3
"""Generate C user-box method route descriptor rows from Rust route metadata."""

from __future__ import annotations

import argparse
import difflib
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RUST_ROUTE = ROOT / "src/mir/user_box_method_route_plan.rs"
C_OUT = ROOT / "lang/c-abi/shims/hako_llvmc_ffi_user_box_method_route_registry.inc"


def parse_rows() -> list[dict[str, str]]:
    text = RUST_ROUTE.read_text()
    route_id = parse_literal_return(text, "route_id")
    core_op = parse_literal_return(text, "core_op")
    route_kind_body = find_rust_fn_body(text, "route_kind")
    proof_body = find_rust_fn_body(text, "proof")
    definition_owner_body = find_rust_fn_body(text, "definition_owner")
    emit_trace_body = find_rust_fn_body(text, "emit_trace_consumer")

    route_birth = require_string(route_kind_body, "user_box.birth")
    route_method = require_string(route_kind_body, "user_box.method")
    proof_birth = require_string(proof_body, "typed_user_box_birth_same_module")
    proof_method = require_string(proof_body, "typed_user_box_method_same_module")
    definition_owner = require_string(definition_owner_body, "typed_object_method")
    trace_birth = require_string(
        emit_trace_body, "mir_call_user_box_birth_same_module_emit"
    )
    trace_method = require_string(
        emit_trace_body, "mir_call_user_box_method_same_module_emit"
    )

    return [
        {
            "method_kind": "birth",
            "route_id": route_id,
            "core_op": core_op,
            "route_kind": route_birth,
            "proof": proof_birth,
            "route_proof": proof_birth,
            "definition_owner": definition_owner,
            "emit_trace_consumer": trace_birth,
            "emit_kind": "direct_function_call",
        },
        {
            "method_kind": "non_birth",
            "route_id": route_id,
            "core_op": core_op,
            "route_kind": route_method,
            "proof": proof_method,
            "route_proof": proof_method,
            "definition_owner": definition_owner,
            "emit_trace_consumer": trace_method,
            "emit_kind": "direct_function_call",
        },
    ]


def parse_literal_return(text: str, fn_name: str) -> str:
    body = find_rust_fn_body(text, fn_name)
    match = re.search(r"^\s*\"(?P<value>[^\"]+)\"\s*$", body, re.S)
    if not match:
        raise SystemExit(f"expected {fn_name} to return one string literal")
    return match.group("value")


def require_string(text: str, value: str) -> str:
    if f'"{value}"' not in text:
        raise SystemExit(f"missing expected Rust route string {value!r}")
    return value


def find_rust_fn_body(text: str, fn_name: str) -> str:
    match = re.search(
        rf"\bfn\s+{re.escape(fn_name)}\s*\([^)]*\)\s*(?:->\s*[^\{{]+)?\{{",
        text,
        re.S,
    )
    if not match:
        raise SystemExit(f"failed to find Rust function {fn_name}")
    return balanced_body_after_open_brace(text, match.end() - 1).strip()


def balanced_body_after_open_brace(text: str, open_brace_index: int) -> str:
    depth = 0
    for index in range(open_brace_index, len(text)):
        char = text[index]
        if char == "{":
            depth += 1
        elif char == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace_index + 1 : index]
    raise SystemExit("unterminated Rust function body")


def cq(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def render_c(rows: list[dict[str, str]]) -> str:
    lines = [
        "/* @generated by tools/user_box_method_route_descriptor_codegen.py */",
        "/* source: src/mir/user_box_method_route_plan.rs */",
        "#ifndef HAKO_LLVMC_USER_BOX_METHOD_ROUTE_REGISTRY_INC",
        "#define HAKO_LLVMC_USER_BOX_METHOD_ROUTE_REGISTRY_INC",
        "",
        "      struct HakoLlvmcUserBoxMethodRouteRegistryRow {",
        "        const char* method_kind;",
        "        const char* route_id;",
        "        const char* core_op;",
        "        const char* route_kind;",
        "        const char* proof;",
        "        const char* route_proof;",
        "        const char* definition_owner;",
        "        const char* emit_trace_consumer;",
        "        const char* emit_kind;",
        "      };",
        "",
        "      static const struct HakoLlvmcUserBoxMethodRouteRegistryRow",
        "          hako_llvmc_user_box_method_route_registry_rows[] = {",
    ]
    for row in rows:
        lines.extend(
            [
                "              {",
                f"                  {cq(row['method_kind'])},",
                f"                  {cq(row['route_id'])},",
                f"                  {cq(row['core_op'])},",
                f"                  {cq(row['route_kind'])},",
                f"                  {cq(row['proof'])},",
                f"                  {cq(row['route_proof'])},",
                f"                  {cq(row['definition_owner'])},",
                f"                  {cq(row['emit_trace_consumer'])},",
                f"                  {cq(row['emit_kind'])},",
                "              },",
            ]
        )
    lines.extend(
        [
            "          };",
            "",
            "      auto int hako_llvmc_user_box_method_route_registry_method_kind_matches(",
            "          const char* method_kind,",
            "          const char* method) {",
            "        if (!(method_kind && method)) return 0;",
            "        if (!strcmp(method_kind, \"birth\")) return !strcmp(method, \"birth\");",
            "        if (!strcmp(method_kind, \"non_birth\")) return strcmp(method, \"birth\") != 0;",
            "        return 0;",
            "      }",
            "",
            "      auto const struct HakoLlvmcUserBoxMethodRouteRegistryRow*",
            "      hako_llvmc_user_box_method_route_registry_find_direct(",
            "          const char* route_id,",
            "          const char* core_op,",
            "          const char* route_kind,",
            "          const char* method,",
            "          const char* proof,",
            "          const char* route_proof) {",
            "        size_t i = 0;",
            "        for (i = 0;",
            "             i < sizeof(hako_llvmc_user_box_method_route_registry_rows) /",
            "                     sizeof(hako_llvmc_user_box_method_route_registry_rows[0]);",
            "             i++) {",
            "          const struct HakoLlvmcUserBoxMethodRouteRegistryRow* row =",
            "              &hako_llvmc_user_box_method_route_registry_rows[i];",
            "          if (row->route_id && row->core_op && row->route_kind &&",
            "              row->proof && row->route_proof && route_id && core_op &&",
            "              route_kind && method && proof && route_proof &&",
            "              hako_llvmc_user_box_method_route_registry_method_kind_matches(",
            "                  row->method_kind, method) &&",
            "              !strcmp(row->route_id, route_id) &&",
            "              !strcmp(row->core_op, core_op) &&",
            "              !strcmp(row->route_kind, route_kind) &&",
            "              !strcmp(row->proof, proof) &&",
            "              !strcmp(row->route_proof, route_proof)) {",
            "            return row;",
            "          }",
            "        }",
            "        return NULL;",
            "      }",
            "",
            "      auto int hako_llvmc_user_box_method_route_registry_direct_is(",
            "          const char* route_id,",
            "          const char* core_op,",
            "          const char* route_kind,",
            "          const char* method,",
            "          const char* proof,",
            "          const char* route_proof,",
            "          const char* definition_owner,",
            "          const char* emit_kind) {",
            "        const struct HakoLlvmcUserBoxMethodRouteRegistryRow* row =",
            "            hako_llvmc_user_box_method_route_registry_find_direct(",
            "                route_id, core_op, route_kind, method, proof, route_proof);",
            "        if (!(row && row->definition_owner && row->emit_kind &&",
            "              definition_owner && emit_kind)) {",
            "          return 0;",
            "        }",
            "        return !strcmp(row->definition_owner, definition_owner) &&",
            "               !strcmp(row->emit_kind, emit_kind);",
            "      }",
            "",
            "#endif",
            "",
        ]
    )
    return "\n".join(lines)


def write_if_changed(path: Path, content: str, check: bool) -> None:
    old = path.read_text() if path.exists() else ""
    if old == content:
        if check:
            print("user_box_method_route_descriptors=unchanged")
        return
    if check:
        diff = "".join(
            difflib.unified_diff(
                old.splitlines(True),
                content.splitlines(True),
                fromfile=str(path),
                tofile=str(path) + " (generated)",
            )
        )
        raise SystemExit(diff)
    path.write_text(content)
    print(f"generated {path}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    write_if_changed(C_OUT, render_c(parse_rows()), args.check)


if __name__ == "__main__":
    main()
